/** Generated by scripts/gen-uw-ep-plus-tracks.mjs — do not edit by hand. */

export type UwEpPlusMilestone = {
  readonly level: number
  readonly marginalStones: number
  readonly stat: string
}

export const UW_EP_PLUS_MILESTONES: Record<string, readonly UwEpPlusMilestone[]> = {
  "ultimatePlusChainLightningSmiteLevel": [
    {
      "level": 0,
      "marginalStones": 0,
      "stat": "0.05%"
    },
    {
      "level": 1,
      "marginalStones": 300,
      "stat": "0.10%"
    },
    {
      "level": 2,
      "marginalStones": 375,
      "stat": "0.15%"
    },
    {
      "level": 3,
      "marginalStones": 475,
      "stat": "0.20%"
    },
    {
      "level": 4,
      "marginalStones": 600,
      "stat": "0.25%"
    },
    {
      "level": 5,
      "marginalStones": 725,
      "stat": "0.30%"
    },
    {
      "level": 6,
      "marginalStones": 925,
      "stat": "0.35%"
    },
    {
      "level": 7,
      "marginalStones": 1150,
      "stat": "0.40%"
    },
    {
      "level": 8,
      "marginalStones": 1450,
      "stat": "0.45%"
    },
    {
      "level": 9,
      "marginalStones": 1800,
      "stat": "0.50%"
    },
    {
      "level": 10,
      "marginalStones": 2200,
      "stat": "0.55%"
    },
    {
      "level": 11,
      "marginalStones": 2650,
      "stat": "0.60%"
    }
  ],
  "ultimatePlusSmartMissilesCoverFireLevel": [
    {
      "level": 0,
      "marginalStones": 0,
      "stat": "13s"
    },
    {
      "level": 1,
      "marginalStones": 300,
      "stat": "12s"
    },
    {
      "level": 2,
      "marginalStones": 375,
      "stat": "11s"
    },
    {
      "level": 3,
      "marginalStones": 475,
      "stat": "10s"
    },
    {
      "level": 4,
      "marginalStones": 600,
      "stat": "9s"
    },
    {
      "level": 5,
      "marginalStones": 725,
      "stat": "8s"
    },
    {
      "level": 6,
      "marginalStones": 925,
      "stat": "7s"
    },
    {
      "level": 7,
      "marginalStones": 1150,
      "stat": "6s"
    },
    {
      "level": 8,
      "marginalStones": 1450,
      "stat": "5s"
    },
    {
      "level": 9,
      "marginalStones": 1800,
      "stat": "4s"
    },
    {
      "level": 10,
      "marginalStones": 2200,
      "stat": "3s"
    },
    {
      "level": 11,
      "marginalStones": 2650,
      "stat": "2s"
    }
  ],
  "ultimatePlusDeathWaveKillWallLevel": [
    {
      "level": 0,
      "marginalStones": 0,
      "stat": "x3"
    },
    {
      "level": 1,
      "marginalStones": 400,
      "stat": "x4"
    },
    {
      "level": 2,
      "marginalStones": 500,
      "stat": "x6"
    },
    {
      "level": 3,
      "marginalStones": 610,
      "stat": "x9"
    },
    {
      "level": 4,
      "marginalStones": 730,
      "stat": "x13"
    },
    {
      "level": 5,
      "marginalStones": 860,
      "stat": "x18"
    },
    {
      "level": 6,
      "marginalStones": 1000,
      "stat": "x24"
    },
    {
      "level": 7,
      "marginalStones": 1150,
      "stat": "x31"
    },
    {
      "level": 8,
      "marginalStones": 1300,
      "stat": "x39"
    },
    {
      "level": 9,
      "marginalStones": 1500,
      "stat": "x48"
    },
    {
      "level": 10,
      "marginalStones": 1700,
      "stat": "x58"
    },
    {
      "level": 11,
      "marginalStones": 1950,
      "stat": "x69"
    },
    {
      "level": 12,
      "marginalStones": 2200,
      "stat": "x81"
    },
    {
      "level": 13,
      "marginalStones": 2450,
      "stat": "x94"
    },
    {
      "level": 14,
      "marginalStones": 2700,
      "stat": "x108"
    }
  ],
  "ultimatePlusChronoFieldChronoLoopLevel": [
    {
      "level": 0,
      "marginalStones": 0,
      "stat": "10%"
    },
    {
      "level": 1,
      "marginalStones": 400,
      "stat": "15%"
    },
    {
      "level": 2,
      "marginalStones": 500,
      "stat": "20%"
    },
    {
      "level": 3,
      "marginalStones": 610,
      "stat": "25%"
    },
    {
      "level": 4,
      "marginalStones": 730,
      "stat": "30%"
    },
    {
      "level": 5,
      "marginalStones": 860,
      "stat": "35%"
    },
    {
      "level": 6,
      "marginalStones": 1000,
      "stat": "40%"
    },
    {
      "level": 7,
      "marginalStones": 1150,
      "stat": "45%"
    },
    {
      "level": 8,
      "marginalStones": 1300,
      "stat": "50%"
    },
    {
      "level": 9,
      "marginalStones": 1500,
      "stat": "55%"
    },
    {
      "level": 10,
      "marginalStones": 1700,
      "stat": "60%"
    },
    {
      "level": 11,
      "marginalStones": 1950,
      "stat": "65%"
    },
    {
      "level": 12,
      "marginalStones": 2200,
      "stat": "70%"
    },
    {
      "level": 13,
      "marginalStones": 2450,
      "stat": "75%"
    }
  ],
  "ultimatePlusInnerLandMinesChargedMinesLevel": [
    {
      "level": 0,
      "marginalStones": 0,
      "stat": "0.50/s"
    },
    {
      "level": 1,
      "marginalStones": 300,
      "stat": "1.50/s"
    },
    {
      "level": 2,
      "marginalStones": 360,
      "stat": "2.90/s"
    },
    {
      "level": 3,
      "marginalStones": 430,
      "stat": "4.70/s"
    },
    {
      "level": 4,
      "marginalStones": 510,
      "stat": "6.90/s"
    },
    {
      "level": 5,
      "marginalStones": 620,
      "stat": "9.50/s"
    },
    {
      "level": 6,
      "marginalStones": 750,
      "stat": "12.50/s"
    },
    {
      "level": 7,
      "marginalStones": 900,
      "stat": "15.90/s"
    },
    {
      "level": 8,
      "marginalStones": 1100,
      "stat": "19.70/s"
    },
    {
      "level": 9,
      "marginalStones": 1350,
      "stat": "23.90/s"
    },
    {
      "level": 10,
      "marginalStones": 1650,
      "stat": "28.50/s"
    },
    {
      "level": 11,
      "marginalStones": 2000,
      "stat": "33.50/s"
    },
    {
      "level": 12,
      "marginalStones": 2400,
      "stat": "38.90/s"
    },
    {
      "level": 13,
      "marginalStones": 2850,
      "stat": "44.70/s"
    },
    {
      "level": 14,
      "marginalStones": 3350,
      "stat": "50.90/s"
    }
  ],
  "ultimatePlusGoldenTowerGoldenComboLevel": [
    {
      "level": 0,
      "marginalStones": 0,
      "stat": "0.03%"
    },
    {
      "level": 1,
      "marginalStones": 300,
      "stat": "0.06%"
    },
    {
      "level": 2,
      "marginalStones": 360,
      "stat": "0.09%"
    },
    {
      "level": 3,
      "marginalStones": 430,
      "stat": "0.12%"
    },
    {
      "level": 4,
      "marginalStones": 510,
      "stat": "0.15%"
    },
    {
      "level": 5,
      "marginalStones": 620,
      "stat": "0.18%"
    },
    {
      "level": 6,
      "marginalStones": 750,
      "stat": "0.21%"
    },
    {
      "level": 7,
      "marginalStones": 900,
      "stat": "0.24%"
    },
    {
      "level": 8,
      "marginalStones": 1100,
      "stat": "0.27%"
    },
    {
      "level": 9,
      "marginalStones": 1350,
      "stat": "0.30%"
    },
    {
      "level": 10,
      "marginalStones": 1650,
      "stat": "0.33%"
    },
    {
      "level": 11,
      "marginalStones": 2050,
      "stat": "0.36%"
    },
    {
      "level": 12,
      "marginalStones": 2600,
      "stat": "0.39%"
    },
    {
      "level": 13,
      "marginalStones": 3300,
      "stat": "0.42%"
    },
    {
      "level": 14,
      "marginalStones": 4150,
      "stat": "0.45%"
    }
  ],
  "ultimatePlusPoisonSwampDeathCreepLevel": [
    {
      "level": 0,
      "marginalStones": 0,
      "stat": "120%"
    },
    {
      "level": 1,
      "marginalStones": 300,
      "stat": "190%"
    },
    {
      "level": 2,
      "marginalStones": 375,
      "stat": "260%"
    },
    {
      "level": 3,
      "marginalStones": 475,
      "stat": "330%"
    },
    {
      "level": 4,
      "marginalStones": 600,
      "stat": "400%"
    },
    {
      "level": 5,
      "marginalStones": 725,
      "stat": "470%"
    },
    {
      "level": 6,
      "marginalStones": 925,
      "stat": "540%"
    },
    {
      "level": 7,
      "marginalStones": 1150,
      "stat": "610%"
    },
    {
      "level": 8,
      "marginalStones": 1450,
      "stat": "680%"
    },
    {
      "level": 9,
      "marginalStones": 1800,
      "stat": "750%"
    },
    {
      "level": 10,
      "marginalStones": 2200,
      "stat": "820%"
    },
    {
      "level": 11,
      "marginalStones": 2650,
      "stat": "890%"
    },
    {
      "level": 12,
      "marginalStones": 3150,
      "stat": "960%"
    },
    {
      "level": 13,
      "marginalStones": 3700,
      "stat": "1030%"
    },
    {
      "level": 14,
      "marginalStones": 4300,
      "stat": "1110%"
    }
  ],
  "ultimatePlusBlackHoleConsumeLevel": [
    {
      "level": 0,
      "marginalStones": 0,
      "stat": "0.05%"
    },
    {
      "level": 1,
      "marginalStones": 400,
      "stat": "0.10%"
    },
    {
      "level": 2,
      "marginalStones": 500,
      "stat": "0.15%"
    },
    {
      "level": 3,
      "marginalStones": 610,
      "stat": "0.20%"
    },
    {
      "level": 4,
      "marginalStones": 730,
      "stat": "0.25%"
    },
    {
      "level": 5,
      "marginalStones": 860,
      "stat": "0.30%"
    },
    {
      "level": 6,
      "marginalStones": 1000,
      "stat": "0.35%"
    },
    {
      "level": 7,
      "marginalStones": 1150,
      "stat": "0.40%"
    },
    {
      "level": 8,
      "marginalStones": 1300,
      "stat": "0.45%"
    },
    {
      "level": 9,
      "marginalStones": 1500,
      "stat": "0.50%"
    },
    {
      "level": 10,
      "marginalStones": 1700,
      "stat": "0.55%"
    },
    {
      "level": 11,
      "marginalStones": 1950,
      "stat": "0.60%"
    },
    {
      "level": 12,
      "marginalStones": 2200,
      "stat": "0.65%"
    },
    {
      "level": 13,
      "marginalStones": 2450,
      "stat": "0.70%"
    },
    {
      "level": 14,
      "marginalStones": 2700,
      "stat": "0.75%"
    }
  ],
  "ultimatePlusSpotlightLightRangeLevel": [
    {
      "level": 0,
      "marginalStones": 0,
      "stat": "1%"
    },
    {
      "level": 1,
      "marginalStones": 400,
      "stat": "2%"
    },
    {
      "level": 2,
      "marginalStones": 500,
      "stat": "3%"
    },
    {
      "level": 3,
      "marginalStones": 610,
      "stat": "4%"
    },
    {
      "level": 4,
      "marginalStones": 730,
      "stat": "5%"
    },
    {
      "level": 5,
      "marginalStones": 860,
      "stat": "6%"
    },
    {
      "level": 6,
      "marginalStones": 1000,
      "stat": "7%"
    },
    {
      "level": 7,
      "marginalStones": 1150,
      "stat": "8%"
    },
    {
      "level": 8,
      "marginalStones": 1300,
      "stat": "9%"
    },
    {
      "level": 9,
      "marginalStones": 1500,
      "stat": "10%"
    },
    {
      "level": 10,
      "marginalStones": 1700,
      "stat": "11%"
    },
    {
      "level": 11,
      "marginalStones": 1950,
      "stat": "12%"
    },
    {
      "level": 12,
      "marginalStones": 2200,
      "stat": "13%"
    },
    {
      "level": 13,
      "marginalStones": 2450,
      "stat": "14%"
    },
    {
      "level": 14,
      "marginalStones": 2700,
      "stat": "15%"
    }
  ]
} as const
