/**
 * Authoritative lab ladder data from `tables/labs/` JSON.
 * Marginal coins and upgrade times for these labs override `tower-labs.json`.
 * Loaded at runtime from `public/tables/labs/` (see loadGodTables.ts).
 * Generated by scripts/sync-lab-god-tables.mjs — do not hand-edit store helpers.
 */

export type LabGodTime = {
  display: string
  seconds: number
}

export type LabGodLevel = {
  level: number
  value: number
  time: LabGodTime
  gems: number
  coins: number
  totalTime: LabGodTime
  totalGems: number
  totalCoins: number
}

export type LabGodTable = {
  name: string
  maxLevel: number
  levels: LabGodLevel[]
}

let labGodTables: Record<string, LabGodTable> = {}

/** Expected lab GOD table count (manifest sanity check). */
export const LAB_GOD_TABLE_COUNT = 217

export function installLabGodTables(tables: Record<string, LabGodTable>): void {
  labGodTables = tables
}

export function getLabGodTables(): Readonly<Record<string, LabGodTable>> {
  return labGodTables
}

export function getLabGodLabNames(): ReadonlySet<string> {
  return new Set(Object.keys(labGodTables))
}

/** Target level row (upgrade ending at `targetLevel`) from a GOD table, if present. */
export function labGodLevelEntry(
  labDisplayName: string,
  targetLevel: number,
): LabGodLevel | undefined {
  const table = labGodTables[labDisplayName]
  if (!table || !Number.isFinite(targetLevel) || targetLevel < 1) return undefined
  return table.levels.find((row) => row.level === targetLevel)
}
