/**
 * Authoritative lab ladder data from `tables/labs/` JSON.
 * Marginal coins and upgrade times for these labs override `tower-labs.json`.
 * Generated by scripts/sync-lab-god-tables.mjs — do not hand-edit imports or LAB_GOD_TABLES.
 */

import amplifyBotCooldown from '../../tables/labs/bots/amplify-bot-cooldown.json'
import amplifyBotDuration from '../../tables/labs/bots/amplify-bot-duration.json'
import areaOfEffectMastery from '../../tables/labs/card-mastery/area-of-effect-mastery.json'
import armorEffectBans from '../../tables/labs/modules/armor-effect-bans.json'
import armoredEnemies from '../../tables/labs/battle-condition/armored-enemies.json'
import assistModuleBonusArmor from '../../tables/labs/modules/assist-module-bonus-armor.json'
import assistModuleBonusCannon from '../../tables/labs/modules/assist-module-bonus-cannon.json'
import assistModuleBonusCore from '../../tables/labs/modules/assist-module-bonus-core.json'
import assistModuleBonusGenerator from '../../tables/labs/modules/assist-module-bonus-generator.json'
import assistModuleSubstatsArmor from '../../tables/labs/modules/assist-module-substats-armor.json'
import assistModuleSubstatsCannon from '../../tables/labs/modules/assist-module-substats-cannon.json'
import assistModuleSubstatsCore from '../../tables/labs/modules/assist-module-substats-core.json'
import assistModuleSubstatsGenerator from '../../tables/labs/modules/assist-module-substats-generator.json'
import attackSpeed from '../../tables/labs/attack/attack-speed.json'
import attackSpeedMastery from '../../tables/labs/card-mastery/attack-speed-mastery.json'
import autoPickPerks from '../../tables/labs/perks/auto-pick-perks.json'
import autoPickRanking from '../../tables/labs/perks/auto-pick-ranking.json'
import banPerks from '../../tables/labs/perks/ban-perks.json'
import basicsUltimate from '../../tables/labs/battle-condition/basics-ultimate.json'
import battleConditionReduction from '../../tables/labs/battle-condition/battle-condition-reduction.json'
import berserkerMastery from '../../tables/labs/card-mastery/berserker-mastery.json'
import blackHoleCoinBonus from '../../tables/labs/ultimate-weapon/black-hole-coin-bonus.json'
import blackHoleDamage from '../../tables/labs/ultimate-weapon/black-hole-damage.json'
import blackHoleDisableRangedEnemies from '../../tables/labs/ultimate-weapon/black-hole-disable-ranged-enemies.json'
import bossEnemyAttack from '../../tables/labs/enemies/boss-enemy-attack.json'
import bossHealth from '../../tables/labs/enemies/boss-health.json'
import bosssUltimate from '../../tables/labs/battle-condition/bosss-ultimate.json'
import botBotCooldown from '../../tables/labs/bots/bot-bot-cooldown.json'
import botBotDuration from '../../tables/labs/bots/bot-bot-duration.json'
import buyMultiplier from '../../tables/labs/main/buy-multiplier.json'
import cannonEffectBans from '../../tables/labs/modules/cannon-effect-bans.json'
import cardPresets from '../../tables/labs/main/card-presets.json'
import cashWave from '../../tables/labs/utility/cash-wave.json'
import cashBonus from '../../tables/labs/utility/cash-bonus.json'
import cashMastery from '../../tables/labs/card-mastery/cash-mastery.json'
import chainLightningShock from '../../tables/labs/ultimate-weapon/chain-lightning-shock.json'
import chainThunder from '../../tables/labs/ultimate-weapon/chain-thunder.json'
import chronoFieldDamageReduction from '../../tables/labs/ultimate-weapon/chrono-field-damage-reduction.json'
import chronoFieldDuration from '../../tables/labs/ultimate-weapon/chrono-field-duration.json'
import chronoFieldRange from '../../tables/labs/ultimate-weapon/chrono-field-range.json'
import chronoFieldReduction from '../../tables/labs/ultimate-weapon/chrono-field-reduction.json'
import coinsKillBonus from '../../tables/labs/utility/coins-kill-bonus.json'
import coinsWave from '../../tables/labs/utility/coins-wave.json'
import coinsMastery from '../../tables/labs/card-mastery/coins-mastery.json'
import commonDropChance from '../../tables/labs/modules/common-drop-chance.json'
import commonEnemyAttack from '../../tables/labs/enemies/common-enemy-attack.json'
import commonEnemyHealth from '../../tables/labs/enemies/common-enemy-health.json'
import coreEffectBans from '../../tables/labs/modules/core-effect-bans.json'
import criticalChanceMastery from '../../tables/labs/card-mastery/critical-chance-mastery.json'
import criticalCoinMastery from '../../tables/labs/card-mastery/critical-coin-mastery.json'
import criticalFactor from '../../tables/labs/attack/critical-factor.json'
import dailyMissionShards from '../../tables/labs/modules/daily-mission-shards.json'
import damage from '../../tables/labs/attack/damage.json'
import damagePerMeter from '../../tables/labs/attack/damage-per-meter.json'
import damageMastery from '../../tables/labs/card-mastery/damage-mastery.json'
import deathDefyDown from '../../tables/labs/battle-condition/death-defy-down.json'
import deathRayMastery from '../../tables/labs/card-mastery/death-ray-mastery.json'
import deathRayResistance from '../../tables/labs/battle-condition/death-ray-resistance.json'
import deathWaveArmorStripping from '../../tables/labs/ultimate-weapon/death-wave-armor-stripping.json'
import deathWaveCellsBonus from '../../tables/labs/ultimate-weapon/death-wave-cells-bonus.json'
import deathWaveCoinBonus from '../../tables/labs/ultimate-weapon/death-wave-coin-bonus.json'
import deathWaveDamageAmplifier from '../../tables/labs/ultimate-weapon/death-wave-damage-amplifier.json'
import deathWaveHealth from '../../tables/labs/ultimate-weapon/death-wave-health.json'
import defense from '../../tables/labs/defense/defense.json'
import defenseAbsolute from '../../tables/labs/defense/defense-absolute.json'
import demonModeMastery from '../../tables/labs/card-mastery/demon-mode-mastery.json'
import dissonantEchoAttack from '../../tables/labs/main/dissonant-echo-attack.json'
import dissonantEchoDefense from '../../tables/labs/main/dissonant-echo-defense.json'
import dissonantEchoUltimateWeapons from '../../tables/labs/main/dissonant-echo-ultimate-weapons.json'
import dissonantEchoUtility from '../../tables/labs/main/dissonant-echo-utility.json'
import doubleDeathRay from '../../tables/labs/cards/double-death-ray.json'
import enemyAttackLevelSkip from '../../tables/labs/utility/enemy-attack-level-skip.json'
import enemyAttackSpeed from '../../tables/labs/battle-condition/enemy-attack-speed.json'
import enemyBalanceMastery from '../../tables/labs/card-mastery/enemy-balance-mastery.json'
import enemyHealthLevelSkip from '../../tables/labs/utility/enemy-health-level-skip.json'
import enemyLevelSkipReduction from '../../tables/labs/battle-condition/enemy-level-skip-reduction.json'
import enemySpeed from '../../tables/labs/battle-condition/enemy-speed.json'
import energyNetMastery from '../../tables/labs/card-mastery/energy-net-mastery.json'
import energyShieldExtraHit from '../../tables/labs/cards/energy-shield-extra-hit.json'
import energyShieldMastery from '../../tables/labs/card-mastery/energy-shield-mastery.json'
import energyShieldsDown from '../../tables/labs/battle-condition/energy-shields-down.json'
import enhancementAttackCoinDiscount from '../../tables/labs/main/enhancement-attack-coin-discount.json'
import enhancementDefenseCoinDiscount from '../../tables/labs/main/enhancement-defense-coin-discount.json'
import enhancementUtilityCoinDiscount from '../../tables/labs/main/enhancement-utility-coin-discount.json'
import extraBlackHole from '../../tables/labs/ultimate-weapon/extra-black-hole.json'
import extraDefenseMastery from '../../tables/labs/card-mastery/extra-defense-mastery.json'
import extraExtraOrbs from '../../tables/labs/cards/extra-extra-orbs.json'
import extraOrbAdjuster from '../../tables/labs/cards/extra-orb-adjuster.json'
import extraOrbMastery from '../../tables/labs/card-mastery/extra-orb-mastery.json'
import fastEnemyAttack from '../../tables/labs/enemies/fast-enemy-attack.json'
import fastEnemyHealth from '../../tables/labs/enemies/fast-enemy-health.json'
import fastEnemySpeed from '../../tables/labs/enemies/fast-enemy-speed.json'
import fastsUltimate from '../../tables/labs/battle-condition/fasts-ultimate.json'
import firstPerkChoice from '../../tables/labs/perks/first-perk-choice.json'
import flameBotBurnStack from '../../tables/labs/bots/flame-bot-burn-stack.json'
import flameBotCooldown from '../../tables/labs/bots/flame-bot-cooldown.json'
import fortressMastery from '../../tables/labs/card-mastery/fortress-mastery.json'
import freeUpgradesMastery from '../../tables/labs/card-mastery/free-upgrades-mastery.json'
import gameSpeed from '../../tables/labs/main/game-speed.json'
import garlicThorns from '../../tables/labs/defense/garlic-thorns.json'
import generatorEffectBans from '../../tables/labs/modules/generator-effect-bans.json'
import goldenBotCooldown from '../../tables/labs/bots/golden-bot-cooldown.json'
import goldenBotDuration from '../../tables/labs/bots/golden-bot-duration.json'
import goldenTowerBonus from '../../tables/labs/ultimate-weapon/golden-tower-bonus.json'
import goldenTowerDuration from '../../tables/labs/ultimate-weapon/golden-tower-duration.json'
import health from '../../tables/labs/defense/health.json'
import healthMastery from '../../tables/labs/card-mastery/health-mastery.json'
import healthRegen from '../../tables/labs/defense/health-regen.json'
import healthRegenMastery from '../../tables/labs/card-mastery/health-regen-mastery.json'
import improveTradeOffPerks from '../../tables/labs/perks/improve-trade-off-perks.json'
import innerLandMineChronoJump from '../../tables/labs/ultimate-weapon/inner-land-mine-chrono-jump.json'
import innerMineBlastRadius from '../../tables/labs/ultimate-weapon/inner-mine-blast-radius.json'
import innerMineRotationSpeed from '../../tables/labs/ultimate-weapon/inner-mine-rotation-speed.json'
import innerMineStun from '../../tables/labs/ultimate-weapon/inner-mine-stun.json'
import interest from '../../tables/labs/utility/interest.json'
import introSprintMastery from '../../tables/labs/card-mastery/intro-sprint-mastery.json'
import knockbackResistance from '../../tables/labs/battle-condition/knockback-resistance.json'
import labsCoinDiscount from '../../tables/labs/main/labs-coin-discount.json'
import labsSpeed from '../../tables/labs/main/labs-speed.json'
import landMineDamage from '../../tables/labs/defense/land-mine-damage.json'
import landMineDecay from '../../tables/labs/defense/land-mine-decay.json'
import landMineStunMastery from '../../tables/labs/card-mastery/land-mine-stun-mastery.json'
import lightSpeedShots from '../../tables/labs/attack/light-speed-shots.json'
import lightningAmplifierScatter from '../../tables/labs/ultimate-weapon/lightning-amplifier-scatter.json'
import maxInterest from '../../tables/labs/utility/max-interest.json'
import maxRendArmorMultiplier from '../../tables/labs/attack/max-rend-armor-multiplier.json'
import missileAmplifier from '../../tables/labs/ultimate-weapon/missile-amplifier.json'
import missileBarrage from '../../tables/labs/ultimate-weapon/missile-barrage.json'
import missileBarrageQuantity from '../../tables/labs/ultimate-weapon/missile-barrage-quantity.json'
import missileDespawnTime from '../../tables/labs/ultimate-weapon/missile-despawn-time.json'
import missileRadius from '../../tables/labs/ultimate-weapon/missile-radius.json'
import missilesExplosion from '../../tables/labs/ultimate-weapon/missiles-explosion.json'
import moduleCoinCost from '../../tables/labs/modules/module-coin-cost.json'
import moduleShardsCost from '../../tables/labs/modules/module-shards-cost.json'
import moreEnemies from '../../tables/labs/battle-condition/more-enemies.json'
import moreRoundStats from '../../tables/labs/main/more-round-stats.json'
import nukeMastery from '../../tables/labs/card-mastery/nuke-mastery.json'
import orbBossHit from '../../tables/labs/defense/orb-boss-hit.json'
import orbResistance from '../../tables/labs/battle-condition/orb-resistance.json'
import orbsSpeed from '../../tables/labs/defense/orbs-speed.json'
import packageAfterBoss from '../../tables/labs/utility/package-after-boss.json'
import perkOptionQuantity from '../../tables/labs/perks/perk-option-quantity.json'
import plasmaCannonMastery from '../../tables/labs/card-mastery/plasma-cannon-mastery.json'
import plasmaCannonResistance from '../../tables/labs/battle-condition/plasma-cannon-resistance.json'
import protectorDamageReduction from '../../tables/labs/enemies/protector-damage-reduction.json'
import protectorHealth from '../../tables/labs/enemies/protector-health.json'
import protectorRadius from '../../tables/labs/enemies/protector-radius.json'
import protectorsUltimate from '../../tables/labs/battle-condition/protectors-ultimate.json'
import range from '../../tables/labs/attack/range.json'
import rangeMastery from '../../tables/labs/card-mastery/range-mastery.json'
import rangedEnemyAttack from '../../tables/labs/enemies/ranged-enemy-attack.json'
import rangedEnemyHealth from '../../tables/labs/enemies/ranged-enemy-health.json'
import rangedEnemyRange from '../../tables/labs/enemies/ranged-enemy-range.json'
import rangedUltimate from '../../tables/labs/battle-condition/ranged-ultimate.json'
import rareDropChance from '../../tables/labs/modules/rare-drop-chance.json'
import rayEnemyAttack from '../../tables/labs/enemies/ray-enemy-attack.json'
import rayEnemyHealth from '../../tables/labs/enemies/ray-enemy-health.json'
import rechargeDemonMode from '../../tables/labs/cards/recharge-demon-mode.json'
import rechargeMissileBarrage from '../../tables/labs/ultimate-weapon/recharge-missile-barrage.json'
import rechargeNuke from '../../tables/labs/cards/recharge-nuke.json'
import rechargeSecondWind from '../../tables/labs/cards/recharge-second-wind.json'
import recoveryPackageAmount from '../../tables/labs/utility/recovery-package-amount.json'
import recoveryPackageChance from '../../tables/labs/utility/recovery-package-chance.json'
import recoveryPackageChanceMastery from '../../tables/labs/card-mastery/recovery-package-chance-mastery.json'
import recoveryPackageMax from '../../tables/labs/utility/recovery-package-max.json'
import rerollDailyMission from '../../tables/labs/main/reroll-daily-mission.json'
import rerollShards from '../../tables/labs/modules/reroll-shards.json'
import scatterEnemyAttack from '../../tables/labs/enemies/scatter-enemy-attack.json'
import scatterEnemyHealth from '../../tables/labs/enemies/scatter-enemy-health.json'
import secondWindBlast from '../../tables/labs/cards/second-wind-blast.json'
import secondWindMastery from '../../tables/labs/card-mastery/second-wind-mastery.json'
import shatterShards from '../../tables/labs/modules/shatter-shards.json'
import shockChance from '../../tables/labs/ultimate-weapon/shock-chance.json'
import shockMultiplier from '../../tables/labs/ultimate-weapon/shock-multiplier.json'
import shockwaveSize from '../../tables/labs/defense/shockwave-size.json'
import slowAuraMastery from '../../tables/labs/card-mastery/slow-aura-mastery.json'
import spotlightCoinBonus from '../../tables/labs/ultimate-weapon/spotlight-coin-bonus.json'
import spotlightMissiles from '../../tables/labs/ultimate-weapon/spotlight-missiles.json'
import standardPerksBonus from '../../tables/labs/perks/standard-perks-bonus.json'
import startingCash from '../../tables/labs/main/starting-cash.json'
import superCritChance from '../../tables/labs/attack/super-crit-chance.json'
import superCritMult from '../../tables/labs/attack/super-crit-mult.json'
import superTowerBonus from '../../tables/labs/cards/super-tower-bonus.json'
import superTowerMastery from '../../tables/labs/card-mastery/super-tower-mastery.json'
import swampRadius from '../../tables/labs/ultimate-weapon/swamp-radius.json'
import swampRendAdditionalEnemies from '../../tables/labs/ultimate-weapon/swamp-rend-additional-enemies.json'
import swampRendBasicEnemies from '../../tables/labs/ultimate-weapon/swamp-rend-basic-enemies.json'
import swampStun from '../../tables/labs/ultimate-weapon/swamp-stun.json'
import swampStunChance from '../../tables/labs/ultimate-weapon/swamp-stun-chance.json'
import swampStunTime from '../../tables/labs/ultimate-weapon/swamp-stun-time.json'
import tankEnemyAttack from '../../tables/labs/enemies/tank-enemy-attack.json'
import tankEnemyHealth from '../../tables/labs/enemies/tank-enemy-health.json'
import tanksUltimate from '../../tables/labs/battle-condition/tanks-ultimate.json'
import targetPriority from '../../tables/labs/main/target-priority.json'
import thornsResistance from '../../tables/labs/battle-condition/thorns-resistance.json'
import thunderBotCooldown from '../../tables/labs/bots/thunder-bot-cooldown.json'
import thunderBotLingerTime from '../../tables/labs/bots/thunder-bot-linger-time.json'
import ultimateCritMastery from '../../tables/labs/card-mastery/ultimate-crit-mastery.json'
import ultimateWeaponDurations from '../../tables/labs/battle-condition/ultimate-weapon-durations.json'
import unlockPerks from '../../tables/labs/perks/unlock-perks.json'
import unmergeModule from '../../tables/labs/modules/unmerge-module.json'
import vampireEnemyAttack from '../../tables/labs/enemies/vampire-enemy-attack.json'
import vampireEnemyHealth from '../../tables/labs/enemies/vampire-enemy-health.json'
import wallFortification from '../../tables/labs/defense/wall-fortification.json'
import wallHealth from '../../tables/labs/defense/wall-health.json'
import wallInvincibility from '../../tables/labs/defense/wall-invincibility.json'
import wallRebuild from '../../tables/labs/defense/wall-rebuild.json'
import wallRegen from '../../tables/labs/defense/wall-regen.json'
import wallThorns from '../../tables/labs/defense/wall-thorns.json'
import waveAcceleratorMastery from '../../tables/labs/card-mastery/wave-accelerator-mastery.json'
import waveSkipMastery from '../../tables/labs/card-mastery/wave-skip-mastery.json'
import wavesRequired from '../../tables/labs/perks/waves-required.json'
import workshopAttackDiscount from '../../tables/labs/main/workshop-attack-discount.json'
import workshopDefenseDiscount from '../../tables/labs/main/workshop-defense-discount.json'
import workshopEnhancements from '../../tables/labs/main/workshop-enhancements.json'
import workshopRespec from '../../tables/labs/main/workshop-respec.json'
import workshopUtilityDiscount from '../../tables/labs/main/workshop-utility-discount.json'

export type LabGodTime = {
  display: string
  seconds: number
}

export type LabGodLevel = {
  level: number
  value: number
  time: LabGodTime
  gems: number
  coins: number
  totalTime: LabGodTime
  totalGems: number
  totalCoins: number
}

export type LabGodTable = {
  name: string
  maxLevel: number
  levels: LabGodLevel[]
}

export const LAB_GOD_TABLES: Record<string, LabGodTable> = {
  'Amplify Bot - Cooldown': amplifyBotCooldown as LabGodTable,
  'Amplify Bot - Duration': amplifyBotDuration as LabGodTable,
  'Area of Effect Mastery': areaOfEffectMastery as LabGodTable,
  'Armor Effect Bans': armorEffectBans as LabGodTable,
  'Armored Enemies': armoredEnemies as LabGodTable,
  'Assist Module Bonus - Armor': assistModuleBonusArmor as LabGodTable,
  'Assist Module Bonus - Cannon': assistModuleBonusCannon as LabGodTable,
  'Assist Module Bonus - Core': assistModuleBonusCore as LabGodTable,
  'Assist Module Bonus - Generator': assistModuleBonusGenerator as LabGodTable,
  'Assist Module Substats - Armor': assistModuleSubstatsArmor as LabGodTable,
  'Assist Module Substats - Cannon': assistModuleSubstatsCannon as LabGodTable,
  'Assist Module Substats - Core': assistModuleSubstatsCore as LabGodTable,
  'Assist Module Substats - Generator': assistModuleSubstatsGenerator as LabGodTable,
  'Attack Speed': attackSpeed as LabGodTable,
  'Attack Speed Mastery': attackSpeedMastery as LabGodTable,
  'Auto Pick Perks': autoPickPerks as LabGodTable,
  'Auto Pick Ranking': autoPickRanking as LabGodTable,
  'Ban Perks': banPerks as LabGodTable,
  "Basic's Ultimate": basicsUltimate as LabGodTable,
  'Battle Condition Reduction': battleConditionReduction as LabGodTable,
  'Berserker Mastery': berserkerMastery as LabGodTable,
  'Black Hole Coin Bonus': blackHoleCoinBonus as LabGodTable,
  'Black Hole Damage': blackHoleDamage as LabGodTable,
  'Black Hole Disable Ranged Enemies': blackHoleDisableRangedEnemies as LabGodTable,
  'Boss Attack': bossEnemyAttack as LabGodTable,
  'Boss Health': bossHealth as LabGodTable,
  "Boss's Ultimate": bosssUltimate as LabGodTable,
  'Bot Bot - Cooldown': botBotCooldown as LabGodTable,
  'Bot Bot - Duration': botBotDuration as LabGodTable,
  'Buy Multiplier': buyMultiplier as LabGodTable,
  'Cannon Effect Bans': cannonEffectBans as LabGodTable,
  'Card Presets': cardPresets as LabGodTable,
  'Cash / Wave': cashWave as LabGodTable,
  'Cash Bonus': cashBonus as LabGodTable,
  'Cash Mastery': cashMastery as LabGodTable,
  'Chain Lightning Shock': chainLightningShock as LabGodTable,
  'Chain Thunder': chainThunder as LabGodTable,
  'Chrono Field Damage Reduction': chronoFieldDamageReduction as LabGodTable,
  'Chrono Field Duration': chronoFieldDuration as LabGodTable,
  'Chrono Field Range': chronoFieldRange as LabGodTable,
  'Chrono Field Reduction %': chronoFieldReduction as LabGodTable,
  'Coins / Kill Bonus': coinsKillBonus as LabGodTable,
  'Coins / Wave': coinsWave as LabGodTable,
  'Coins Mastery': coinsMastery as LabGodTable,
  'Common Drop Chance': commonDropChance as LabGodTable,
  'Common Enemy Attack': commonEnemyAttack as LabGodTable,
  'Common Enemy Health': commonEnemyHealth as LabGodTable,
  'Core Effect Bans': coreEffectBans as LabGodTable,
  'Critical Chance Mastery': criticalChanceMastery as LabGodTable,
  'Critical Coin Mastery': criticalCoinMastery as LabGodTable,
  'Critical Factor': criticalFactor as LabGodTable,
  'Daily Mission Shards': dailyMissionShards as LabGodTable,
  'Damage': damage as LabGodTable,
  'Damage / Meter': damagePerMeter as LabGodTable,
  'Damage Mastery': damageMastery as LabGodTable,
  'Death Defy Down': deathDefyDown as LabGodTable,
  'Death Ray Mastery': deathRayMastery as LabGodTable,
  'Death Ray Resistance': deathRayResistance as LabGodTable,
  'Death Wave Armor Stripping': deathWaveArmorStripping as LabGodTable,
  'Death Wave Cells Bonus': deathWaveCellsBonus as LabGodTable,
  'Death Wave Coin Bonus': deathWaveCoinBonus as LabGodTable,
  'Death Wave Damage Amplifier': deathWaveDamageAmplifier as LabGodTable,
  'Death Wave Health': deathWaveHealth as LabGodTable,
  'Defense %': defense as LabGodTable,
  'Defense Absolute': defenseAbsolute as LabGodTable,
  'Demon Mode Mastery': demonModeMastery as LabGodTable,
  'Dissonant Echo - Attack': dissonantEchoAttack as LabGodTable,
  'Dissonant Echo - Defense': dissonantEchoDefense as LabGodTable,
  'Dissonant Echo - Ultimate Weapons': dissonantEchoUltimateWeapons as LabGodTable,
  'Dissonant Echo - Utility': dissonantEchoUtility as LabGodTable,
  'Double Death Ray': doubleDeathRay as LabGodTable,
  'Enemy Attack Level Skip': enemyAttackLevelSkip as LabGodTable,
  'Enemy Attack Speed': enemyAttackSpeed as LabGodTable,
  'Enemy Balance Mastery': enemyBalanceMastery as LabGodTable,
  'Enemy Health Level Skip': enemyHealthLevelSkip as LabGodTable,
  'Enemy Level Skip Reduction': enemyLevelSkipReduction as LabGodTable,
  'Enemy Speed': enemySpeed as LabGodTable,
  'Energy Net Mastery': energyNetMastery as LabGodTable,
  'Energy Shield Extra Hit': energyShieldExtraHit as LabGodTable,
  'Energy Shield Mastery': energyShieldMastery as LabGodTable,
  'Energy Shields Down': energyShieldsDown as LabGodTable,
  'Enhancement Attack - Coin Discount': enhancementAttackCoinDiscount as LabGodTable,
  'Enhancement Defense - Coin Discount': enhancementDefenseCoinDiscount as LabGodTable,
  'Enhancement Utility - Coin Discount': enhancementUtilityCoinDiscount as LabGodTable,
  'Extra Black Hole': extraBlackHole as LabGodTable,
  'Extra Defense Mastery': extraDefenseMastery as LabGodTable,
  'Extra Extra Orbs': extraExtraOrbs as LabGodTable,
  'Extra Orb Adjuster': extraOrbAdjuster as LabGodTable,
  'Extra Orb Mastery': extraOrbMastery as LabGodTable,
  'Fast Enemy Attack': fastEnemyAttack as LabGodTable,
  'Fast Enemy Health': fastEnemyHealth as LabGodTable,
  'Fast Enemy Speed': fastEnemySpeed as LabGodTable,
  "Fast's Ultimate": fastsUltimate as LabGodTable,
  'First Perk Choice': firstPerkChoice as LabGodTable,
  'Flame Bot - Burn Stack': flameBotBurnStack as LabGodTable,
  'Flame Bot - Cooldown': flameBotCooldown as LabGodTable,
  'Fortress Mastery': fortressMastery as LabGodTable,
  'Free Upgrades Mastery': freeUpgradesMastery as LabGodTable,
  'Game Speed': gameSpeed as LabGodTable,
  'Garlic Thorns': garlicThorns as LabGodTable,
  'Generator Effect Bans': generatorEffectBans as LabGodTable,
  'Golden Bot - Cooldown': goldenBotCooldown as LabGodTable,
  'Golden Bot - Duration': goldenBotDuration as LabGodTable,
  'Golden Tower Bonus': goldenTowerBonus as LabGodTable,
  'Golden Tower Duration': goldenTowerDuration as LabGodTable,
  'Health': health as LabGodTable,
  'Health Mastery': healthMastery as LabGodTable,
  'Health Regen': healthRegen as LabGodTable,
  'Health Regen Mastery': healthRegenMastery as LabGodTable,
  'Improve Trade-off Perks': improveTradeOffPerks as LabGodTable,
  'Inner Land Mine - Chrono Jump': innerLandMineChronoJump as LabGodTable,
  'Inner Mine Blast Radius': innerMineBlastRadius as LabGodTable,
  'Inner Mine Rotation Speed': innerMineRotationSpeed as LabGodTable,
  'Inner Mine Stun': innerMineStun as LabGodTable,
  'Interest': interest as LabGodTable,
  'Intro Sprint Mastery': introSprintMastery as LabGodTable,
  'Knockback Resistance': knockbackResistance as LabGodTable,
  'Labs Coin Discount': labsCoinDiscount as LabGodTable,
  'Labs Speed': labsSpeed as LabGodTable,
  'Land Mine Damage': landMineDamage as LabGodTable,
  'Land Mine Decay': landMineDecay as LabGodTable,
  'Land Mine Stun Mastery': landMineStunMastery as LabGodTable,
  'Light Speed Shots': lightSpeedShots as LabGodTable,
  'Lightning Amplifier - Scatter': lightningAmplifierScatter as LabGodTable,
  'Max Interest': maxInterest as LabGodTable,
  'Max Rend Armor Multiplier': maxRendArmorMultiplier as LabGodTable,
  'Missile Amplifier': missileAmplifier as LabGodTable,
  'Missile Barrage': missileBarrage as LabGodTable,
  'Missile Barrage Quantity': missileBarrageQuantity as LabGodTable,
  'Missile Despawn Time': missileDespawnTime as LabGodTable,
  'Missile Radius': missileRadius as LabGodTable,
  'Missiles Explosion': missilesExplosion as LabGodTable,
  'Module Coin Cost': moduleCoinCost as LabGodTable,
  'Module Shards Cost': moduleShardsCost as LabGodTable,
  'More Enemies': moreEnemies as LabGodTable,
  'More Round Stats': moreRoundStats as LabGodTable,
  'Nuke Mastery': nukeMastery as LabGodTable,
  'Orb Boss Hit': orbBossHit as LabGodTable,
  'Orb Resistance': orbResistance as LabGodTable,
  'Orbs Speed': orbsSpeed as LabGodTable,
  'Package After Boss': packageAfterBoss as LabGodTable,
  'Perk Option Quantity': perkOptionQuantity as LabGodTable,
  'Plasma Cannon Mastery': plasmaCannonMastery as LabGodTable,
  'Plasma Cannon Resistance': plasmaCannonResistance as LabGodTable,
  'Protector Damage Reduction': protectorDamageReduction as LabGodTable,
  'Protector Health': protectorHealth as LabGodTable,
  'Protector Radius': protectorRadius as LabGodTable,
  "Protector's Ultimate": protectorsUltimate as LabGodTable,
  'Range': range as LabGodTable,
  'Range Mastery': rangeMastery as LabGodTable,
  'Ranged Enemy Attack': rangedEnemyAttack as LabGodTable,
  'Ranged Enemy Health': rangedEnemyHealth as LabGodTable,
  'Ranged Enemy Range': rangedEnemyRange as LabGodTable,
  'Ranged Ultimate': rangedUltimate as LabGodTable,
  'Rare Drop Chance': rareDropChance as LabGodTable,
  'Ray Enemy Attack': rayEnemyAttack as LabGodTable,
  'Ray Enemy Health': rayEnemyHealth as LabGodTable,
  'Recharge Demon Mode': rechargeDemonMode as LabGodTable,
  'Recharge Missile Barrage': rechargeMissileBarrage as LabGodTable,
  'Recharge Nuke': rechargeNuke as LabGodTable,
  'Recharge Second Wind': rechargeSecondWind as LabGodTable,
  'Recovery Package Amount': recoveryPackageAmount as LabGodTable,
  'Recovery Package Chance': recoveryPackageChance as LabGodTable,
  'Recovery Package Chance Mastery': recoveryPackageChanceMastery as LabGodTable,
  'Recovery Package Max': recoveryPackageMax as LabGodTable,
  'Reroll Daily Mission': rerollDailyMission as LabGodTable,
  'Reroll Shards': rerollShards as LabGodTable,
  'Scatter Enemy Attack': scatterEnemyAttack as LabGodTable,
  'Scatter Enemy Health': scatterEnemyHealth as LabGodTable,
  'Second Wind Blast': secondWindBlast as LabGodTable,
  'Second Wind Mastery': secondWindMastery as LabGodTable,
  'Shatter Shards': shatterShards as LabGodTable,
  'Shock Chance': shockChance as LabGodTable,
  'Shock Multiplier': shockMultiplier as LabGodTable,
  'Shockwave Size': shockwaveSize as LabGodTable,
  'Slow Aura Mastery': slowAuraMastery as LabGodTable,
  'Spotlight Coin Bonus': spotlightCoinBonus as LabGodTable,
  'Spotlight Missiles': spotlightMissiles as LabGodTable,
  'Standard Perks Bonus': standardPerksBonus as LabGodTable,
  'Starting Cash': startingCash as LabGodTable,
  'Super Crit Chance': superCritChance as LabGodTable,
  'Super Crit Mult': superCritMult as LabGodTable,
  'Super Tower Bonus': superTowerBonus as LabGodTable,
  'Super Tower Mastery': superTowerMastery as LabGodTable,
  'Swamp Radius': swampRadius as LabGodTable,
  'Swamp Rend - Additional Enemies': swampRendAdditionalEnemies as LabGodTable,
  'Swamp Rend - Basic Enemies': swampRendBasicEnemies as LabGodTable,
  'Swamp Stun': swampStun as LabGodTable,
  'Swamp Stun Chance': swampStunChance as LabGodTable,
  'Swamp Stun Time': swampStunTime as LabGodTable,
  'Tank Enemy Attack': tankEnemyAttack as LabGodTable,
  'Tank Enemy Health': tankEnemyHealth as LabGodTable,
  "Tank's Ultimate": tanksUltimate as LabGodTable,
  'Target Priority': targetPriority as LabGodTable,
  'Thorns Resistance': thornsResistance as LabGodTable,
  'Thunder Bot - Cooldown': thunderBotCooldown as LabGodTable,
  'Thunder Bot - Linger Time': thunderBotLingerTime as LabGodTable,
  'Ultimate Crit Mastery': ultimateCritMastery as LabGodTable,
  'Ultimate Weapon Durations': ultimateWeaponDurations as LabGodTable,
  'Unlock Perks': unlockPerks as LabGodTable,
  'Unmerge Module': unmergeModule as LabGodTable,
  'Vampire Enemy Attack': vampireEnemyAttack as LabGodTable,
  'Vampire Enemy Health': vampireEnemyHealth as LabGodTable,
  'Wall Fortification': wallFortification as LabGodTable,
  'Wall Health': wallHealth as LabGodTable,
  'Wall Invincibility': wallInvincibility as LabGodTable,
  'Wall Rebuild': wallRebuild as LabGodTable,
  'Wall Regen': wallRegen as LabGodTable,
  'Wall Thorns': wallThorns as LabGodTable,
  'Wave Accelerator Mastery': waveAcceleratorMastery as LabGodTable,
  'Wave Skip Mastery': waveSkipMastery as LabGodTable,
  'Waves Required': wavesRequired as LabGodTable,
  'Workshop Attack Discount': workshopAttackDiscount as LabGodTable,
  'Workshop Defense Discount': workshopDefenseDiscount as LabGodTable,
  'Workshop Enhancements': workshopEnhancements as LabGodTable,
  'Workshop Respec': workshopRespec as LabGodTable,
  'Workshop Utility Discount': workshopUtilityDiscount as LabGodTable,
}

/** Research card display names with a GOD table in `tables/labs/`. */
export const LAB_GOD_LAB_NAMES: ReadonlySet<string> = new Set(
  Object.keys(LAB_GOD_TABLES),
)

/** Target level row (upgrade ending at `targetLevel`) from a GOD table, if present. */
export function labGodLevelEntry(
  labDisplayName: string,
  targetLevel: number,
): LabGodLevel | undefined {
  const table = LAB_GOD_TABLES[labDisplayName]
  if (!table || !Number.isFinite(targetLevel) || targetLevel < 1) return undefined
  return table.levels.find((row) => row.level === targetLevel)
}
