/** Wiki Basic Upgrades — generated by scripts/gen-workshop-ultimate-data.mjs */

import type { WorkshopUltimateTrack } from './workshopUltimateTable'

export type WorkshopUltimateWeaponId =
  | 'goldenTower'
  | 'blackHole'
  | 'spotlight'
  | 'deathWave'
  | 'chainLightning'
  | 'smartMissiles'
  | 'innerLandMines'
  | 'poisonSwamp'
  | 'chronoField'

export type WorkshopUltimateUpgradeKey =
  | 'goldenTowerBonusLevel'
  | 'goldenTowerDurationLevel'
  | 'goldenTowerCooldownLevel'
  | 'blackHoleSizeLevel'
  | 'blackHoleDurationLevel'
  | 'blackHoleCooldownLevel'
  | 'spotlightBonusLevel'
  | 'spotlightAngleLevel'
  | 'spotlightQuantityLevel'
  | 'deathWaveDamageLevel'
  | 'deathWaveQuantityLevel'
  | 'deathWaveCooldownLevel'
  | 'chainLightningDamageLevel'
  | 'chainLightningQuantityLevel'
  | 'chainLightningChanceLevel'
  | 'smartMissilesDamageLevel'
  | 'smartMissilesQuantityLevel'
  | 'smartMissilesCooldownLevel'
  | 'innerLandMinesDamageLevel'
  | 'innerLandMinesQuantityLevel'
  | 'innerLandMinesCooldownLevel'
  | 'poisonSwampDamageLevel'
  | 'poisonSwampDurationLevel'
  | 'poisonSwampCooldownLevel'
  | 'chronoFieldDurationLevel'
  | 'chronoFieldSlowLevel'
  | 'chronoFieldCooldownLevel'

/** In-game DevPanel order (`ultimateWeapon*` save array indices 0…8). */
export const WORKSHOP_ULTIMATE_WEAPON_ORDER: readonly WorkshopUltimateWeaponId[] = [
  'chainLightning',
  'smartMissiles',
  'deathWave',
  'chronoField',
  'innerLandMines',
  'goldenTower',
  'poisonSwamp',
  'blackHole',
  'spotlight',
]

export const WORKSHOP_ULTIMATE_UPGRADE_ORDER: readonly WorkshopUltimateUpgradeKey[] = [
  'chainLightningDamageLevel',
  'chainLightningQuantityLevel',
  'chainLightningChanceLevel',
  'smartMissilesDamageLevel',
  'smartMissilesQuantityLevel',
  'smartMissilesCooldownLevel',
  'deathWaveDamageLevel',
  'deathWaveQuantityLevel',
  'deathWaveCooldownLevel',
  'chronoFieldDurationLevel',
  'chronoFieldSlowLevel',
  'chronoFieldCooldownLevel',
  'innerLandMinesDamageLevel',
  'innerLandMinesQuantityLevel',
  'innerLandMinesCooldownLevel',
  'goldenTowerBonusLevel',
  'goldenTowerDurationLevel',
  'goldenTowerCooldownLevel',
  'poisonSwampDamageLevel',
  'poisonSwampDurationLevel',
  'poisonSwampCooldownLevel',
  'blackHoleSizeLevel',
  'blackHoleDurationLevel',
  'blackHoleCooldownLevel',
  'spotlightBonusLevel',
  'spotlightAngleLevel',
  'spotlightQuantityLevel',
]

export const WORKSHOP_ULTIMATE_WEAPON_STATS: Record<
  WorkshopUltimateWeaponId,
  readonly { key: WorkshopUltimateUpgradeKey; stat: string }[]
> = {
  goldenTower: [
    { key: 'goldenTowerBonusLevel', stat: 'bonus' },
    { key: 'goldenTowerDurationLevel', stat: 'duration' },
    { key: 'goldenTowerCooldownLevel', stat: 'cooldown' },
  ],
  blackHole: [
    { key: 'blackHoleSizeLevel', stat: 'size' },
    { key: 'blackHoleDurationLevel', stat: 'duration' },
    { key: 'blackHoleCooldownLevel', stat: 'cooldown' },
  ],
  spotlight: [
    { key: 'spotlightBonusLevel', stat: 'bonus' },
    { key: 'spotlightAngleLevel', stat: 'angle' },
    { key: 'spotlightQuantityLevel', stat: 'quantity' },
  ],
  deathWave: [
    { key: 'deathWaveDamageLevel', stat: 'damage' },
    { key: 'deathWaveQuantityLevel', stat: 'quantity' },
    { key: 'deathWaveCooldownLevel', stat: 'cooldown' },
  ],
  chainLightning: [
    { key: 'chainLightningDamageLevel', stat: 'damage' },
    { key: 'chainLightningQuantityLevel', stat: 'quantity' },
    { key: 'chainLightningChanceLevel', stat: 'chance' },
  ],
  smartMissiles: [
    { key: 'smartMissilesDamageLevel', stat: 'damage' },
    { key: 'smartMissilesQuantityLevel', stat: 'quantity' },
    { key: 'smartMissilesCooldownLevel', stat: 'cooldown' },
  ],
  innerLandMines: [
    { key: 'innerLandMinesDamageLevel', stat: 'damage' },
    { key: 'innerLandMinesQuantityLevel', stat: 'quantity' },
    { key: 'innerLandMinesCooldownLevel', stat: 'cooldown' },
  ],
  poisonSwamp: [
    { key: 'poisonSwampDamageLevel', stat: 'damage' },
    { key: 'poisonSwampDurationLevel', stat: 'duration' },
    { key: 'poisonSwampCooldownLevel', stat: 'cooldown' },
  ],
  chronoField: [
    { key: 'chronoFieldDurationLevel', stat: 'duration' },
    { key: 'chronoFieldSlowLevel', stat: 'slow' },
    { key: 'chronoFieldCooldownLevel', stat: 'cooldown' },
  ],
}

export const WORKSHOP_ULTIMATE_TRACKS: Record<WorkshopUltimateUpgradeKey, WorkshopUltimateTrack> = {
  goldenTowerBonusLevel: {
  valueKind: "mult",
  milestones: [
    {
      value: 5,
      marginalStones: 0
    },
    {
      value: 5.8,
      marginalStones: 5
    },
    {
      value: 6.6,
      marginalStones: 13
    },
    {
      value: 7.4,
      marginalStones: 22
    },
    {
      value: 8.2,
      marginalStones: 32
    },
    {
      value: 9,
      marginalStones: 43
    },
    {
      value: 9.8,
      marginalStones: 55
    },
    {
      value: 10.6,
      marginalStones: 68
    },
    {
      value: 11.4,
      marginalStones: 82
    },
    {
      value: 12.2,
      marginalStones: 98
    },
    {
      value: 13,
      marginalStones: 116
    },
    {
      value: 13.8,
      marginalStones: 138
    },
    {
      value: 14.6,
      marginalStones: 162
    },
    {
      value: 15.4,
      marginalStones: 250
    },
    {
      value: 16.2,
      marginalStones: 350
    },
    {
      value: 17,
      marginalStones: 500
    },
    {
      value: 17.8,
      marginalStones: 700
    },
    {
      value: 18.6,
      marginalStones: 950
    },
    {
      value: 19.4,
      marginalStones: 1250
    },
    {
      value: 20.2,
      marginalStones: 1600
    },
    {
      value: 21,
      marginalStones: 2000
    }
  ]
},
  goldenTowerDurationLevel: {
  valueKind: "seconds",
  milestones: [
    {
      value: 15,
      marginalStones: 0
    },
    {
      value: 16,
      marginalStones: 5
    },
    {
      value: 17,
      marginalStones: 14
    },
    {
      value: 18,
      marginalStones: 23
    },
    {
      value: 19,
      marginalStones: 32
    },
    {
      value: 20,
      marginalStones: 41
    },
    {
      value: 21,
      marginalStones: 50
    },
    {
      value: 22,
      marginalStones: 59
    },
    {
      value: 23,
      marginalStones: 68
    },
    {
      value: 24,
      marginalStones: 77
    },
    {
      value: 25,
      marginalStones: 87
    },
    {
      value: 26,
      marginalStones: 98
    },
    {
      value: 27,
      marginalStones: 110
    },
    {
      value: 28,
      marginalStones: 123
    },
    {
      value: 29,
      marginalStones: 137
    },
    {
      value: 30,
      marginalStones: 152
    },
    {
      value: 31,
      marginalStones: 168
    },
    {
      value: 32,
      marginalStones: 185
    },
    {
      value: 33,
      marginalStones: 203
    },
    {
      value: 34,
      marginalStones: 222
    },
    {
      value: 35,
      marginalStones: 242
    },
    {
      value: 36,
      marginalStones: 263
    },
    {
      value: 37,
      marginalStones: 285
    },
    {
      value: 38,
      marginalStones: 308
    },
    {
      value: 39,
      marginalStones: 332
    },
    {
      value: 40,
      marginalStones: 356
    },
    {
      value: 41,
      marginalStones: 380
    },
    {
      value: 42,
      marginalStones: 404
    },
    {
      value: 43,
      marginalStones: 428
    },
    {
      value: 44,
      marginalStones: 452
    },
    {
      value: 45,
      marginalStones: 476
    },
    {
      value: 46,
      marginalStones: 530
    },
    {
      value: 47,
      marginalStones: 614
    },
    {
      value: 48,
      marginalStones: 728
    },
    {
      value: 49,
      marginalStones: 872
    },
    {
      value: 50,
      marginalStones: 1046
    },
    {
      value: 51,
      marginalStones: 1250
    },
    {
      value: 52,
      marginalStones: 1484
    },
    {
      value: 53,
      marginalStones: 1748
    }
  ]
},
  goldenTowerCooldownLevel: {
  valueKind: "seconds",
  milestones: [
    {
      value: 300,
      marginalStones: 0
    },
    {
      value: 290,
      marginalStones: 10
    },
    {
      value: 280,
      marginalStones: 28
    },
    {
      value: 270,
      marginalStones: 46
    },
    {
      value: 260,
      marginalStones: 64
    },
    {
      value: 250,
      marginalStones: 82
    },
    {
      value: 240,
      marginalStones: 100
    },
    {
      value: 230,
      marginalStones: 118
    },
    {
      value: 220,
      marginalStones: 136
    },
    {
      value: 210,
      marginalStones: 154
    },
    {
      value: 200,
      marginalStones: 172
    },
    {
      value: 190,
      marginalStones: 190
    },
    {
      value: 180,
      marginalStones: 208
    },
    {
      value: 170,
      marginalStones: 226
    },
    {
      value: 160,
      marginalStones: 244
    },
    {
      value: 150,
      marginalStones: 262
    },
    {
      value: 140,
      marginalStones: 300
    },
    {
      value: 130,
      marginalStones: 368
    },
    {
      value: 120,
      marginalStones: 476
    },
    {
      value: 110,
      marginalStones: 644
    },
    {
      value: 100,
      marginalStones: 872
    }
  ]
},
  blackHoleSizeLevel: {
  valueKind: "meters",
  milestones: [
    {
      value: 30,
      marginalStones: 0
    },
    {
      value: 32,
      marginalStones: 5
    },
    {
      value: 34,
      marginalStones: 12
    },
    {
      value: 36,
      marginalStones: 19
    },
    {
      value: 38,
      marginalStones: 26
    },
    {
      value: 40,
      marginalStones: 34
    },
    {
      value: 42,
      marginalStones: 43
    },
    {
      value: 44,
      marginalStones: 53
    },
    {
      value: 46,
      marginalStones: 64
    },
    {
      value: 48,
      marginalStones: 76
    },
    {
      value: 50,
      marginalStones: 89
    },
    {
      value: 52,
      marginalStones: 103
    },
    {
      value: 54,
      marginalStones: 118
    },
    {
      value: 56,
      marginalStones: 134
    },
    {
      value: 58,
      marginalStones: 151
    },
    {
      value: 60,
      marginalStones: 169
    },
    {
      value: 62,
      marginalStones: 189
    },
    {
      value: 64,
      marginalStones: 211
    },
    {
      value: 66,
      marginalStones: 236
    },
    {
      value: 68,
      marginalStones: 264
    },
    {
      value: 70,
      marginalStones: 295
    }
  ]
},
  blackHoleDurationLevel: {
  valueKind: "seconds",
  milestones: [
    {
      value: 15,
      marginalStones: 0
    },
    {
      value: 16,
      marginalStones: 5
    },
    {
      value: 17,
      marginalStones: 14
    },
    {
      value: 18,
      marginalStones: 23
    },
    {
      value: 19,
      marginalStones: 32
    },
    {
      value: 20,
      marginalStones: 41
    },
    {
      value: 21,
      marginalStones: 50
    },
    {
      value: 22,
      marginalStones: 59
    },
    {
      value: 23,
      marginalStones: 68
    },
    {
      value: 24,
      marginalStones: 77
    },
    {
      value: 25,
      marginalStones: 86
    },
    {
      value: 26,
      marginalStones: 95
    },
    {
      value: 27,
      marginalStones: 104
    },
    {
      value: 28,
      marginalStones: 113
    },
    {
      value: 29,
      marginalStones: 122
    },
    {
      value: 30,
      marginalStones: 131
    },
    {
      value: 31,
      marginalStones: 165
    },
    {
      value: 32,
      marginalStones: 224
    },
    {
      value: 33,
      marginalStones: 308
    },
    {
      value: 34,
      marginalStones: 417
    },
    {
      value: 35,
      marginalStones: 551
    },
    {
      value: 36,
      marginalStones: 710
    },
    {
      value: 37,
      marginalStones: 894
    },
    {
      value: 38,
      marginalStones: 1103
    }
  ]
},
  blackHoleCooldownLevel: {
  valueKind: "seconds",
  milestones: [
    {
      value: 200,
      marginalStones: 0
    },
    {
      value: 190,
      marginalStones: 10
    },
    {
      value: 180,
      marginalStones: 28
    },
    {
      value: 170,
      marginalStones: 46
    },
    {
      value: 160,
      marginalStones: 64
    },
    {
      value: 150,
      marginalStones: 82
    },
    {
      value: 140,
      marginalStones: 100
    },
    {
      value: 130,
      marginalStones: 118
    },
    {
      value: 120,
      marginalStones: 136
    },
    {
      value: 110,
      marginalStones: 154
    },
    {
      value: 100,
      marginalStones: 172
    },
    {
      value: 90,
      marginalStones: 190
    },
    {
      value: 80,
      marginalStones: 208
    },
    {
      value: 70,
      marginalStones: 226
    },
    {
      value: 60,
      marginalStones: 244
    },
    {
      value: 50,
      marginalStones: 262
    }
  ]
},
  spotlightBonusLevel: {
  valueKind: "mult",
  milestones: [
    {
      value: 8,
      marginalStones: 0
    },
    {
      value: 9.4,
      marginalStones: 5
    },
    {
      value: 10.8,
      marginalStones: 13
    },
    {
      value: 12.2,
      marginalStones: 21
    },
    {
      value: 13.6,
      marginalStones: 30
    },
    {
      value: 15,
      marginalStones: 40
    },
    {
      value: 16.4,
      marginalStones: 52
    },
    {
      value: 17.8,
      marginalStones: 65
    },
    {
      value: 19.2,
      marginalStones: 80
    },
    {
      value: 20.6,
      marginalStones: 95
    },
    {
      value: 22,
      marginalStones: 112
    },
    {
      value: 23.4,
      marginalStones: 133
    },
    {
      value: 24.8,
      marginalStones: 150
    },
    {
      value: 26.2,
      marginalStones: 180
    },
    {
      value: 27.6,
      marginalStones: 220
    },
    {
      value: 29,
      marginalStones: 280
    },
    {
      value: 30.4,
      marginalStones: 320
    },
    {
      value: 31.8,
      marginalStones: 360
    },
    {
      value: 33.2,
      marginalStones: 420
    },
    {
      value: 34.6,
      marginalStones: 500
    },
    {
      value: 36,
      marginalStones: 600
    },
    {
      value: 37.4,
      marginalStones: 720
    },
    {
      value: 38.8,
      marginalStones: 850
    },
    {
      value: 40.2,
      marginalStones: 1000
    },
    {
      value: 41.6,
      marginalStones: 1175
    },
    {
      value: 43,
      marginalStones: 1400
    }
  ]
},
  spotlightAngleLevel: {
  valueKind: "angle",
  milestones: [
    {
      value: 30,
      marginalStones: 0
    },
    {
      value: 31,
      marginalStones: 5
    },
    {
      value: 32,
      marginalStones: 16
    },
    {
      value: 33,
      marginalStones: 27
    },
    {
      value: 34,
      marginalStones: 38
    },
    {
      value: 35,
      marginalStones: 49
    },
    {
      value: 36,
      marginalStones: 60
    },
    {
      value: 37,
      marginalStones: 71
    },
    {
      value: 38,
      marginalStones: 82
    },
    {
      value: 39,
      marginalStones: 93
    },
    {
      value: 40,
      marginalStones: 104
    },
    {
      value: 41,
      marginalStones: 115
    },
    {
      value: 42,
      marginalStones: 126
    },
    {
      value: 43,
      marginalStones: 137
    },
    {
      value: 44,
      marginalStones: 148
    },
    {
      value: 45,
      marginalStones: 159
    },
    {
      value: 46,
      marginalStones: 170
    },
    {
      value: 47,
      marginalStones: 181
    },
    {
      value: 48,
      marginalStones: 192
    },
    {
      value: 49,
      marginalStones: 203
    },
    {
      value: 50,
      marginalStones: 214
    },
    {
      value: 51,
      marginalStones: 225
    },
    {
      value: 52,
      marginalStones: 236
    },
    {
      value: 53,
      marginalStones: 247
    },
    {
      value: 54,
      marginalStones: 258
    },
    {
      value: 55,
      marginalStones: 269
    },
    {
      value: 56,
      marginalStones: 280
    },
    {
      value: 57,
      marginalStones: 291
    },
    {
      value: 58,
      marginalStones: 302
    },
    {
      value: 59,
      marginalStones: 313
    },
    {
      value: 60,
      marginalStones: 324
    },
    {
      value: 61,
      marginalStones: 337
    },
    {
      value: 62,
      marginalStones: 352
    },
    {
      value: 63,
      marginalStones: 369
    },
    {
      value: 64,
      marginalStones: 388
    },
    {
      value: 65,
      marginalStones: 409
    },
    {
      value: 66,
      marginalStones: 432
    },
    {
      value: 67,
      marginalStones: 457
    },
    {
      value: 68,
      marginalStones: 484
    },
    {
      value: 69,
      marginalStones: 513
    },
    {
      value: 70,
      marginalStones: 544
    },
    {
      value: 71,
      marginalStones: 577
    },
    {
      value: 72,
      marginalStones: 612
    },
    {
      value: 73,
      marginalStones: 649
    },
    {
      value: 74,
      marginalStones: 688
    },
    {
      value: 75,
      marginalStones: 729
    },
    {
      value: 76,
      marginalStones: 772
    },
    {
      value: 77,
      marginalStones: 817
    },
    {
      value: 78,
      marginalStones: 864
    },
    {
      value: 79,
      marginalStones: 913
    },
    {
      value: 80,
      marginalStones: 964
    },
    {
      value: 81,
      marginalStones: 1017
    },
    {
      value: 82,
      marginalStones: 1072
    },
    {
      value: 83,
      marginalStones: 1129
    },
    {
      value: 84,
      marginalStones: 1188
    },
    {
      value: 85,
      marginalStones: 1249
    },
    {
      value: 86,
      marginalStones: 1312
    },
    {
      value: 87,
      marginalStones: 1377
    },
    {
      value: 88,
      marginalStones: 1444
    },
    {
      value: 89,
      marginalStones: 1513
    },
    {
      value: 90,
      marginalStones: 1584
    }
  ]
},
  spotlightQuantityLevel: {
  valueKind: "count",
  milestones: [
    {
      value: 1,
      marginalStones: 0
    },
    {
      value: 2,
      marginalStones: 375
    },
    {
      value: 3,
      marginalStones: 850
    },
    {
      value: 4,
      marginalStones: 2500
    }
  ]
},
  deathWaveDamageLevel: {
  valueKind: "mult",
  milestones: [
    {
      value: 2,
      marginalStones: 0
    },
    {
      value: 3,
      marginalStones: 5
    },
    {
      value: 5,
      marginalStones: 11
    },
    {
      value: 9,
      marginalStones: 17
    },
    {
      value: 14,
      marginalStones: 23
    },
    {
      value: 22,
      marginalStones: 29
    },
    {
      value: 32,
      marginalStones: 35
    },
    {
      value: 46,
      marginalStones: 41
    },
    {
      value: 63,
      marginalStones: 47
    },
    {
      value: 85,
      marginalStones: 53
    },
    {
      value: 113,
      marginalStones: 61
    },
    {
      value: 148,
      marginalStones: 71
    },
    {
      value: 191,
      marginalStones: 84
    },
    {
      value: 244,
      marginalStones: 100
    },
    {
      value: 309,
      marginalStones: 120
    },
    {
      value: 387,
      marginalStones: 144
    },
    {
      value: 482,
      marginalStones: 174
    },
    {
      value: 596,
      marginalStones: 210
    },
    {
      value: 723,
      marginalStones: 254
    },
    {
      value: 877,
      marginalStones: 308
    },
    {
      value: 1064,
      marginalStones: 374
    },
    {
      value: 1290,
      marginalStones: 452
    },
    {
      value: 1569,
      marginalStones: 558
    },
    {
      value: 1916,
      marginalStones: 694
    },
    {
      value: 2356,
      marginalStones: 880
    },
    {
      value: 2919,
      marginalStones: 1126
    },
    {
      value: 3637,
      marginalStones: 1432
    },
    {
      value: 4544,
      marginalStones: 1813
    },
    {
      value: 5678,
      marginalStones: 2269
    },
    {
      value: 7078,
      marginalStones: 2800
    },
    {
      value: 9119,
      marginalStones: 3406
    }
  ]
},
  deathWaveQuantityLevel: {
  valueKind: "count",
  milestones: [
    {
      value: 1,
      marginalStones: 0
    },
    {
      value: 2,
      marginalStones: 200
    },
    {
      value: 3,
      marginalStones: 500
    },
    {
      value: 4,
      marginalStones: 850
    },
    {
      value: 5,
      marginalStones: 1400
    }
  ]
},
  deathWaveCooldownLevel: {
  valueKind: "seconds",
  milestones: [
    {
      value: 300,
      marginalStones: 0
    },
    {
      value: 290,
      marginalStones: 8
    },
    {
      value: 280,
      marginalStones: 24
    },
    {
      value: 270,
      marginalStones: 40
    },
    {
      value: 260,
      marginalStones: 56
    },
    {
      value: 250,
      marginalStones: 72
    },
    {
      value: 240,
      marginalStones: 88
    },
    {
      value: 230,
      marginalStones: 104
    },
    {
      value: 220,
      marginalStones: 120
    },
    {
      value: 210,
      marginalStones: 136
    },
    {
      value: 200,
      marginalStones: 152
    },
    {
      value: 190,
      marginalStones: 168
    },
    {
      value: 180,
      marginalStones: 184
    },
    {
      value: 170,
      marginalStones: 200
    },
    {
      value: 160,
      marginalStones: 216
    },
    {
      value: 150,
      marginalStones: 232
    },
    {
      value: 140,
      marginalStones: 248
    },
    {
      value: 130,
      marginalStones: 264
    },
    {
      value: 120,
      marginalStones: 280
    },
    {
      value: 110,
      marginalStones: 346
    },
    {
      value: 100,
      marginalStones: 512
    },
    {
      value: 90,
      marginalStones: 688
    },
    {
      value: 80,
      marginalStones: 874
    },
    {
      value: 70,
      marginalStones: 1070
    },
    {
      value: 60,
      marginalStones: 1276
    },
    {
      value: 50,
      marginalStones: 1492
    }
  ]
},
  chainLightningDamageLevel: {
  valueKind: "mult",
  milestones: [
    {
      value: 2,
      marginalStones: 0
    },
    {
      value: 3,
      marginalStones: 5
    },
    {
      value: 5,
      marginalStones: 11
    },
    {
      value: 9,
      marginalStones: 17
    },
    {
      value: 14,
      marginalStones: 23
    },
    {
      value: 22,
      marginalStones: 29
    },
    {
      value: 32,
      marginalStones: 35
    },
    {
      value: 46,
      marginalStones: 41
    },
    {
      value: 63,
      marginalStones: 47
    },
    {
      value: 85,
      marginalStones: 53
    },
    {
      value: 113,
      marginalStones: 61
    },
    {
      value: 148,
      marginalStones: 71
    },
    {
      value: 191,
      marginalStones: 84
    },
    {
      value: 244,
      marginalStones: 100
    },
    {
      value: 309,
      marginalStones: 120
    },
    {
      value: 387,
      marginalStones: 144
    },
    {
      value: 482,
      marginalStones: 174
    },
    {
      value: 596,
      marginalStones: 210
    },
    {
      value: 733,
      marginalStones: 252
    },
    {
      value: 898,
      marginalStones: 302
    },
    {
      value: 1094,
      marginalStones: 362
    },
    {
      value: 1328,
      marginalStones: 434
    },
    {
      value: 1607,
      marginalStones: 525
    },
    {
      value: 1937,
      marginalStones: 636
    },
    {
      value: 2329,
      marginalStones: 767
    },
    {
      value: 2794,
      marginalStones: 923
    },
    {
      value: 3342,
      marginalStones: 1109
    },
    {
      value: 3990,
      marginalStones: 1295
    },
    {
      value: 4755,
      marginalStones: 1521
    },
    {
      value: 5655,
      marginalStones: 1787
    },
    {
      value: 6715,
      marginalStones: 2103
    },
    {
      value: 7961,
      marginalStones: 2469
    }
  ]
},
  chainLightningQuantityLevel: {
  valueKind: "count",
  milestones: [
    {
      value: 1,
      marginalStones: 0
    },
    {
      value: 2,
      marginalStones: 30
    },
    {
      value: 3,
      marginalStones: 75
    },
    {
      value: 4,
      marginalStones: 150
    },
    {
      value: 5,
      marginalStones: 400
    }
  ]
},
  chainLightningChanceLevel: {
  valueKind: "percent",
  milestones: [
    {
      value: 5,
      marginalStones: 0
    },
    {
      value: 6.5,
      marginalStones: 8
    },
    {
      value: 8,
      marginalStones: 26
    },
    {
      value: 9.5,
      marginalStones: 44
    },
    {
      value: 11,
      marginalStones: 62
    },
    {
      value: 12.5,
      marginalStones: 80
    },
    {
      value: 14,
      marginalStones: 98
    },
    {
      value: 15.5,
      marginalStones: 116
    },
    {
      value: 17,
      marginalStones: 134
    },
    {
      value: 18.5,
      marginalStones: 152
    },
    {
      value: 20,
      marginalStones: 170
    },
    {
      value: 21.5,
      marginalStones: 188
    },
    {
      value: 23,
      marginalStones: 206
    },
    {
      value: 24.5,
      marginalStones: 224
    },
    {
      value: 26,
      marginalStones: 242
    },
    {
      value: 27.5,
      marginalStones: 260
    }
  ]
},
  smartMissilesDamageLevel: {
  valueKind: "mult",
  milestones: [
    {
      value: 10,
      marginalStones: 0
    },
    {
      value: 11,
      marginalStones: 5
    },
    {
      value: 13,
      marginalStones: 11
    },
    {
      value: 16,
      marginalStones: 17
    },
    {
      value: 20,
      marginalStones: 23
    },
    {
      value: 26,
      marginalStones: 29
    },
    {
      value: 34,
      marginalStones: 35
    },
    {
      value: 43,
      marginalStones: 41
    },
    {
      value: 55,
      marginalStones: 47
    },
    {
      value: 69,
      marginalStones: 53
    },
    {
      value: 87,
      marginalStones: 61
    },
    {
      value: 108,
      marginalStones: 71
    },
    {
      value: 134,
      marginalStones: 84
    },
    {
      value: 164,
      marginalStones: 100
    },
    {
      value: 200,
      marginalStones: 120
    },
    {
      value: 243,
      marginalStones: 144
    },
    {
      value: 293,
      marginalStones: 174
    },
    {
      value: 352,
      marginalStones: 210
    },
    {
      value: 421,
      marginalStones: 252
    },
    {
      value: 502,
      marginalStones: 302
    },
    {
      value: 597,
      marginalStones: 362
    },
    {
      value: 708,
      marginalStones: 432
    },
    {
      value: 838,
      marginalStones: 528
    },
    {
      value: 989,
      marginalStones: 654
    },
    {
      value: 1165,
      marginalStones: 810
    },
    {
      value: 1370,
      marginalStones: 996
    },
    {
      value: 1608,
      marginalStones: 1222
    },
    {
      value: 1886,
      marginalStones: 1488
    },
    {
      value: 2209,
      marginalStones: 1804
    },
    {
      value: 2585,
      marginalStones: 2180
    },
    {
      value: 3021,
      marginalStones: 2636
    }
  ]
},
  smartMissilesQuantityLevel: {
  valueKind: "count",
  milestones: [
    {
      value: 5,
      marginalStones: 0
    },
    {
      value: 6,
      marginalStones: 4
    },
    {
      value: 7,
      marginalStones: 12
    },
    {
      value: 8,
      marginalStones: 35
    },
    {
      value: 9,
      marginalStones: 70
    },
    {
      value: 10,
      marginalStones: 120
    },
    {
      value: 11,
      marginalStones: 180
    },
    {
      value: 12,
      marginalStones: 275
    },
    {
      value: 13,
      marginalStones: 350
    },
    {
      value: 14,
      marginalStones: 420
    },
    {
      value: 15,
      marginalStones: 500
    },
    {
      value: 16,
      marginalStones: 600
    },
    {
      value: 17,
      marginalStones: 750
    },
    {
      value: 18,
      marginalStones: 950
    },
    {
      value: 19,
      marginalStones: 1200
    },
    {
      value: 20,
      marginalStones: 1500
    }
  ]
},
  smartMissilesCooldownLevel: {
  valueKind: "seconds",
  milestones: [
    {
      value: 180,
      marginalStones: 0
    },
    {
      value: 170,
      marginalStones: 8
    },
    {
      value: 160,
      marginalStones: 24
    },
    {
      value: 150,
      marginalStones: 40
    },
    {
      value: 140,
      marginalStones: 56
    },
    {
      value: 130,
      marginalStones: 72
    },
    {
      value: 120,
      marginalStones: 88
    },
    {
      value: 110,
      marginalStones: 104
    },
    {
      value: 100,
      marginalStones: 120
    },
    {
      value: 90,
      marginalStones: 136
    },
    {
      value: 80,
      marginalStones: 152
    },
    {
      value: 70,
      marginalStones: 168
    },
    {
      value: 60,
      marginalStones: 184
    },
    {
      value: 50,
      marginalStones: 200
    },
    {
      value: 40,
      marginalStones: 216
    },
    {
      value: 30,
      marginalStones: 232
    },
    {
      value: 20,
      marginalStones: 750
    }
  ]
},
  innerLandMinesDamageLevel: {
  valueKind: "mult",
  milestones: [
    {
      value: 10,
      marginalStones: 0
    },
    {
      value: 11,
      marginalStones: 5
    },
    {
      value: 13,
      marginalStones: 11
    },
    {
      value: 16,
      marginalStones: 17
    },
    {
      value: 20,
      marginalStones: 23
    },
    {
      value: 26,
      marginalStones: 29
    },
    {
      value: 34,
      marginalStones: 35
    },
    {
      value: 43,
      marginalStones: 41
    },
    {
      value: 55,
      marginalStones: 47
    },
    {
      value: 69,
      marginalStones: 53
    },
    {
      value: 87,
      marginalStones: 61
    },
    {
      value: 108,
      marginalStones: 71
    },
    {
      value: 134,
      marginalStones: 84
    },
    {
      value: 164,
      marginalStones: 100
    },
    {
      value: 200,
      marginalStones: 120
    },
    {
      value: 243,
      marginalStones: 144
    },
    {
      value: 293,
      marginalStones: 174
    },
    {
      value: 352,
      marginalStones: 210
    },
    {
      value: 421,
      marginalStones: 254
    },
    {
      value: 502,
      marginalStones: 308
    },
    {
      value: 597,
      marginalStones: 374
    },
    {
      value: 708,
      marginalStones: 454
    },
    {
      value: 838,
      marginalStones: 540
    },
    {
      value: 989,
      marginalStones: 632
    },
    {
      value: 1165,
      marginalStones: 730
    },
    {
      value: 1370,
      marginalStones: 834
    },
    {
      value: 1608,
      marginalStones: 944
    },
    {
      value: 1886,
      marginalStones: 1060
    },
    {
      value: 2209,
      marginalStones: 1182
    },
    {
      value: 2585,
      marginalStones: 1312
    },
    {
      value: 3021,
      marginalStones: 1448
    }
  ]
},
  innerLandMinesQuantityLevel: {
  valueKind: "count",
  milestones: [
    {
      value: 3,
      marginalStones: 0
    },
    {
      value: 4,
      marginalStones: 50
    },
    {
      value: 5,
      marginalStones: 125
    },
    {
      value: 6,
      marginalStones: 250
    }
  ]
},
  innerLandMinesCooldownLevel: {
  valueKind: "seconds",
  milestones: [
    {
      value: 200,
      marginalStones: 0
    },
    {
      value: 190,
      marginalStones: 8
    },
    {
      value: 180,
      marginalStones: 24
    },
    {
      value: 170,
      marginalStones: 40
    },
    {
      value: 160,
      marginalStones: 56
    },
    {
      value: 150,
      marginalStones: 72
    },
    {
      value: 140,
      marginalStones: 88
    },
    {
      value: 130,
      marginalStones: 104
    },
    {
      value: 120,
      marginalStones: 120
    },
    {
      value: 110,
      marginalStones: 136
    },
    {
      value: 100,
      marginalStones: 152
    },
    {
      value: 90,
      marginalStones: 168
    },
    {
      value: 80,
      marginalStones: 184
    },
    {
      value: 70,
      marginalStones: 200
    },
    {
      value: 60,
      marginalStones: 216
    },
    {
      value: 50,
      marginalStones: 232
    }
  ]
},
  poisonSwampDamageLevel: {
  valueKind: "mult",
  milestones: [
    {
      value: 10,
      marginalStones: 0
    },
    {
      value: 11,
      marginalStones: 5
    },
    {
      value: 13,
      marginalStones: 11
    },
    {
      value: 16,
      marginalStones: 17
    },
    {
      value: 20,
      marginalStones: 23
    },
    {
      value: 26,
      marginalStones: 29
    },
    {
      value: 34,
      marginalStones: 35
    },
    {
      value: 43,
      marginalStones: 41
    },
    {
      value: 55,
      marginalStones: 47
    },
    {
      value: 69,
      marginalStones: 53
    },
    {
      value: 87,
      marginalStones: 61
    },
    {
      value: 108,
      marginalStones: 71
    },
    {
      value: 134,
      marginalStones: 84
    },
    {
      value: 164,
      marginalStones: 100
    },
    {
      value: 200,
      marginalStones: 120
    },
    {
      value: 243,
      marginalStones: 144
    },
    {
      value: 293,
      marginalStones: 174
    },
    {
      value: 352,
      marginalStones: 210
    },
    {
      value: 421,
      marginalStones: 252
    },
    {
      value: 502,
      marginalStones: 302
    },
    {
      value: 597,
      marginalStones: 362
    },
    {
      value: 708,
      marginalStones: 434
    },
    {
      value: 838,
      marginalStones: 525
    },
    {
      value: 989,
      marginalStones: 636
    },
    {
      value: 1165,
      marginalStones: 772
    },
    {
      value: 1370,
      marginalStones: 938
    },
    {
      value: 1608,
      marginalStones: 1134
    },
    {
      value: 1886,
      marginalStones: 1360
    },
    {
      value: 2209,
      marginalStones: 1616
    },
    {
      value: 2585,
      marginalStones: 1902
    },
    {
      value: 3021,
      marginalStones: 2228
    }
  ]
},
  poisonSwampDurationLevel: {
  valueKind: "seconds",
  milestones: [
    {
      value: 30,
      marginalStones: 0
    },
    {
      value: 35,
      marginalStones: 10
    },
    {
      value: 40,
      marginalStones: 20
    },
    {
      value: 45,
      marginalStones: 35
    },
    {
      value: 50,
      marginalStones: 55
    },
    {
      value: 55,
      marginalStones: 100
    },
    {
      value: 60,
      marginalStones: 120
    },
    {
      value: 65,
      marginalStones: 150
    },
    {
      value: 70,
      marginalStones: 200
    },
    {
      value: 75,
      marginalStones: 260
    },
    {
      value: 80,
      marginalStones: 330
    },
    {
      value: 85,
      marginalStones: 410
    },
    {
      value: 90,
      marginalStones: 500
    },
    {
      value: 95,
      marginalStones: 600
    },
    {
      value: 100,
      marginalStones: 710
    }
  ]
},
  poisonSwampCooldownLevel: {
  valueKind: "seconds",
  milestones: [
    {
      value: 125,
      marginalStones: 0
    },
    {
      value: 120,
      marginalStones: 8
    },
    {
      value: 115,
      marginalStones: 26
    },
    {
      value: 110,
      marginalStones: 44
    },
    {
      value: 105,
      marginalStones: 62
    },
    {
      value: 100,
      marginalStones: 80
    },
    {
      value: 95,
      marginalStones: 98
    },
    {
      value: 90,
      marginalStones: 116
    },
    {
      value: 85,
      marginalStones: 134
    },
    {
      value: 80,
      marginalStones: 152
    },
    {
      value: 75,
      marginalStones: 170
    },
    {
      value: 70,
      marginalStones: 188
    },
    {
      value: 65,
      marginalStones: 206
    },
    {
      value: 60,
      marginalStones: 224
    },
    {
      value: 55,
      marginalStones: 242
    },
    {
      value: 50,
      marginalStones: 260
    }
  ]
},
  chronoFieldDurationLevel: {
  valueKind: "seconds",
  milestones: [
    {
      value: 5,
      marginalStones: 0
    },
    {
      value: 6,
      marginalStones: 5
    },
    {
      value: 7,
      marginalStones: 14
    },
    {
      value: 8,
      marginalStones: 23
    },
    {
      value: 9,
      marginalStones: 32
    },
    {
      value: 10,
      marginalStones: 41
    },
    {
      value: 11,
      marginalStones: 50
    },
    {
      value: 12,
      marginalStones: 59
    },
    {
      value: 13,
      marginalStones: 68
    },
    {
      value: 14,
      marginalStones: 77
    },
    {
      value: 15,
      marginalStones: 86
    },
    {
      value: 16,
      marginalStones: 95
    },
    {
      value: 17,
      marginalStones: 104
    },
    {
      value: 18,
      marginalStones: 113
    },
    {
      value: 19,
      marginalStones: 122
    },
    {
      value: 20,
      marginalStones: 131
    },
    {
      value: 21,
      marginalStones: 140
    },
    {
      value: 22,
      marginalStones: 149
    },
    {
      value: 23,
      marginalStones: 158
    },
    {
      value: 24,
      marginalStones: 167
    },
    {
      value: 25,
      marginalStones: 176
    },
    {
      value: 26,
      marginalStones: 185
    },
    {
      value: 27,
      marginalStones: 194
    },
    {
      value: 28,
      marginalStones: 203
    },
    {
      value: 29,
      marginalStones: 212
    },
    {
      value: 30,
      marginalStones: 221
    },
    {
      value: 31,
      marginalStones: 230
    },
    {
      value: 32,
      marginalStones: 239
    },
    {
      value: 33,
      marginalStones: 248
    },
    {
      value: 34,
      marginalStones: 257
    },
    {
      value: 35,
      marginalStones: 266
    },
    {
      value: 36,
      marginalStones: 275
    },
    {
      value: 37,
      marginalStones: 284
    },
    {
      value: 38,
      marginalStones: 293
    },
    {
      value: 39,
      marginalStones: 302
    },
    {
      value: 40,
      marginalStones: 311
    }
  ]
},
  chronoFieldSlowLevel: {
  valueKind: "percent",
  milestones: [
    {
      value: 20,
      marginalStones: 0
    },
    {
      value: 25,
      marginalStones: 15
    },
    {
      value: 30,
      marginalStones: 25
    },
    {
      value: 35,
      marginalStones: 40
    },
    {
      value: 40,
      marginalStones: 60
    },
    {
      value: 45,
      marginalStones: 120
    },
    {
      value: 50,
      marginalStones: 150
    },
    {
      value: 55,
      marginalStones: 200
    },
    {
      value: 60,
      marginalStones: 300
    },
    {
      value: 65,
      marginalStones: 450
    },
    {
      value: 70,
      marginalStones: 650
    },
    {
      value: 75,
      marginalStones: 900
    }
  ]
},
  chronoFieldCooldownLevel: {
  valueKind: "seconds",
  milestones: [
    {
      value: 180,
      marginalStones: 0
    },
    {
      value: 170,
      marginalStones: 10
    },
    {
      value: 160,
      marginalStones: 31
    },
    {
      value: 150,
      marginalStones: 52
    },
    {
      value: 140,
      marginalStones: 73
    },
    {
      value: 130,
      marginalStones: 94
    },
    {
      value: 120,
      marginalStones: 115
    },
    {
      value: 110,
      marginalStones: 136
    },
    {
      value: 100,
      marginalStones: 157
    },
    {
      value: 90,
      marginalStones: 178
    },
    {
      value: 80,
      marginalStones: 199
    },
    {
      value: 70,
      marginalStones: 220
    },
    {
      value: 60,
      marginalStones: 241
    }
  ]
},
}
