/**
 * Authoritative workshop ladder data from `tables/workshop/` JSON.
 * Loaded at runtime from `public/tables/workshop/` (see loadGodTables.ts).
 * Generated by scripts/sync-workshop-god-tables.mjs — do not hand-edit store helpers.
 */

export type WorkshopGodAmount = {
  display: string
  coins?: number | null
  cash?: number | null
  maxed?: boolean
}

export type WorkshopGodLevel = {
  level: number
  value: number | null
  valueDisplay?: string
  nextCoins: WorkshopGodAmount
  additionalCoins: WorkshopGodAmount
  totalCoins: WorkshopGodAmount
  /** Present on full workshop upgrade tables; omitted on enhancement tables. */
  nextCash?: WorkshopGodAmount
  additionalCash?: WorkshopGodAmount
  totalCash?: WorkshopGodAmount
  cashToTarget?: WorkshopGodAmount
  cashToMax?: WorkshopGodAmount
}

export type WorkshopGodTable = {
  name: string
  category: string
  maxLevel: number
  levels: WorkshopGodLevel[]
}

let workshopGodTables: Record<string, WorkshopGodTable> = {}

/** Expected workshop GOD table count (manifest sanity check). */
export const WORKSHOP_GOD_TABLE_COUNT = 66

export function installWorkshopGodTables(
  tables: Record<string, WorkshopGodTable>,
): void {
  workshopGodTables = tables
}

export function getWorkshopGodTables(): Readonly<Record<string, WorkshopGodTable>> {
  return workshopGodTables
}

export function getWorkshopGodUpgradeNames(): ReadonlySet<string> {
  return new Set(Object.keys(workshopGodTables))
}

/** Row for workshop level L from a GOD table, if present. */
export function workshopGodLevelEntry(
  upgradeDisplayName: string,
  level: number,
): WorkshopGodLevel | undefined {
  const table = workshopGodTables[upgradeDisplayName]
  if (!table || !Number.isFinite(level) || level < 0) return undefined
  return table.levels.find((row) => row.level === level)
}

/** Marginal coins for the upgrade ending at `targetLevel` (wiki **Next Coins** on row targetLevel−1). */
export function workshopGodMarginalCoins(
  upgradeDisplayName: string,
  targetLevel: number,
): number | undefined {
  if (!Number.isFinite(targetLevel) || targetLevel < 1) return undefined
  const row = workshopGodLevelEntry(upgradeDisplayName, targetLevel - 1)
  const coins = row?.nextCoins?.coins
  return typeof coins === 'number' && Number.isFinite(coins) ? coins : undefined
}
