/** Wiki bot upgrade tables — generated by scripts/gen-workshop-bots-data.mjs */

import type { WorkshopUltimateTrack } from './workshopUltimateTable'

export type WorkshopBotId = 'flame' | 'thunder' | 'golden' | 'amplify' | 'botBot'

export type WorkshopBotUpgradeKey =
  | 'flameBotDamageReductionLevel'
  | 'flameBotCooldownLevel'
  | 'flameBotDamageLevel'
  | 'flameBotRangeLevel'
  | 'thunderBotDurationLevel'
  | 'thunderBotCooldownLevel'
  | 'thunderBotLingerLevel'
  | 'thunderBotRangeLevel'
  | 'goldenBotDurationLevel'
  | 'goldenBotCooldownLevel'
  | 'goldenBotBonusLevel'
  | 'goldenBotRangeLevel'
  | 'amplifyBotDurationLevel'
  | 'amplifyBotCooldownLevel'
  | 'amplifyBotBonusLevel'
  | 'amplifyBotRangeLevel'
  | 'botBotDurationLevel'
  | 'botBotCooldownLevel'
  | 'botBotBonusLevel'
  | 'botBotRangeLevel'

export type WorkshopBotSpecialKey =
  | 'flameBotBurningGroundUnlocked'
  | 'thunderBotTitanShockUnlocked'
  | 'goldenBotBonusCellsUnlocked'
  | 'amplifyBotEchoingShotUnlocked'
  | 'botBotMaximumPowerUnlocked'

export type WorkshopBotSpecialLevelKey =
  | 'flameBotBurningGroundLevel'
  | 'thunderBotTitanShockLevel'
  | 'goldenBotBonusCellsLevel'
  | 'amplifyBotEchoingShotLevel'
  | 'botBotMaximumPowerLevel'

export const WORKSHOP_BOT_ORDER: readonly WorkshopBotId[] = ["flame","thunder","golden","amplify","botBot"]

export const WORKSHOP_BOT_UPGRADE_ORDER: readonly WorkshopBotUpgradeKey[] = ["flameBotDamageReductionLevel","flameBotCooldownLevel","flameBotDamageLevel","flameBotRangeLevel","thunderBotDurationLevel","thunderBotCooldownLevel","thunderBotLingerLevel","thunderBotRangeLevel","goldenBotDurationLevel","goldenBotCooldownLevel","goldenBotBonusLevel","goldenBotRangeLevel","amplifyBotDurationLevel","amplifyBotCooldownLevel","amplifyBotBonusLevel","amplifyBotRangeLevel","botBotDurationLevel","botBotCooldownLevel","botBotBonusLevel","botBotRangeLevel"]

export const WORKSHOP_BOT_SPECIAL_LEVEL_ORDER: readonly WorkshopBotSpecialLevelKey[] = ["flameBotBurningGroundLevel","thunderBotTitanShockLevel","goldenBotBonusCellsLevel","amplifyBotEchoingShotLevel","botBotMaximumPowerLevel"]

/** Level before stone unlock (wiki: ability not purchased). */
export const WORKSHOP_BOT_SPECIAL_LEVEL_LOCKED = -1 as const

export const WORKSHOP_BOT_SPECIAL_UNLOCK_STONES = 1250 as const

export const WORKSHOP_BOT_SPECIAL_BY_BOT: Record<WorkshopBotId, WorkshopBotSpecialKey> = {"flame":"flameBotBurningGroundUnlocked","thunder":"thunderBotTitanShockUnlocked","golden":"goldenBotBonusCellsUnlocked","amplify":"amplifyBotEchoingShotUnlocked","botBot":"botBotMaximumPowerUnlocked"}

export const WORKSHOP_BOT_SPECIAL_LEVEL_BY_BOT: Record<WorkshopBotId, WorkshopBotSpecialLevelKey> = {"flame":"flameBotBurningGroundLevel","thunder":"thunderBotTitanShockLevel","golden":"goldenBotBonusCellsLevel","amplify":"amplifyBotEchoingShotLevel","botBot":"botBotMaximumPowerLevel"}

export const WORKSHOP_BOT_WEAPON_STATS: Record<
  WorkshopBotId,
  readonly { key: WorkshopBotUpgradeKey; stat: string }[]
> = {
  flame: [
    {
      key: "flameBotDamageReductionLevel",
      stat: "damageReduction"
    },
    {
      key: "flameBotCooldownLevel",
      stat: "cooldown"
    },
    {
      key: "flameBotDamageLevel",
      stat: "damage"
    },
    {
      key: "flameBotRangeLevel",
      stat: "range"
    }
  ],
  thunder: [
    {
      key: "thunderBotDurationLevel",
      stat: "duration"
    },
    {
      key: "thunderBotCooldownLevel",
      stat: "cooldown"
    },
    {
      key: "thunderBotLingerLevel",
      stat: "linger"
    },
    {
      key: "thunderBotRangeLevel",
      stat: "range"
    }
  ],
  golden: [
    {
      key: "goldenBotDurationLevel",
      stat: "duration"
    },
    {
      key: "goldenBotCooldownLevel",
      stat: "cooldown"
    },
    {
      key: "goldenBotBonusLevel",
      stat: "bonus"
    },
    {
      key: "goldenBotRangeLevel",
      stat: "range"
    }
  ],
  amplify: [
    {
      key: "amplifyBotDurationLevel",
      stat: "duration"
    },
    {
      key: "amplifyBotCooldownLevel",
      stat: "cooldown"
    },
    {
      key: "amplifyBotBonusLevel",
      stat: "bonus"
    },
    {
      key: "amplifyBotRangeLevel",
      stat: "range"
    }
  ],
  botBot: [
    {
      key: "botBotDurationLevel",
      stat: "duration"
    },
    {
      key: "botBotCooldownLevel",
      stat: "cooldown"
    },
    {
      key: "botBotBonusLevel",
      stat: "bonus"
    },
    {
      key: "botBotRangeLevel",
      stat: "range"
    }
  ]
}

function track(kind: WorkshopUltimateTrack['valueKind'], rows: readonly (readonly [number, number])[]) {
  return {
    valueKind: kind,
    milestones: rows.map(([value, marginalStones], i) => ({
      value,
      marginalStones: i === 0 ? 0 : marginalStones,
    })),
  } satisfies WorkshopUltimateTrack
}

export const WORKSHOP_BOT_TRACKS: Record<WorkshopBotUpgradeKey, WorkshopUltimateTrack> = {
  flameBotDamageReductionLevel: track('percent', [[20, 0], [23, 100], [26, 140], [29, 180], [32, 220], [35, 260], [38, 300], [41, 340], [44, 380], [47, 420], [50, 460], [53, 500], [56, 540], [59, 580], [62, 620], [65, 660], [68, 700], [71, 740], [74, 780], [77, 820], [80, 860], [83, 900], [86, 940], [89, 980], [92, 1020], [95, 1060]]),
  flameBotCooldownLevel: track('seconds', [[75, 0], [72, 100], [69, 140], [66, 180], [63, 220], [60, 260], [57, 300], [54, 340], [51, 380], [48, 420], [45, 460], [42, 500], [39, 540], [36, 580], [33, 620], [30, 660]]),
  flameBotDamageLevel: track('mult', [[50, 0], [58, 100], [66, 140], [74, 180], [82, 220], [90, 260], [98, 300], [106, 340], [114, 380], [122, 420], [130, 460], [138, 500], [146, 540], [154, 580], [162, 620], [170, 660], [178, 700], [186, 740], [194, 780], [202, 820], [210, 860], [218, 900], [226, 940], [234, 980], [242, 1020], [250, 1060], [258, 1100], [266, 1140], [274, 1180], [282, 1220], [290, 1260]]),
  flameBotRangeLevel: track('meters', [[30, 0], [34, 100], [38, 140], [42, 180], [46, 220], [50, 260], [54, 300], [58, 340], [62, 380], [66, 420], [70, 460], [74, 500], [78, 540], [82, 580], [86, 620], [90, 660]]),
  thunderBotDurationLevel: track('seconds', [[5, 0], [5.5, 100], [6, 140], [6.5, 180], [7, 220], [7.5, 260], [8, 300], [8.5, 340], [9, 380], [9.5, 420], [10, 460], [10.5, 500], [11, 540], [11.5, 580], [12, 620], [12.5, 660], [13, 700], [13.5, 740], [14, 780], [14.5, 820], [15, 860]]),
  thunderBotCooldownLevel: track('seconds', [[120, 0], [117, 100], [114, 140], [111, 180], [108, 220], [105, 260], [102, 300], [99, 340], [96, 380], [93, 420], [90, 460], [87, 500], [84, 540], [81, 580], [78, 620], [75, 660]]),
  thunderBotLingerLevel: track('percent', [[20, 0], [23, 100], [26, 140], [29, 180], [32, 220], [35, 260], [38, 300], [41, 340], [44, 380], [47, 420], [50, 460], [53, 500], [56, 540], [59, 580], [62, 620], [65, 660], [68, 700], [71, 740], [74, 780], [77, 820], [80, 860]]),
  thunderBotRangeLevel: track('meters', [[25, 0], [28, 100], [31, 140], [34, 180], [37, 220], [40, 260], [43, 300], [46, 340], [49, 380], [52, 420], [55, 460], [58, 500], [61, 540], [64, 580], [67, 620], [70, 660]]),
  goldenBotDurationLevel: track('seconds', [[20, 0], [20.5, 100], [21, 140], [21.5, 180], [22, 220], [22.5, 260], [23, 300], [23.5, 340], [24, 380], [24.5, 420], [25, 460], [25.5, 500], [26, 540], [26.5, 580], [27, 620], [27.5, 660], [28, 700], [28.5, 740], [29, 780], [29.5, 820], [30, 860], [30.5, 900], [31, 940], [31.5, 980], [32, 1020], [32.5, 1060], [33, 1100], [33.5, 1140], [34, 1180], [34.5, 1220], [35, 1260]]),
  goldenBotCooldownLevel: track('seconds', [[120, 0], [117, 100], [114, 140], [111, 180], [108, 220], [105, 260], [102, 300], [99, 340], [96, 380], [93, 420], [90, 460], [87, 500], [84, 540], [81, 580], [78, 620], [75, 660]]),
  goldenBotBonusLevel: track('mult', [[2, 0], [2.2, 100], [2.4, 140], [2.6, 180], [2.8, 220], [3, 260], [3.2, 300], [3.4, 340], [3.6, 380], [3.8, 420], [4, 460], [4.2, 500], [4.4, 540], [4.6, 580], [4.8, 620], [5, 660], [5.2, 700], [5.4, 740], [5.6, 780], [5.8, 820], [6, 860], [6.2, 900], [6.4, 940], [6.6, 980], [6.8, 1020], [7, 1060], [7.2, 1100], [7.4, 1140], [7.6, 1180], [7.8, 1220], [8, 1260]]),
  goldenBotRangeLevel: track('meters', [[20, 0], [22, 100], [24, 140], [26, 180], [28, 220], [30, 260], [32, 300], [34, 340], [36, 380], [38, 420], [40, 460], [42, 500], [44, 540], [46, 580], [48, 620], [50, 660], [52, 700], [54, 740], [56, 780], [58, 820], [60, 860]]),
  amplifyBotDurationLevel: track('seconds', [[20, 0], [20.5, 100], [21, 140], [21.5, 180], [22, 220], [22.5, 260], [23, 300], [23.5, 340], [24, 380], [24.5, 420], [25, 460], [25.5, 500], [26, 540], [26.5, 580], [27, 620], [27.5, 660], [28, 700], [28.5, 740], [29, 780], [29.5, 820], [30, 860], [30.5, 900], [31, 940], [31.5, 980], [32, 1020], [32.5, 1060], [33, 1100], [33.5, 1140], [34, 1180], [34.5, 1220], [35, 1260]]),
  amplifyBotCooldownLevel: track('seconds', [[120, 0], [117, 100], [114, 140], [111, 180], [108, 220], [105, 260], [102, 300], [99, 340], [96, 380], [93, 420], [90, 460], [87, 500], [84, 540], [81, 580], [78, 620], [75, 660]]),
  amplifyBotBonusLevel: track('mult', [[3.5, 0], [3.9, 100], [4.3, 140], [4.7, 180], [5.1, 220], [5.5, 260], [5.9, 300], [6.3, 340], [6.7, 380], [7.1, 420], [7.5, 460], [7.9, 500], [8.3, 540], [8.7, 580], [9.1, 620], [9.5, 660], [9.9, 700], [10.3, 740], [10.7, 780], [11.1, 820], [11.5, 860], [11.9, 900], [12.3, 940], [12.7, 980], [13.1, 1020], [13.5, 1060], [13.9, 1100], [14.3, 1140], [14.7, 1180], [15.1, 1220], [15.5, 1260]]),
  amplifyBotRangeLevel: track('meters', [[25, 0], [27, 100], [29, 140], [31, 180], [33, 220], [35, 260], [37, 300], [39, 340], [41, 380], [43, 420], [45, 460], [47, 500], [49, 540], [51, 580], [53, 620], [55, 660], [57, 700], [59, 740], [61, 780]]),
  botBotDurationLevel: track('seconds', [[20, 0], [20.5, 100], [21, 140], [21.5, 180], [22, 220], [22.5, 260], [23, 300], [23.5, 340], [24, 380], [24.5, 420], [25, 460], [25.5, 500], [26, 540], [26.5, 580], [27, 620], [27.5, 660], [28, 700], [28.5, 740], [29, 780], [29.5, 820], [30, 860], [30.5, 900], [31, 940], [31.5, 980], [32, 1020], [32.5, 1060], [33, 1100], [33.5, 1140], [34, 1180], [34.5, 1220], [35, 1260]]),
  botBotCooldownLevel: track('seconds', [[120, 0], [117, 100], [114, 140], [111, 180], [108, 220], [105, 260], [102, 300], [99, 340], [96, 380], [93, 420], [90, 460], [87, 500], [84, 540], [81, 580], [78, 620], [75, 660]]),
  botBotBonusLevel: track('mult', [[1, 0], [1.05, 100], [1.1, 140], [1.15, 180], [1.2, 220], [1.25, 260], [1.3, 300], [1.35, 340], [1.4, 380], [1.45, 420], [1.5, 460], [1.55, 500], [1.6, 540], [1.65, 580], [1.7, 620], [1.75, 660], [1.8, 700], [1.85, 740], [1.9, 780], [1.95, 820], [2, 860], [2.05, 900], [2.1, 940], [2.15, 980], [2.2, 1020], [2.25, 1060], [2.3, 1100], [2.35, 1140], [2.4, 1180], [2.45, 1220], [2.5, 1260]]),
  botBotRangeLevel: track('meters', [[20, 0], [22, 100], [24, 140], [26, 180], [28, 220], [30, 260], [32, 300], [34, 340], [36, 380], [38, 420], [40, 460], [42, 500], [44, 540], [46, 580], [48, 620], [50, 660], [52, 700], [54, 740], [56, 780], [58, 820], [60, 860]]),
}

export const WORKSHOP_BOT_SPECIAL_TRACKS: Record<WorkshopBotSpecialLevelKey, WorkshopUltimateTrack> = {
  flameBotBurningGroundLevel: track('mult', [[1.5, 0], [1.6, 100], [1.7, 150], [1.8, 200], [1.9, 250], [2, 300], [2.1, 350], [2.2, 400], [2.3, 450], [2.4, 500], [2.5, 550], [2.6, 600], [2.7, 650], [2.8, 700], [2.9, 750], [3, 800], [3.1, 850], [3.2, 900], [3.3, 950], [3.4, 1000], [3.5, 1050]]),
  thunderBotTitanShockLevel: track('percent', [[5, 0], [6, 100], [7, 150], [8, 200], [9, 250], [10, 300], [11, 350], [12, 400], [13, 450], [14, 500], [15, 550], [16, 600], [17, 650], [18, 700], [19, 750], [20, 800], [21, 850], [22, 900], [23, 950], [24, 1000], [25, 1050]]),
  goldenBotBonusCellsLevel: track('mult', [[1.25, 0], [1.3, 100], [1.35, 150], [1.4, 200], [1.45, 250], [1.5, 300], [1.55, 350], [1.6, 400], [1.65, 450], [1.7, 500], [1.75, 550], [1.8, 600], [1.85, 650], [1.9, 700], [1.95, 750], [2, 800], [2.05, 850], [2.1, 900], [2.15, 950], [2.2, 1000], [2.25, 1050], [2.3, 1100], [2.35, 1150], [2.4, 1200], [2.45, 1250], [2.5, 1300]]),
  amplifyBotEchoingShotLevel: track('count', [[3, 0], [4, 100], [5, 300], [6, 500], [7, 700], [8, 900], [9, 1100], [10, 1300], [11, 1500], [12, 1700]]),
  botBotMaximumPowerLevel: track('mult', [[1.25, 0], [1.3, 100], [1.35, 150], [1.4, 200], [1.45, 250], [1.5, 300], [1.55, 350], [1.6, 400], [1.65, 450], [1.7, 500], [1.75, 550], [1.8, 600], [1.85, 650], [1.9, 700], [1.95, 750], [2, 800], [2.05, 850], [2.1, 900], [2.15, 950], [2.2, 1000], [2.25, 1050]]),
}
