/**
 * Authoritative workshop ladder data from `tables/workshop/` JSON (workshop calculator exports).
 * Generated by scripts/sync-workshop-god-tables.mjs — do not hand-edit imports or WORKSHOP_GOD_TABLES.
 */

import attackSpeed from '../../tables/workshop/attack/attack-speed.json'
import attackSpeedPlus from '../../tables/workshop/enhancements/attack/attack-speed-plus.json'
import bounceShotChance from '../../tables/workshop/attack/bounce-shot-chance.json'
import bounceShotRange from '../../tables/workshop/attack/bounce-shot-range.json'
import bounceShotTargets from '../../tables/workshop/attack/bounce-shot-targets.json'
import cashWave from '../../tables/workshop/utility/cash-wave.json'
import cashBonus from '../../tables/workshop/utility/cash-bonus.json'
import cashBonusPlus from '../../tables/workshop/enhancements/utility/cash-bonus-plus.json'
import cellsKillBonus from '../../tables/workshop/enhancements/utility/cells-kill-bonus.json'
import coinBonusPlus from '../../tables/workshop/enhancements/utility/coin-bonus-plus.json'
import coinsKillBonus from '../../tables/workshop/utility/coins-kill-bonus.json'
import coinsWave from '../../tables/workshop/utility/coins-wave.json'
import criticalChance from '../../tables/workshop/attack/critical-chance.json'
import criticalFactor from '../../tables/workshop/attack/critical-factor.json'
import criticalFactorPlus from '../../tables/workshop/enhancements/attack/critical-factor-plus.json'
import damage from '../../tables/workshop/attack/damage.json'
import damageMeter from '../../tables/workshop/attack/damage-meter.json'
import damageMeterPlus from '../../tables/workshop/enhancements/attack/damage-meter-plus.json'
import damagePlus from '../../tables/workshop/enhancements/attack/damage-plus.json'
import deathDefy from '../../tables/workshop/defense/death-defy.json'
import defenseAbsolute from '../../tables/workshop/defense/defense-absolute.json'
import defenseAbsolutePlus from '../../tables/workshop/enhancements/defense/defense-absolute-plus.json'
import defensePercent from '../../tables/workshop/defense/defense-percent.json'
import enemyAttackLevelSkip from '../../tables/workshop/utility/enemy-attack-level-skip.json'
import enemyHealthLevelSkip from '../../tables/workshop/utility/enemy-health-level-skip.json'
import enemyLevelSkipPlus from '../../tables/workshop/enhancements/utility/enemy-level-skip-plus.json'
import freeAttackUpgrade from '../../tables/workshop/utility/free-attack-upgrade.json'
import freeDefenseUpgrade from '../../tables/workshop/utility/free-defense-upgrade.json'
import freeUpgradesPlus from '../../tables/workshop/enhancements/utility/free-upgrades-plus.json'
import freeUtilityUpgrade from '../../tables/workshop/utility/free-utility-upgrade.json'
import health from '../../tables/workshop/defense/health.json'
import healthPlus from '../../tables/workshop/enhancements/defense/health-plus.json'
import healthRegen from '../../tables/workshop/defense/health-regen.json'
import healthRegenPlus from '../../tables/workshop/enhancements/defense/health-regen-plus.json'
import interestWave from '../../tables/workshop/utility/interest-wave.json'
import knockbackChance from '../../tables/workshop/defense/knockback-chance.json'
import knockbackForce from '../../tables/workshop/defense/knockback-force.json'
import landMineChance from '../../tables/workshop/defense/land-mine-chance.json'
import landMineDamage from '../../tables/workshop/defense/land-mine-damage.json'
import landMineDamagePlus from '../../tables/workshop/enhancements/defense/land-mine-damage-plus.json'
import landMineRadius from '../../tables/workshop/defense/land-mine-radius.json'
import lifesteal from '../../tables/workshop/defense/lifesteal.json'
import maxRecovery from '../../tables/workshop/utility/max-recovery.json'
import multishotChance from '../../tables/workshop/attack/multishot-chance.json'
import multishotTargets from '../../tables/workshop/attack/multishot-targets.json'
import orbSize from '../../tables/workshop/enhancements/defense/orb-size.json'
import orbSpeed from '../../tables/workshop/defense/orb-speed.json'
import orbs from '../../tables/workshop/defense/orbs.json'
import packageChance from '../../tables/workshop/utility/package-chance.json'
import range from '../../tables/workshop/attack/range.json'
import rapidFireChance from '../../tables/workshop/attack/rapid-fire-chance.json'
import rapidFireDuration from '../../tables/workshop/attack/rapid-fire-duration.json'
import recoveryAmount from '../../tables/workshop/utility/recovery-amount.json'
import recoveryPackagePlus from '../../tables/workshop/enhancements/utility/recovery-package-plus.json'
import rendArmorChance from '../../tables/workshop/attack/rend-armor-chance.json'
import rendArmorMax from '../../tables/workshop/enhancements/attack/rend-armor-max.json'
import rendArmorMult from '../../tables/workshop/attack/rend-armor-mult.json'
import shockwaveFrequency from '../../tables/workshop/defense/shockwave-frequency.json'
import shockwaveSize from '../../tables/workshop/defense/shockwave-size.json'
import superCritChance from '../../tables/workshop/attack/super-crit-chance.json'
import superCritMult from '../../tables/workshop/attack/super-crit-mult.json'
import superCritMultPlus from '../../tables/workshop/enhancements/attack/super-crit-mult-plus.json'
import thorns from '../../tables/workshop/defense/thorns.json'
import wallHealth from '../../tables/workshop/defense/wall-health.json'
import wallHealthPlus from '../../tables/workshop/enhancements/defense/wall-health-plus.json'
import wallRebuild from '../../tables/workshop/defense/wall-rebuild.json'

export type WorkshopGodAmount = {
  display: string
  coins?: number | null
  cash?: number | null
  maxed?: boolean
}

export type WorkshopGodLevel = {
  level: number
  value: number | null
  valueDisplay?: string
  nextCoins: WorkshopGodAmount
  additionalCoins: WorkshopGodAmount
  totalCoins: WorkshopGodAmount
  /** Present on full workshop upgrade tables; omitted on enhancement tables. */
  nextCash?: WorkshopGodAmount
  additionalCash?: WorkshopGodAmount
  totalCash?: WorkshopGodAmount
  cashToTarget?: WorkshopGodAmount
  cashToMax?: WorkshopGodAmount
}

export type WorkshopGodTable = {
  name: string
  category: string
  maxLevel: number
  levels: WorkshopGodLevel[]
}

export const WORKSHOP_GOD_TABLES: Record<string, WorkshopGodTable> = {
  'Attack Speed': attackSpeed as WorkshopGodTable,
  'Attack Speed +': attackSpeedPlus as WorkshopGodTable,
  'Bounce Shot Chance': bounceShotChance as WorkshopGodTable,
  'Bounce Shot Range': bounceShotRange as WorkshopGodTable,
  'Bounce Shot Targets': bounceShotTargets as WorkshopGodTable,
  'Cash - Wave': cashWave as WorkshopGodTable,
  'Cash Bonus': cashBonus as WorkshopGodTable,
  'Cash Bonus +': cashBonusPlus as WorkshopGodTable,
  'Cells - Kill Bonus': cellsKillBonus as WorkshopGodTable,
  'Coin Bonus +': coinBonusPlus as WorkshopGodTable,
  'Coins - Kill Bonus': coinsKillBonus as WorkshopGodTable,
  'Coins - Wave': coinsWave as WorkshopGodTable,
  'Critical Chance': criticalChance as WorkshopGodTable,
  'Critical Factor': criticalFactor as WorkshopGodTable,
  'Critical Factor +': criticalFactorPlus as WorkshopGodTable,
  'Damage': damage as WorkshopGodTable,
  'Damage - Meter': damageMeter as WorkshopGodTable,
  'Damage - Meter +': damageMeterPlus as WorkshopGodTable,
  'Damage +': damagePlus as WorkshopGodTable,
  'Death Defy': deathDefy as WorkshopGodTable,
  'Defense Absolute': defenseAbsolute as WorkshopGodTable,
  'Defense Absolute +': defenseAbsolutePlus as WorkshopGodTable,
  'Defense Percent': defensePercent as WorkshopGodTable,
  'Enemy Attack Level Skip': enemyAttackLevelSkip as WorkshopGodTable,
  'Enemy Health Level Skip': enemyHealthLevelSkip as WorkshopGodTable,
  'Enemy Level Skip +': enemyLevelSkipPlus as WorkshopGodTable,
  'Free Attack Upgrade': freeAttackUpgrade as WorkshopGodTable,
  'Free Defense Upgrade': freeDefenseUpgrade as WorkshopGodTable,
  'Free Upgrades +': freeUpgradesPlus as WorkshopGodTable,
  'Free Utility Upgrade': freeUtilityUpgrade as WorkshopGodTable,
  'Health': health as WorkshopGodTable,
  'Health +': healthPlus as WorkshopGodTable,
  'Health Regen': healthRegen as WorkshopGodTable,
  'Health Regen +': healthRegenPlus as WorkshopGodTable,
  'Interest - Wave': interestWave as WorkshopGodTable,
  'Knockback Chance': knockbackChance as WorkshopGodTable,
  'Knockback Force': knockbackForce as WorkshopGodTable,
  'Land Mine Chance': landMineChance as WorkshopGodTable,
  'Land Mine Damage': landMineDamage as WorkshopGodTable,
  'Land Mine Damage +': landMineDamagePlus as WorkshopGodTable,
  'Land Mine Radius': landMineRadius as WorkshopGodTable,
  'Lifesteal': lifesteal as WorkshopGodTable,
  'Max Recovery': maxRecovery as WorkshopGodTable,
  'Multishot Chance': multishotChance as WorkshopGodTable,
  'Multishot Targets': multishotTargets as WorkshopGodTable,
  'Orb Size': orbSize as WorkshopGodTable,
  'Orb Speed': orbSpeed as WorkshopGodTable,
  'Orbs': orbs as WorkshopGodTable,
  'Package Chance': packageChance as WorkshopGodTable,
  'Range': range as WorkshopGodTable,
  'Rapid Fire Chance': rapidFireChance as WorkshopGodTable,
  'Rapid Fire Duration': rapidFireDuration as WorkshopGodTable,
  'Recovery Amount': recoveryAmount as WorkshopGodTable,
  'Recovery Package +': recoveryPackagePlus as WorkshopGodTable,
  'Rend Armor Chance': rendArmorChance as WorkshopGodTable,
  'Rend Armor Max': rendArmorMax as WorkshopGodTable,
  'Rend Armor Mult': rendArmorMult as WorkshopGodTable,
  'Shockwave Frequency': shockwaveFrequency as WorkshopGodTable,
  'Shockwave Size': shockwaveSize as WorkshopGodTable,
  'Super Crit Chance': superCritChance as WorkshopGodTable,
  'Super Crit Mult': superCritMult as WorkshopGodTable,
  'Super Crit Mult +': superCritMultPlus as WorkshopGodTable,
  'Thorns': thorns as WorkshopGodTable,
  'Wall Health': wallHealth as WorkshopGodTable,
  'Wall Health +': wallHealthPlus as WorkshopGodTable,
  'Wall Rebuild': wallRebuild as WorkshopGodTable,
}

/** Workshop upgrade display names with a GOD table in `tables/workshop/`. */
export const WORKSHOP_GOD_UPGRADE_NAMES: ReadonlySet<string> = new Set(
  Object.keys(WORKSHOP_GOD_TABLES),
)

/** Row for workshop level L from a GOD table, if present. */
export function workshopGodLevelEntry(
  upgradeDisplayName: string,
  level: number,
): WorkshopGodLevel | undefined {
  const table = WORKSHOP_GOD_TABLES[upgradeDisplayName]
  if (!table || !Number.isFinite(level) || level < 0) return undefined
  return table.levels.find((row) => row.level === level)
}

/** Marginal coins for the upgrade ending at `targetLevel` (wiki **Next Coins** on row targetLevel−1). */
export function workshopGodMarginalCoins(
  upgradeDisplayName: string,
  targetLevel: number,
): number | undefined {
  if (!Number.isFinite(targetLevel) || targetLevel < 1) return undefined
  const row = workshopGodLevelEntry(upgradeDisplayName, targetLevel - 1)
  const coins = row?.nextCoins?.coins
  return typeof coins === 'number' && Number.isFinite(coins) ? coins : undefined
}
