/**
 * Authoritative workshop display-card formula specs from `tables/workshop/formulas/`.
 * Generated by scripts/sync-workshop-formula-tables.mjs — do not hand-edit.
 */

import type { WorkshopFormulaSpec } from './workshopFormulaTypes'
import formula0 from '../../tables/workshop/formulas/utility/cash-bonus.json' with { type: 'json' }
import formula1 from '../../tables/workshop/formulas/utility/cash-wave.json' with { type: 'json' }
import formula2 from '../../tables/workshop/formulas/utility/coins-kill-bonus.json' with { type: 'json' }
import formula3 from '../../tables/workshop/formulas/utility/coins-wave.json' with { type: 'json' }
import formula4 from '../../tables/workshop/formulas/utility/enemy-attack-level-skip.json' with { type: 'json' }
import formula5 from '../../tables/workshop/formulas/utility/enemy-health-level-skip.json' with { type: 'json' }
import formula6 from '../../tables/workshop/formulas/utility/free-attack-upgrade.json' with { type: 'json' }
import formula7 from '../../tables/workshop/formulas/utility/free-defense-upgrade.json' with { type: 'json' }
import formula8 from '../../tables/workshop/formulas/utility/free-utility-upgrade.json' with { type: 'json' }
import formula9 from '../../tables/workshop/formulas/utility/interest-wave.json' with { type: 'json' }
import formula10 from '../../tables/workshop/formulas/utility/max-recovery.json' with { type: 'json' }
import formula11 from '../../tables/workshop/formulas/utility/package-chance.json' with { type: 'json' }
import formula12 from '../../tables/workshop/formulas/utility/recovery-amount.json' with { type: 'json' }

export const WORKSHOP_FORMULA_COUNT = 13

const workshopFormulaByKey: Record<string, WorkshopFormulaSpec> = {
  'cashBonusLevel': formula0 as WorkshopFormulaSpec,
  'cashPerWaveLevel': formula1 as WorkshopFormulaSpec,
  'coinsKillBonusLevel': formula2 as WorkshopFormulaSpec,
  'coinsWaveLevel': formula3 as WorkshopFormulaSpec,
  'enemyAttackLevelSkipLevel': formula4 as WorkshopFormulaSpec,
  'enemyHealthLevelSkipLevel': formula5 as WorkshopFormulaSpec,
  'freeAttackUpgradeLevel': formula6 as WorkshopFormulaSpec,
  'freeDefenseUpgradeLevel': formula7 as WorkshopFormulaSpec,
  'freeUtilityUpgradeLevel': formula8 as WorkshopFormulaSpec,
  'interestPerWaveLevel': formula9 as WorkshopFormulaSpec,
  'maxRecoveryLevel': formula10 as WorkshopFormulaSpec,
  'packageChanceLevel': formula11 as WorkshopFormulaSpec,
  'recoveryAmountLevel': formula12 as WorkshopFormulaSpec,
}

export function getWorkshopFormulaSpec(workshopKey: string): WorkshopFormulaSpec | undefined {
  return workshopFormulaByKey[workshopKey]
}

export function getWorkshopFormulaSpecs(): Readonly<Record<string, WorkshopFormulaSpec>> {
  return workshopFormulaByKey
}
