/**
 * Game `ModuleManager.effects` index → workshop sub-module effect pick.
 * Generated by `scripts/gen-game-module-effect-index.mjs` from wiki submodule tables.
 */

import type { WorkshopChassisModuleMergeTier } from '../data/workshopChassisModuleShared'
import { workshopChassisModuleEffectTier } from '../data/workshopChassisModuleShared'
import type { WorkshopAssistModuleSlot } from '../data/workshopSimModules'
import type { WorkshopSubmoduleRarity } from '../data/workshopSubmoduleEffects'
import { WORKSHOP_SUBMODULE_SLOT_COUNT } from '../data/workshopSubmoduleCatalog'
import type {
  WorkshopSubmoduleOrderedSlots,
  WorkshopSubmoduleSelectionMap,
} from '../data/workshopSubmoduleSelection'

export type GameModuleEffectDecode = {
  slot: WorkshopAssistModuleSlot
  effectId: string
  rarity: WorkshopSubmoduleRarity
}

export const GAME_MODULE_EFFECT_COUNT = 330 as const

/** Save effect index → decoded pick (`null` if out of range). Index 0 is Attack Speed common. */
export const GAME_MODULE_EFFECT_BY_INDEX: readonly GameModuleEffectDecode[] = [
  { slot: "cannon", effectId: "attack-speed", rarity: "common" }, // 0
  { slot: "cannon", effectId: "attack-speed", rarity: "common" }, // 1
  { slot: "cannon", effectId: "attack-speed", rarity: "rare" }, // 2
  { slot: "cannon", effectId: "attack-speed", rarity: "epic" }, // 3
  { slot: "cannon", effectId: "attack-speed", rarity: "legendary" }, // 4
  { slot: "cannon", effectId: "attack-speed", rarity: "mythic" }, // 5
  { slot: "cannon", effectId: "crit-chance", rarity: "common" }, // 6
  { slot: "cannon", effectId: "crit-chance", rarity: "common" }, // 7
  { slot: "cannon", effectId: "crit-chance", rarity: "rare" }, // 8
  { slot: "cannon", effectId: "crit-chance", rarity: "epic" }, // 9
  { slot: "cannon", effectId: "crit-chance", rarity: "legendary" }, // 10
  { slot: "cannon", effectId: "crit-chance", rarity: "mythic" }, // 11
  { slot: "cannon", effectId: "crit-factor", rarity: "common" }, // 12
  { slot: "cannon", effectId: "crit-factor", rarity: "common" }, // 13
  { slot: "cannon", effectId: "crit-factor", rarity: "rare" }, // 14
  { slot: "cannon", effectId: "crit-factor", rarity: "epic" }, // 15
  { slot: "cannon", effectId: "crit-factor", rarity: "legendary" }, // 16
  { slot: "cannon", effectId: "crit-factor", rarity: "mythic" }, // 17
  { slot: "cannon", effectId: "attack-range-m", rarity: "common" }, // 18
  { slot: "cannon", effectId: "attack-range-m", rarity: "common" }, // 19
  { slot: "cannon", effectId: "attack-range-m", rarity: "rare" }, // 20
  { slot: "cannon", effectId: "attack-range-m", rarity: "epic" }, // 21
  { slot: "cannon", effectId: "attack-range-m", rarity: "legendary" }, // 22
  { slot: "cannon", effectId: "attack-range-m", rarity: "mythic" }, // 23
  { slot: "cannon", effectId: "damage-meter-m", rarity: "common" }, // 24
  { slot: "cannon", effectId: "damage-meter-m", rarity: "common" }, // 25
  { slot: "cannon", effectId: "damage-meter-m", rarity: "rare" }, // 26
  { slot: "cannon", effectId: "damage-meter-m", rarity: "epic" }, // 27
  { slot: "cannon", effectId: "damage-meter-m", rarity: "legendary" }, // 28
  { slot: "cannon", effectId: "damage-meter-m", rarity: "mythic" }, // 29
  { slot: "cannon", effectId: "multishot-chance", rarity: "rare" }, // 30
  { slot: "cannon", effectId: "multishot-chance", rarity: "epic" }, // 31
  { slot: "cannon", effectId: "multishot-chance", rarity: "legendary" }, // 32
  { slot: "cannon", effectId: "multishot-chance", rarity: "legendary" }, // 33
  { slot: "cannon", effectId: "multishot-chance", rarity: "mythic" }, // 34
  { slot: "cannon", effectId: "multishot-targets", rarity: "epic" }, // 35
  { slot: "cannon", effectId: "multishot-targets", rarity: "legendary" }, // 36
  { slot: "cannon", effectId: "multishot-targets", rarity: "legendary" }, // 37
  { slot: "cannon", effectId: "multishot-targets", rarity: "mythic" }, // 38
  { slot: "cannon", effectId: "rapid-fire-chance", rarity: "rare" }, // 39
  { slot: "cannon", effectId: "rapid-fire-chance", rarity: "epic" }, // 40
  { slot: "cannon", effectId: "rapid-fire-chance", rarity: "legendary" }, // 41
  { slot: "cannon", effectId: "rapid-fire-chance", rarity: "legendary" }, // 42
  { slot: "cannon", effectId: "rapid-fire-chance", rarity: "mythic" }, // 43
  { slot: "cannon", effectId: "rapid-fire-duration", rarity: "rare" }, // 44
  { slot: "cannon", effectId: "rapid-fire-duration", rarity: "epic" }, // 45
  { slot: "cannon", effectId: "rapid-fire-duration", rarity: "legendary" }, // 46
  { slot: "cannon", effectId: "rapid-fire-duration", rarity: "legendary" }, // 47
  { slot: "cannon", effectId: "rapid-fire-duration", rarity: "mythic" }, // 48
  { slot: "cannon", effectId: "bounce-shot-chance", rarity: "rare" }, // 49
  { slot: "cannon", effectId: "bounce-shot-chance", rarity: "epic" }, // 50
  { slot: "cannon", effectId: "bounce-shot-chance", rarity: "legendary" }, // 51
  { slot: "cannon", effectId: "bounce-shot-chance", rarity: "legendary" }, // 52
  { slot: "cannon", effectId: "bounce-shot-chance", rarity: "mythic" }, // 53
  { slot: "cannon", effectId: "bounce-shot-targets", rarity: "epic" }, // 54
  { slot: "cannon", effectId: "bounce-shot-targets", rarity: "legendary" }, // 55
  { slot: "cannon", effectId: "bounce-shot-targets", rarity: "legendary" }, // 56
  { slot: "cannon", effectId: "bounce-shot-targets", rarity: "mythic" }, // 57
  { slot: "cannon", effectId: "bounce-shot-range", rarity: "rare" }, // 58
  { slot: "cannon", effectId: "bounce-shot-range", rarity: "epic" }, // 59
  { slot: "cannon", effectId: "bounce-shot-range", rarity: "legendary" }, // 60
  { slot: "cannon", effectId: "bounce-shot-range", rarity: "legendary" }, // 61
  { slot: "cannon", effectId: "bounce-shot-range", rarity: "mythic" }, // 62
  { slot: "cannon", effectId: "super-crit-chance", rarity: "epic" }, // 63
  { slot: "cannon", effectId: "super-crit-chance", rarity: "legendary" }, // 64
  { slot: "cannon", effectId: "super-crit-chance", rarity: "legendary" }, // 65
  { slot: "cannon", effectId: "super-crit-chance", rarity: "mythic" }, // 66
  { slot: "cannon", effectId: "super-crit-multi", rarity: "epic" }, // 67
  { slot: "cannon", effectId: "super-crit-multi", rarity: "legendary" }, // 68
  { slot: "cannon", effectId: "super-crit-multi", rarity: "legendary" }, // 69
  { slot: "cannon", effectId: "super-crit-multi", rarity: "mythic" }, // 70
  { slot: "cannon", effectId: "rend-armor-chance", rarity: "legendary" }, // 71
  { slot: "cannon", effectId: "rend-armor-chance", rarity: "legendary" }, // 72
  { slot: "cannon", effectId: "rend-armor-chance", rarity: "mythic" }, // 73
  { slot: "cannon", effectId: "rend-armor-multi", rarity: "legendary" }, // 74
  { slot: "cannon", effectId: "rend-armor-multi", rarity: "legendary" }, // 75
  { slot: "cannon", effectId: "rend-armor-multi", rarity: "mythic" }, // 76
  { slot: "cannon", effectId: "max-rend-armor-multi", rarity: "legendary" }, // 77
  { slot: "cannon", effectId: "max-rend-armor-multi", rarity: "legendary" }, // 78
  { slot: "cannon", effectId: "max-rend-armor-multi", rarity: "mythic" }, // 79
  { slot: "armor", effectId: "health-regen", rarity: "common" }, // 80
  { slot: "armor", effectId: "health-regen", rarity: "common" }, // 81
  { slot: "armor", effectId: "health-regen", rarity: "rare" }, // 82
  { slot: "armor", effectId: "health-regen", rarity: "epic" }, // 83
  { slot: "armor", effectId: "health-regen", rarity: "legendary" }, // 84
  { slot: "armor", effectId: "health-regen", rarity: "mythic" }, // 85
  { slot: "armor", effectId: "defense", rarity: "common" }, // 86
  { slot: "armor", effectId: "defense", rarity: "common" }, // 87
  { slot: "armor", effectId: "defense", rarity: "rare" }, // 88
  { slot: "armor", effectId: "defense", rarity: "epic" }, // 89
  { slot: "armor", effectId: "defense", rarity: "legendary" }, // 90
  { slot: "armor", effectId: "defense", rarity: "mythic" }, // 91
  { slot: "armor", effectId: "defense-absolute", rarity: "common" }, // 92
  { slot: "armor", effectId: "defense-absolute", rarity: "common" }, // 93
  { slot: "armor", effectId: "defense-absolute", rarity: "rare" }, // 94
  { slot: "armor", effectId: "defense-absolute", rarity: "epic" }, // 95
  { slot: "armor", effectId: "defense-absolute", rarity: "legendary" }, // 96
  { slot: "armor", effectId: "defense-absolute", rarity: "mythic" }, // 97
  { slot: "armor", effectId: "thorns-damage", rarity: "epic" }, // 98
  { slot: "armor", effectId: "thorns-damage", rarity: "legendary" }, // 99
  { slot: "armor", effectId: "thorns-damage", rarity: "legendary" }, // 100
  { slot: "armor", effectId: "thorns-damage", rarity: "mythic" }, // 101
  { slot: "armor", effectId: "lifesteal", rarity: "epic" }, // 102
  { slot: "armor", effectId: "lifesteal", rarity: "legendary" }, // 103
  { slot: "armor", effectId: "lifesteal", rarity: "legendary" }, // 104
  { slot: "armor", effectId: "lifesteal", rarity: "mythic" }, // 105
  { slot: "armor", effectId: "knockback-chance", rarity: "epic" }, // 106
  { slot: "armor", effectId: "knockback-chance", rarity: "legendary" }, // 107
  { slot: "armor", effectId: "knockback-chance", rarity: "legendary" }, // 108
  { slot: "armor", effectId: "knockback-chance", rarity: "mythic" }, // 109
  { slot: "armor", effectId: "knockback-force", rarity: "epic" }, // 110
  { slot: "armor", effectId: "knockback-force", rarity: "legendary" }, // 111
  { slot: "armor", effectId: "knockback-force", rarity: "legendary" }, // 112
  { slot: "armor", effectId: "knockback-force", rarity: "mythic" }, // 113
  { slot: "armor", effectId: "orb-speed", rarity: "epic" }, // 114
  { slot: "armor", effectId: "orb-speed", rarity: "legendary" }, // 115
  { slot: "armor", effectId: "orb-speed", rarity: "legendary" }, // 116
  { slot: "armor", effectId: "orb-speed", rarity: "mythic" }, // 117
  { slot: "armor", effectId: "orbs", rarity: "mythic" }, // 118
  { slot: "armor", effectId: "orbs", rarity: "ancestral" }, // 119
  { slot: "armor", effectId: "shockwave-size", rarity: "epic" }, // 120
  { slot: "armor", effectId: "shockwave-size", rarity: "legendary" }, // 121
  { slot: "armor", effectId: "shockwave-size", rarity: "legendary" }, // 122
  { slot: "armor", effectId: "shockwave-size", rarity: "mythic" }, // 123
  { slot: "armor", effectId: "shockwave-frequency-s", rarity: "epic" }, // 124
  { slot: "armor", effectId: "shockwave-frequency-s", rarity: "legendary" }, // 125
  { slot: "armor", effectId: "shockwave-frequency-s", rarity: "legendary" }, // 126
  { slot: "armor", effectId: "shockwave-frequency-s", rarity: "mythic" }, // 127
  { slot: "armor", effectId: "land-mine-chance", rarity: "rare" }, // 128
  { slot: "armor", effectId: "land-mine-chance", rarity: "epic" }, // 129
  { slot: "armor", effectId: "land-mine-chance", rarity: "legendary" }, // 130
  { slot: "armor", effectId: "land-mine-chance", rarity: "legendary" }, // 131
  { slot: "armor", effectId: "land-mine-chance", rarity: "mythic" }, // 132
  { slot: "armor", effectId: "land-mine-damage", rarity: "rare" }, // 133
  { slot: "armor", effectId: "land-mine-damage", rarity: "epic" }, // 134
  { slot: "armor", effectId: "land-mine-damage", rarity: "legendary" }, // 135
  { slot: "armor", effectId: "land-mine-damage", rarity: "legendary" }, // 136
  { slot: "armor", effectId: "land-mine-damage", rarity: "mythic" }, // 137
  { slot: "armor", effectId: "land-mine-radius", rarity: "rare" }, // 138
  { slot: "armor", effectId: "land-mine-radius", rarity: "epic" }, // 139
  { slot: "armor", effectId: "land-mine-radius", rarity: "legendary" }, // 140
  { slot: "armor", effectId: "land-mine-radius", rarity: "legendary" }, // 141
  { slot: "armor", effectId: "land-mine-radius", rarity: "mythic" }, // 142
  { slot: "armor", effectId: "death-defy", rarity: "legendary" }, // 143
  { slot: "armor", effectId: "death-defy", rarity: "legendary" }, // 144
  { slot: "armor", effectId: "death-defy", rarity: "mythic" }, // 145
  { slot: "armor", effectId: "wall-health", rarity: "epic" }, // 146
  { slot: "armor", effectId: "wall-health", rarity: "legendary" }, // 147
  { slot: "armor", effectId: "wall-health", rarity: "legendary" }, // 148
  { slot: "armor", effectId: "wall-health", rarity: "mythic" }, // 149
  { slot: "armor", effectId: "wall-rebuild-s", rarity: "epic" }, // 150
  { slot: "armor", effectId: "wall-rebuild-s", rarity: "legendary" }, // 151
  { slot: "armor", effectId: "wall-rebuild-s", rarity: "legendary" }, // 152
  { slot: "armor", effectId: "wall-rebuild-s", rarity: "mythic" }, // 153
  { slot: "generator", effectId: "cash-bonus", rarity: "common" }, // 154
  { slot: "generator", effectId: "cash-bonus", rarity: "common" }, // 155
  { slot: "generator", effectId: "cash-bonus", rarity: "rare" }, // 156
  { slot: "generator", effectId: "cash-bonus", rarity: "epic" }, // 157
  { slot: "generator", effectId: "cash-bonus", rarity: "legendary" }, // 158
  { slot: "generator", effectId: "cash-bonus", rarity: "mythic" }, // 159
  { slot: "generator", effectId: "cash-wave", rarity: "common" }, // 160
  { slot: "generator", effectId: "cash-wave", rarity: "common" }, // 161
  { slot: "generator", effectId: "cash-wave", rarity: "rare" }, // 162
  { slot: "generator", effectId: "cash-wave", rarity: "epic" }, // 163
  { slot: "generator", effectId: "cash-wave", rarity: "legendary" }, // 164
  { slot: "generator", effectId: "cash-wave", rarity: "mythic" }, // 165
  { slot: "generator", effectId: "coins-kill-bonus", rarity: "common" }, // 166
  { slot: "generator", effectId: "coins-kill-bonus", rarity: "common" }, // 167
  { slot: "generator", effectId: "coins-kill-bonus", rarity: "rare" }, // 168
  { slot: "generator", effectId: "coins-kill-bonus", rarity: "epic" }, // 169
  { slot: "generator", effectId: "coins-kill-bonus", rarity: "legendary" }, // 170
  { slot: "generator", effectId: "coins-kill-bonus", rarity: "mythic" }, // 171
  { slot: "generator", effectId: "coins-wave", rarity: "common" }, // 172
  { slot: "generator", effectId: "coins-wave", rarity: "common" }, // 173
  { slot: "generator", effectId: "coins-wave", rarity: "rare" }, // 174
  { slot: "generator", effectId: "coins-wave", rarity: "epic" }, // 175
  { slot: "generator", effectId: "coins-wave", rarity: "legendary" }, // 176
  { slot: "generator", effectId: "coins-wave", rarity: "mythic" }, // 177
  { slot: "generator", effectId: "free-attack-upgrade", rarity: "common" }, // 178
  { slot: "generator", effectId: "free-attack-upgrade", rarity: "common" }, // 179
  { slot: "generator", effectId: "free-attack-upgrade", rarity: "rare" }, // 180
  { slot: "generator", effectId: "free-attack-upgrade", rarity: "epic" }, // 181
  { slot: "generator", effectId: "free-attack-upgrade", rarity: "legendary" }, // 182
  { slot: "generator", effectId: "free-attack-upgrade", rarity: "mythic" }, // 183
  { slot: "generator", effectId: "free-defense-upgrade", rarity: "common" }, // 184
  { slot: "generator", effectId: "free-defense-upgrade", rarity: "common" }, // 185
  { slot: "generator", effectId: "free-defense-upgrade", rarity: "rare" }, // 186
  { slot: "generator", effectId: "free-defense-upgrade", rarity: "epic" }, // 187
  { slot: "generator", effectId: "free-defense-upgrade", rarity: "legendary" }, // 188
  { slot: "generator", effectId: "free-defense-upgrade", rarity: "mythic" }, // 189
  { slot: "generator", effectId: "free-utility-upgrade", rarity: "common" }, // 190
  { slot: "generator", effectId: "free-utility-upgrade", rarity: "common" }, // 191
  { slot: "generator", effectId: "free-utility-upgrade", rarity: "rare" }, // 192
  { slot: "generator", effectId: "free-utility-upgrade", rarity: "epic" }, // 193
  { slot: "generator", effectId: "free-utility-upgrade", rarity: "legendary" }, // 194
  { slot: "generator", effectId: "free-utility-upgrade", rarity: "mythic" }, // 195
  { slot: "generator", effectId: "interest-wave", rarity: "epic" }, // 196
  { slot: "generator", effectId: "interest-wave", rarity: "legendary" }, // 197
  { slot: "generator", effectId: "interest-wave", rarity: "legendary" }, // 198
  { slot: "generator", effectId: "interest-wave", rarity: "mythic" }, // 199
  { slot: "generator", effectId: "recovery-amount", rarity: "epic" }, // 200
  { slot: "generator", effectId: "recovery-amount", rarity: "legendary" }, // 201
  { slot: "generator", effectId: "recovery-amount", rarity: "legendary" }, // 202
  { slot: "generator", effectId: "recovery-amount", rarity: "mythic" }, // 203
  { slot: "generator", effectId: "max-recovery", rarity: "epic" }, // 204
  { slot: "generator", effectId: "max-recovery", rarity: "legendary" }, // 205
  { slot: "generator", effectId: "max-recovery", rarity: "legendary" }, // 206
  { slot: "generator", effectId: "max-recovery", rarity: "mythic" }, // 207
  { slot: "generator", effectId: "package-chance", rarity: "epic" }, // 208
  { slot: "generator", effectId: "package-chance", rarity: "legendary" }, // 209
  { slot: "generator", effectId: "package-chance", rarity: "mythic" }, // 210
  { slot: "generator", effectId: "package-chance", rarity: "ancestral" }, // 211
  { slot: "generator", effectId: "enemy-attack-level-skip", rarity: "epic" }, // 212
  { slot: "generator", effectId: "enemy-attack-level-skip", rarity: "legendary" }, // 213
  { slot: "generator", effectId: "enemy-attack-level-skip", rarity: "mythic" }, // 214
  { slot: "generator", effectId: "enemy-attack-level-skip", rarity: "ancestral" }, // 215
  { slot: "generator", effectId: "enemy-health-level-skip", rarity: "epic" }, // 216
  { slot: "generator", effectId: "enemy-health-level-skip", rarity: "legendary" }, // 217
  { slot: "generator", effectId: "enemy-health-level-skip", rarity: "mythic" }, // 218
  { slot: "generator", effectId: "enemy-health-level-skip", rarity: "ancestral" }, // 219
  { slot: "core", effectId: "chain-lightning-damage-x", rarity: "legendary" }, // 220
  { slot: "core", effectId: "chain-lightning-damage-x", rarity: "mythic" }, // 221
  { slot: "core", effectId: "chain-lightning-damage-x", rarity: "ancestral" }, // 222
  { slot: "core", effectId: "chain-lightning-damage-x", rarity: "epic" }, // 223
  { slot: "core", effectId: "chain-lightning-damage-x", rarity: "legendary" }, // 224
  { slot: "core", effectId: "chain-lightning-damage-x", rarity: "mythic" }, // 225
  { slot: "core", effectId: "chain-lightning-quantity", rarity: "epic" }, // 226
  { slot: "core", effectId: "chain-lightning-quantity", rarity: "legendary" }, // 227
  { slot: "core", effectId: "chain-lightning-quantity", rarity: "legendary" }, // 228
  { slot: "core", effectId: "chain-lightning-quantity", rarity: "mythic" }, // 229
  { slot: "core", effectId: "chain-lightning-chance", rarity: "legendary" }, // 230
  { slot: "core", effectId: "chain-lightning-chance", rarity: "mythic" }, // 231
  { slot: "core", effectId: "chain-lightning-chance", rarity: "ancestral" }, // 232
  { slot: "core", effectId: "chain-lightning-chance", rarity: "epic" }, // 233
  { slot: "core", effectId: "chain-lightning-chance", rarity: "legendary" }, // 234
  { slot: "core", effectId: "chain-lightning-chance", rarity: "mythic" }, // 235
  { slot: "core", effectId: "smart-missiles-damage", rarity: "legendary" }, // 236
  { slot: "core", effectId: "smart-missiles-damage", rarity: "mythic" }, // 237
  { slot: "core", effectId: "smart-missiles-damage", rarity: "ancestral" }, // 238
  { slot: "core", effectId: "smart-missiles-damage", rarity: "epic" }, // 239
  { slot: "core", effectId: "smart-missiles-damage", rarity: "legendary" }, // 240
  { slot: "core", effectId: "smart-missiles-damage", rarity: "mythic" }, // 241
  { slot: "core", effectId: "smart-missiles-quantity", rarity: "epic" }, // 242
  { slot: "core", effectId: "smart-missiles-quantity", rarity: "legendary" }, // 243
  { slot: "core", effectId: "smart-missiles-quantity", rarity: "legendary" }, // 244
  { slot: "core", effectId: "smart-missiles-quantity", rarity: "mythic" }, // 245
  { slot: "core", effectId: "death-wave-damage-x", rarity: "legendary" }, // 246
  { slot: "core", effectId: "death-wave-damage-x", rarity: "mythic" }, // 247
  { slot: "core", effectId: "death-wave-damage-x", rarity: "ancestral" }, // 248
  { slot: "core", effectId: "death-wave-damage-x", rarity: "epic" }, // 249
  { slot: "core", effectId: "death-wave-damage-x", rarity: "legendary" }, // 250
  { slot: "core", effectId: "death-wave-damage-x", rarity: "mythic" }, // 251
  { slot: "core", effectId: "death-wave-quantity", rarity: "legendary" }, // 252
  { slot: "core", effectId: "death-wave-quantity", rarity: "legendary" }, // 253
  { slot: "core", effectId: "death-wave-quantity", rarity: "mythic" }, // 254
  { slot: "core", effectId: "smart-missiles-cooldown-s", rarity: "legendary" }, // 255
  { slot: "core", effectId: "smart-missiles-cooldown-s", rarity: "legendary" }, // 256
  { slot: "core", effectId: "smart-missiles-cooldown-s", rarity: "mythic" }, // 257
  { slot: "core", effectId: "death-wave-cooldown-s", rarity: "legendary" }, // 258
  { slot: "core", effectId: "death-wave-cooldown-s", rarity: "legendary" }, // 259
  { slot: "core", effectId: "death-wave-cooldown-s", rarity: "mythic" }, // 260
  { slot: "core", effectId: "chrono-field-duration-s", rarity: "legendary" }, // 261
  { slot: "core", effectId: "chrono-field-duration-s", rarity: "legendary" }, // 262
  { slot: "core", effectId: "chrono-field-duration-s", rarity: "mythic" }, // 263
  { slot: "core", effectId: "chrono-field-speed-reduction", rarity: "epic" }, // 264
  { slot: "core", effectId: "chrono-field-speed-reduction", rarity: "legendary" }, // 265
  { slot: "core", effectId: "chrono-field-speed-reduction", rarity: "legendary" }, // 266
  { slot: "core", effectId: "chrono-field-speed-reduction", rarity: "mythic" }, // 267
  { slot: "core", effectId: "chrono-field-cooldown-s", rarity: "legendary" }, // 268
  { slot: "core", effectId: "chrono-field-cooldown-s", rarity: "legendary" }, // 269
  { slot: "core", effectId: "chrono-field-cooldown-s", rarity: "mythic" }, // 270
  { slot: "core", effectId: "inner-land-mines-damage-x", rarity: "legendary" }, // 271
  { slot: "core", effectId: "inner-land-mines-damage-x", rarity: "mythic" }, // 272
  { slot: "core", effectId: "inner-land-mines-damage-x", rarity: "ancestral" }, // 273
  { slot: "core", effectId: "inner-land-mines-damage-x", rarity: "epic" }, // 274
  { slot: "core", effectId: "inner-land-mines-damage-x", rarity: "legendary" }, // 275
  { slot: "core", effectId: "inner-land-mines-damage-x", rarity: "mythic" }, // 276
  { slot: "core", effectId: "inner-land-mines-quantity", rarity: "legendary" }, // 277
  { slot: "core", effectId: "inner-land-mines-quantity", rarity: "legendary" }, // 278
  { slot: "core", effectId: "inner-land-mines-quantity", rarity: "mythic" }, // 279
  { slot: "core", effectId: "golden-tower-bonus", rarity: "epic" }, // 280
  { slot: "core", effectId: "golden-tower-bonus", rarity: "legendary" }, // 281
  { slot: "core", effectId: "golden-tower-bonus", rarity: "legendary" }, // 282
  { slot: "core", effectId: "golden-tower-bonus", rarity: "mythic" }, // 283
  { slot: "core", effectId: "inner-land-mines-cooldown-s", rarity: "epic" }, // 284
  { slot: "core", effectId: "inner-land-mines-cooldown-s", rarity: "legendary" }, // 285
  { slot: "core", effectId: "inner-land-mines-cooldown-s", rarity: "legendary" }, // 286
  { slot: "core", effectId: "inner-land-mines-cooldown-s", rarity: "mythic" }, // 287
  { slot: "core", effectId: "golden-tower-duration-s", rarity: "legendary" }, // 288
  { slot: "core", effectId: "golden-tower-duration-s", rarity: "legendary" }, // 289
  { slot: "core", effectId: "golden-tower-duration-s", rarity: "mythic" }, // 290
  { slot: "core", effectId: "golden-tower-cooldown-s", rarity: "legendary" }, // 291
  { slot: "core", effectId: "golden-tower-cooldown-s", rarity: "legendary" }, // 292
  { slot: "core", effectId: "golden-tower-cooldown-s", rarity: "mythic" }, // 293
  { slot: "core", effectId: "poison-swamp-damage-x", rarity: "legendary" }, // 294
  { slot: "core", effectId: "poison-swamp-damage-x", rarity: "mythic" }, // 295
  { slot: "core", effectId: "poison-swamp-damage-x", rarity: "ancestral" }, // 296
  { slot: "core", effectId: "poison-swamp-damage-x", rarity: "epic" }, // 297
  { slot: "core", effectId: "poison-swamp-damage-x", rarity: "legendary" }, // 298
  { slot: "core", effectId: "poison-swamp-damage-x", rarity: "mythic" }, // 299
  { slot: "core", effectId: "poison-swamp-duration-s", rarity: "legendary" }, // 300
  { slot: "core", effectId: "poison-swamp-duration-s", rarity: "legendary" }, // 301
  { slot: "core", effectId: "poison-swamp-duration-s", rarity: "mythic" }, // 302
  { slot: "core", effectId: "poison-swamp-cooldown-s", rarity: "rare" }, // 303
  { slot: "core", effectId: "poison-swamp-cooldown-s", rarity: "epic" }, // 304
  { slot: "core", effectId: "poison-swamp-cooldown-s", rarity: "legendary" }, // 305
  { slot: "core", effectId: "poison-swamp-cooldown-s", rarity: "legendary" }, // 306
  { slot: "core", effectId: "poison-swamp-cooldown-s", rarity: "mythic" }, // 307
  { slot: "core", effectId: "black-hole-cooldown-s", rarity: "legendary" }, // 308
  { slot: "core", effectId: "black-hole-cooldown-s", rarity: "legendary" }, // 309
  { slot: "core", effectId: "black-hole-cooldown-s", rarity: "mythic" }, // 310
  { slot: "core", effectId: "black-hole-duration-s", rarity: "legendary" }, // 311
  { slot: "core", effectId: "black-hole-duration-s", rarity: "legendary" }, // 312
  { slot: "core", effectId: "black-hole-duration-s", rarity: "mythic" }, // 313
  { slot: "core", effectId: "black-hole-size-m", rarity: "legendary" }, // 314
  { slot: "core", effectId: "black-hole-size-m", rarity: "mythic" }, // 315
  { slot: "core", effectId: "black-hole-size-m", rarity: "ancestral" }, // 316
  { slot: "core", effectId: "black-hole-size-m", rarity: "epic" }, // 317
  { slot: "core", effectId: "black-hole-size-m", rarity: "legendary" }, // 318
  { slot: "core", effectId: "black-hole-size-m", rarity: "mythic" }, // 319
  { slot: "core", effectId: "spotlight-bonus", rarity: "legendary" }, // 320
  { slot: "core", effectId: "spotlight-bonus", rarity: "mythic" }, // 321
  { slot: "core", effectId: "spotlight-bonus", rarity: "ancestral" }, // 322
  { slot: "core", effectId: "spotlight-bonus", rarity: "epic" }, // 323
  { slot: "core", effectId: "spotlight-bonus", rarity: "legendary" }, // 324
  { slot: "core", effectId: "spotlight-bonus", rarity: "mythic" }, // 325
  { slot: "core", effectId: "spotlight-angle", rarity: "epic" }, // 326
  { slot: "core", effectId: "spotlight-angle", rarity: "legendary" }, // 327
  { slot: "core", effectId: "spotlight-angle", rarity: "legendary" }, // 328
  { slot: "core", effectId: "spotlight-angle", rarity: "mythic" }, // 329
] as const

export function gameModuleEffectByIndex(
  index: number,
  moduleLevel = 0,
): GameModuleEffectDecode | null {
  if (!Number.isFinite(index) || index < 0) return null
  let i = Math.trunc(index)
  const level = Number.isFinite(moduleLevel) ? Math.max(0, Math.trunc(moduleLevel)) : 0
  // High-level modules store sparseIndex + level when that sum reaches the table size (330).
  if (i >= GAME_MODULE_EFFECT_COUNT && level > 0) {
    i -= level
  }
  if (i < 0 || i >= GAME_MODULE_EFFECT_COUNT) return null
  return GAME_MODULE_EFFECT_BY_INDEX[i] ?? null
}

/** Decode save effect index for a chassis slot (assist may use primary module level offset). */
export function gameModuleEffectByIndexForSlot(
  index: number,
  slot: WorkshopAssistModuleSlot,
  moduleLevel = 0,
  primaryModuleLevel = 0,
): GameModuleEffectDecode | null {
  const matchSlot = (decoded: GameModuleEffectDecode | null): GameModuleEffectDecode | null =>
    decoded != null && decoded.slot === slot ? decoded : null

  const direct = matchSlot(gameModuleEffectByIndex(index, moduleLevel))
  if (direct != null) return direct

  const primaryLevel = Number.isFinite(primaryModuleLevel)
    ? Math.max(0, Math.trunc(primaryModuleLevel))
    : 0
  if (primaryLevel > 0) {
    return matchSlot(gameModuleEffectByIndex(index - primaryLevel, 0))
  }
  return null
}

function decodeGeneratorEffectAtIndex(
  index: number,
  moduleLevel: number,
): GameModuleEffectDecode | null {
  const decoded = gameModuleEffectByIndex(index, moduleLevel)
  return decoded != null && decoded.slot === 'generator' ? decoded : null
}

function isAncestralFamilyChassisMerge(
  chassisMerge?: WorkshopChassisModuleMergeTier | null,
): boolean {
  return (
    chassisMerge != null && workshopChassisModuleEffectTier(chassisMerge) === 'ancestral'
  )
}

/** Mythic / Mythic+ / ancestral-family core modules store sparse indices needing row remaps. */
function isHighTierCoreChassisMerge(
  chassisMerge?: WorkshopChassisModuleMergeTier | null,
): boolean {
  if (chassisMerge == null) return false
  const tier = workshopChassisModuleEffectTier(chassisMerge)
  return tier === 'mythic' || tier === 'ancestral'
}

/** Mythic+ / ancestral-family chassis use sparse generator indices stored as actual − 3. */
function isHighTierGeneratorChassisMerge(
  chassisMerge?: WorkshopChassisModuleMergeTier | null,
): boolean {
  if (chassisMerge == null) return false
  const tier = workshopChassisModuleEffectTier(chassisMerge)
  return tier === 'mythic' || tier === 'ancestral'
}

function decodeGeneratorSparsePlusThree(
  rawIndex: number,
  moduleLevel: number,
  primaryModuleLevel: number,
  naive: GameModuleEffectDecode | null,
): GameModuleEffectDecode | null {
  if (rawIndex + 3 >= GAME_MODULE_EFFECT_COUNT) return null
  const bumped =
    decodeGeneratorEffectAtIndex(rawIndex + 3, moduleLevel) ??
    decodeGeneratorEffectAtIndex(rawIndex + 3, 0)
  if (bumped == null) return null
  if (bumped.rarity !== 'mythic' && bumped.rarity !== 'ancestral') return null
  if (naive != null && bumped.effectId === naive.effectId) {
    if (bumped.rarity === 'ancestral' && naive.rarity === 'epic') return bumped
    return null
  }
  const primaryLevel = Math.max(0, Math.trunc(primaryModuleLevel))
  const level = Math.max(0, Math.trunc(moduleLevel))
  if (bumped.effectId !== naive?.effectId) {
    if (primaryLevel > level) return bumped
    if (primaryLevel === 0 && level >= 130) return bumped
  }
  return null
}

/** Common-start armor rows use sparse offset 6 for Ancestral on ancestral-family chassis. */
const ARMOR_COMMON_START_ANCESTRAL_ROWS: readonly {
  base: number
  effectId: string
}[] = [
  { base: 80, effectId: 'health-regen' },
  { base: 86, effectId: 'defense' },
  { base: 92, effectId: 'defense-absolute' },
]

function decodeArmorAncestralCommonStartRow(
  rawIndex: number,
): GameModuleEffectDecode | null {
  for (const { base, effectId } of ARMOR_COMMON_START_ANCESTRAL_ROWS) {
    if (rawIndex - base === 6) {
      return { slot: 'armor', effectId, rarity: 'ancestral' }
    }
  }
  return null
}

function decodeArmorLandMineRadiusOnAncestralChassis(
  rawIndex: number,
  decoded: GameModuleEffectDecode,
): GameModuleEffectDecode | null {
  if (decoded.effectId !== 'land-mine-radius' || decoded.rarity !== 'epic') {
    return null
  }
  const shifted = gameModuleEffectByIndex(rawIndex - 1)
  if (shifted?.effectId === 'land-mine-radius' && shifted.rarity === 'rare') {
    return shifted
  }
  return null
}

type CoreRowSpan = { start: number; end: number; effectId: string }

function buildCoreRowSpans(): CoreRowSpan[] {
  const spans: CoreRowSpan[] = []
  let i = GAME_MODULE_EFFECT_BY_INDEX.findIndex((entry) => entry.slot === 'core')
  if (i < 0) return spans
  while (i < GAME_MODULE_EFFECT_COUNT) {
    const entry = GAME_MODULE_EFFECT_BY_INDEX[i]
    if (entry?.slot !== 'core') break
    const effectId = entry.effectId
    let j = i + 1
    while (j < GAME_MODULE_EFFECT_COUNT && GAME_MODULE_EFFECT_BY_INDEX[j]?.effectId === effectId) {
      j++
    }
    spans.push({ start: i, end: j, effectId })
    i = j
  }
  return spans
}

const CORE_ROW_SPANS = buildCoreRowSpans()

/** Ancestral main core: block-2 tier in row N maps to same tier in paired follow-on row. */
const CORE_ANCESTRAL_FORWARD_ROW: Readonly<Record<string, string>> = {
  'chain-lightning-damage-x': 'chain-lightning-quantity',
  'spotlight-bonus': 'spotlight-angle',
}

function findCoreRowSpanForIndex(rawIndex: number): (CoreRowSpan & { offset: number }) | null {
  for (const span of CORE_ROW_SPANS) {
    if (rawIndex >= span.start && rawIndex < span.end) {
      return { ...span, offset: rawIndex - span.start }
    }
  }
  return null
}

function findCoreEffectWithRarity(
  effectId: string,
  rarity: WorkshopSubmoduleRarity,
): GameModuleEffectDecode | null {
  const span = CORE_ROW_SPANS.find((row) => row.effectId === effectId)
  if (span == null) return null
  for (let i = span.start; i < span.end; i++) {
    const entry = GAME_MODULE_EFFECT_BY_INDEX[i]
    if (entry?.effectId === effectId && entry.rarity === rarity) {
      return { slot: 'core', effectId, rarity }
    }
  }
  return null
}

/** Game table includes Golden Tower Bonus Ancestral at 284; import table starts ILM CD there. */
const CORE_GOLDEN_TOWER_BONUS_ANCESTRAL_INDEX = 284

function decodeCoreHighTierRemap(
  rawIndex: number,
  decoded: GameModuleEffectDecode | null,
  primaryModuleLevel: number,
  chassisMerge?: WorkshopChassisModuleMergeTier | null,
): GameModuleEffectDecode | null {
  const chassisEffectTier =
    chassisMerge != null ? workshopChassisModuleEffectTier(chassisMerge) : null

  if (
    rawIndex === CORE_GOLDEN_TOWER_BONUS_ANCESTRAL_INDEX &&
    chassisEffectTier === 'ancestral'
  ) {
    return { slot: 'core', effectId: 'golden-tower-bonus', rarity: 'ancestral' }
  }
  if (primaryModuleLevel > 0) {
    if (rawIndex === 286) {
      return findCoreEffectWithRarity('golden-tower-duration-s', 'mythic')
    }
    if (rawIndex === 307) {
      return findCoreEffectWithRarity('black-hole-size-m', 'epic')
    }
  }
  if (chassisEffectTier === 'mythic' && primaryModuleLevel === 0) {
    if (rawIndex === 250) {
      return findCoreEffectWithRarity('death-wave-damage-x', 'mythic')
    }
    if (rawIndex === 285) {
      return findCoreEffectWithRarity('golden-tower-duration-s', 'mythic')
    }
    if (rawIndex === 311) {
      return findCoreEffectWithRarity('black-hole-duration-s', 'mythic')
    }
  }
  if (decoded == null) return null

  const row = findCoreRowSpanForIndex(rawIndex)
  if (row == null) return null
  const rowLength = row.end - row.start

  if (
    primaryModuleLevel === 0 &&
    rowLength === 6 &&
    row.offset >= 3
  ) {
    const targetEffectId = CORE_ANCESTRAL_FORWARD_ROW[decoded.effectId]
    if (targetEffectId != null) {
      return findCoreEffectWithRarity(targetEffectId, decoded.rarity)
    }
  }

  if (
    decoded.effectId === 'black-hole-size-m' &&
    decoded.rarity === 'mythic' &&
    row.offset === 1
  ) {
    return findCoreEffectWithRarity('black-hole-cooldown-s', 'mythic')
  }

  if (decoded.effectId === 'spotlight-angle' && decoded.rarity === 'epic' && row.offset === 0) {
    return { slot: 'core', effectId: 'spotlight-angle', rarity: 'ancestral' }
  }

  if (
    decoded.effectId === 'poison-swamp-cooldown-s' &&
    decoded.rarity === 'rare' &&
    row.offset === 0
  ) {
    return findCoreEffectWithRarity('poison-swamp-cooldown-s', 'mythic')
  }

  return null
}

/**
 * Cannon rows with a leading null Common column store Rare at the next compressed index
 * (e.g. Rapid Fire Duration save index 45 → Rare +0.4s, not Epic +0.8s).
 */
function decodeCannonRareAtEpicIndex(
  rawIndex: number,
  decoded: GameModuleEffectDecode,
): GameModuleEffectDecode | null {
  if (decoded.slot !== 'cannon' || decoded.rarity !== 'epic') return null
  const prev = gameModuleEffectByIndex(rawIndex - 1, 0)
  if (prev == null || prev.slot !== 'cannon' || prev.effectId !== decoded.effectId) {
    return null
  }
  if (prev.rarity !== 'rare') return null
  const twoBack = gameModuleEffectByIndex(rawIndex - 2, 0)
  if (twoBack?.slot === 'cannon' && twoBack.effectId === decoded.effectId) {
    return null
  }
  return prev
}

/**
 * Cannon rows with leading null wiki tiers store Epic at the next compressed index
 * (e.g. Super Crit Multi save index 68 → Epic +2x, not Legendary +3).
 */
function decodeCannonEpicAtLegendaryIndex(
  rawIndex: number,
  decoded: GameModuleEffectDecode,
): GameModuleEffectDecode | null {
  if (decoded.slot !== 'cannon' || decoded.rarity !== 'legendary') return null
  const prev = gameModuleEffectByIndex(rawIndex - 1, 0)
  if (prev == null || prev.slot !== 'cannon' || prev.effectId !== decoded.effectId) {
    return null
  }
  if (prev.rarity !== 'epic') return null
  return prev
}

/**
 * Decode save effect index for submodule import.
 * Main ancestral-tier generator modules store the Epic row base index for Epic-only substat rows;
 * bump +3 when that decodes as Epic but Ancestral exists in the same row.
 * Generator assist encodes vs primary chassis level: sparse+primary≥330 → stored as sparse+primary−10;
 * ancestral-family assist may store mythic/ancestral picks as raw−3.
 * Ancestral-family armor common-start rows store Ancestral at sparse offset 6 (index table omits it).
 * High-tier core modules (Mythic+ and ancestral-family) remap sparse indices missing tiers
 * (e.g. 284 → GT Bonus Ancestral, 285 → GT Duration Mythic on Mythic+ main) and paired rows;
 * main modules also forward block-2 tiers to follow-on stats.
 */
function gameModuleEffectForSubmoduleImport(
  raw: number,
  slot: WorkshopAssistModuleSlot,
  moduleLevel: number,
  primaryModuleLevel: number,
  chassisMerge?: WorkshopChassisModuleMergeTier | null,
): GameModuleEffectDecode | null {
  const primaryLevel = Number.isFinite(primaryModuleLevel)
    ? Math.max(0, Math.trunc(primaryModuleLevel))
    : 0
  const rawIndex = Math.trunc(raw)

  if (slot === 'generator' && primaryLevel > 0) {
    const levelEncoded = rawIndex + 10 - primaryLevel
    if (levelEncoded >= 0) {
      const hit =
        decodeGeneratorEffectAtIndex(levelEncoded, moduleLevel) ??
        decodeGeneratorEffectAtIndex(levelEncoded, 0)
      if (hit != null) return hit
    }
  }

  if (slot === 'armor' && isAncestralFamilyChassisMerge(chassisMerge)) {
    const ancestralRow = decodeArmorAncestralCommonStartRow(rawIndex)
    if (ancestralRow != null) return ancestralRow
    if (rawIndex === 150) {
      return { slot: 'armor', effectId: 'wall-health', rarity: 'ancestral' }
    }
  }

  if (slot === 'core' && isHighTierCoreChassisMerge(chassisMerge)) {
    const earlyCore = decodeCoreHighTierRemap(rawIndex, null, primaryLevel, chassisMerge)
    if (earlyCore != null) return earlyCore
  }

  const decoded = gameModuleEffectByIndexForSlot(
    raw,
    slot,
    moduleLevel,
    primaryModuleLevel,
  )
  if (decoded == null) return null
  if (slot === 'armor' && isAncestralFamilyChassisMerge(chassisMerge)) {
    const landMine = decodeArmorLandMineRadiusOnAncestralChassis(rawIndex, decoded)
    if (landMine != null) return landMine
  }
  if (slot === 'core' && isHighTierCoreChassisMerge(chassisMerge)) {
    const coreRemap = decodeCoreHighTierRemap(rawIndex, decoded, primaryLevel, chassisMerge)
    if (coreRemap != null) return coreRemap
  }
  if (slot === 'generator' && isHighTierGeneratorChassisMerge(chassisMerge)) {
    const sparse = decodeGeneratorSparsePlusThree(
      rawIndex,
      moduleLevel,
      primaryLevel,
      decoded,
    )
    if (sparse != null) return sparse
  }
  if (slot === 'cannon') {
    const cannonRare = decodeCannonRareAtEpicIndex(rawIndex, decoded)
    if (cannonRare != null) return cannonRare
    const cannonEpic = decodeCannonEpicAtLegendaryIndex(rawIndex, decoded)
    if (cannonEpic != null) return cannonEpic
  }
  return decoded
}

/** Map equipped module `effects` array (0 = empty slot) to workshop picks. */
export function gameSubmoduleImportFromEffectIndices(
  slot: WorkshopAssistModuleSlot,
  effectIndices: readonly number[],
  moduleLevel = 0,
  primaryModuleLevel = 0,
  chassisMerge?: WorkshopChassisModuleMergeTier | null,
): {
  map: WorkshopSubmoduleSelectionMap
  ordered: WorkshopSubmoduleOrderedSlots
} {
  const ordered: WorkshopSubmoduleOrderedSlots = Array.from(
    { length: WORKSHOP_SUBMODULE_SLOT_COUNT },
    () => null,
  )
  const map: WorkshopSubmoduleSelectionMap = {}
  for (let si = 0; si < effectIndices.length && si < ordered.length; si++) {
    const raw = effectIndices[si]!
    if (raw === 0) continue
    const decoded = gameModuleEffectForSubmoduleImport(
      raw,
      slot,
      moduleLevel,
      primaryModuleLevel,
      chassisMerge,
    )
    if (decoded == null) continue
    const pick = { effectId: decoded.effectId, rarity: decoded.rarity }
    ordered[si] = pick
    map[decoded.effectId] = decoded.rarity
  }
  return { map, ordered }
}

/** Map equipped module `effects` array (0 = empty slot) to workshop selection map. */
export function gameSubmoduleSelectionFromEffectIndices(
  slot: WorkshopAssistModuleSlot,
  effectIndices: readonly number[],
  moduleLevel = 0,
  primaryModuleLevel = 0,
  chassisMerge?: WorkshopChassisModuleMergeTier | null,
): WorkshopSubmoduleSelectionMap {
  return gameSubmoduleImportFromEffectIndices(
    slot,
    effectIndices,
    moduleLevel,
    primaryModuleLevel,
    chassisMerge,
  ).map
}
