/**
 * Game `ModuleItem.infoIndex` → workshop chassis module id.
 * Generated by `scripts/gen-game-module-index.mjs` — edit MANUAL_OVERRIDES there, then re-run.
 */

import type { WorkshopAssistModuleSlot } from '../data/workshopSimModules'
import { CHASSIS_MODULE_ORDERS } from '../data/workshopChassisModuleSelection'

export const GAME_MODULE_INFO_COUNT = 49 as const

/** Save `infoIndex` → workshop id (`null` = generic module with no named chassis). */
export const GAME_MODULE_INFO_INDEX_TO_WORKSHOP_ID: readonly (string | null)[] = [
  null, // 0: generic / unknown
  null, // 1: generic / unknown
  null, // 2: generic / unknown
  null, // 3: generic / unknown
  null, // 4: generic / unknown
  null, // 5: generic / unknown
  "havocBringer", // 6: havocBringer
  "havocBringer", // 7: havocBringer
  "deathPenalty", // 8: deathPenalty
  "beingAnnihilator", // 9: beingAnnihilator
  "astralDeliverance", // 10: astralDeliverance
  "shrinkRay", // 11: shrinkRay
  null, // 12: generic / unknown
  null, // 13: generic / unknown
  null, // 14: generic / unknown
  null, // 15: generic / unknown
  null, // 16: generic / unknown
  null, // 17: generic / unknown
  "negativeMassProjector", // 18: negativeMassProjector
  "wormholeRedirector", // 19: wormholeRedirector
  "antiCubePortal", // 20: antiCubePortal
  "spaceDisplacer", // 21: spaceDisplacer
  "sharpFortitude", // 22: sharpFortitude
  "orbitalAugment", // 23: orbitalAugment
  null, // 24: generic / unknown
  null, // 25: generic / unknown
  null, // 26: generic / unknown
  "blackHoleDigestor", // 27: blackHoleDigestor
  "pulsarHarvester", // 28: pulsarHarvester
  "galaxyCompressor", // 29: galaxyCompressor
  "singularityHarness", // 30: singularityHarness
  "pulsarHarvester", // 31: pulsarHarvester
  "galaxyCompressor", // 32: galaxyCompressor
  "singularityHarness", // 33: singularityHarness
  "projectFunding", // 34: projectFunding
  "restorativeBonus", // 35: restorativeBonus
  null, // 36: generic / unknown
  "multiverseNexus", // 37: multiverseNexus
  "dimensionCore", // 38: dimensionCore
  "harmonyConductor", // 39: harmonyConductor
  "omChip", // 40: omChip
  null, // 41: generic / unknown
  "sharpFortitude", // 42: sharpFortitude
  "projectFunding", // 43: projectFunding
  "magneticHook", // 44: magneticHook
  "amplifyingStrike", // 45: amplifyingStrike
  "orbitalAugment", // 46: orbitalAugment
  "restorativeBonus", // 47: restorativeBonus
  "primordialCollapse", // 48: primordialCollapse
] as const

export function gameWorkshopChassisModuleId(
  infoIndex: number,
  slot: WorkshopAssistModuleSlot,
): string | null {
  if (!Number.isFinite(infoIndex) || infoIndex < 0) return null
  const id = GAME_MODULE_INFO_INDEX_TO_WORKSHOP_ID[Math.trunc(infoIndex)] ?? null
  if (id == null) return null
  return CHASSIS_MODULE_ORDERS[slot].includes(id) ? id : null
}
