/**
 * Game `ModuleManager.effects` index → workshop sub-module effect pick.
 * Generated by `scripts/gen-game-module-effect-index.mjs` from wiki submodule tables.
 */

import type { WorkshopAssistModuleSlot } from '../data/workshopSimModules'
import type { WorkshopSubmoduleRarity } from '../data/workshopSubmoduleEffects'
import type { WorkshopSubmoduleSelectionMap } from '../data/workshopSubmoduleSelection'

export type GameModuleEffectDecode = {
  slot: WorkshopAssistModuleSlot
  effectId: string
  rarity: WorkshopSubmoduleRarity
}

export const GAME_MODULE_EFFECT_COUNT = 330 as const

/** Save effect index → decoded pick (`null` if out of range). Index 0 is Attack Speed common. */
export const GAME_MODULE_EFFECT_BY_INDEX: readonly GameModuleEffectDecode[] = [
  { slot: "cannon", effectId: "attack-speed", rarity: "common" }, // 0
  { slot: "cannon", effectId: "attack-speed", rarity: "rare" }, // 1
  { slot: "cannon", effectId: "attack-speed", rarity: "epic" }, // 2
  { slot: "cannon", effectId: "attack-speed", rarity: "epic" }, // 3
  { slot: "cannon", effectId: "attack-speed", rarity: "legendary" }, // 4
  { slot: "cannon", effectId: "attack-speed", rarity: "mythic" }, // 5
  { slot: "cannon", effectId: "crit-chance", rarity: "common" }, // 6
  { slot: "cannon", effectId: "crit-chance", rarity: "rare" }, // 7
  { slot: "cannon", effectId: "crit-chance", rarity: "epic" }, // 8
  { slot: "cannon", effectId: "crit-chance", rarity: "epic" }, // 9
  { slot: "cannon", effectId: "crit-chance", rarity: "legendary" }, // 10
  { slot: "cannon", effectId: "crit-chance", rarity: "mythic" }, // 11
  { slot: "cannon", effectId: "crit-factor", rarity: "common" }, // 12
  { slot: "cannon", effectId: "crit-factor", rarity: "rare" }, // 13
  { slot: "cannon", effectId: "crit-factor", rarity: "epic" }, // 14
  { slot: "cannon", effectId: "crit-factor", rarity: "epic" }, // 15
  { slot: "cannon", effectId: "crit-factor", rarity: "legendary" }, // 16
  { slot: "cannon", effectId: "crit-factor", rarity: "mythic" }, // 17
  { slot: "cannon", effectId: "attack-range-m", rarity: "common" }, // 18
  { slot: "cannon", effectId: "attack-range-m", rarity: "rare" }, // 19
  { slot: "cannon", effectId: "attack-range-m", rarity: "epic" }, // 20
  { slot: "cannon", effectId: "attack-range-m", rarity: "epic" }, // 21
  { slot: "cannon", effectId: "attack-range-m", rarity: "legendary" }, // 22
  { slot: "cannon", effectId: "attack-range-m", rarity: "mythic" }, // 23
  { slot: "cannon", effectId: "damage-meter-m", rarity: "common" }, // 24
  { slot: "cannon", effectId: "damage-meter-m", rarity: "rare" }, // 25
  { slot: "cannon", effectId: "damage-meter-m", rarity: "epic" }, // 26
  { slot: "cannon", effectId: "damage-meter-m", rarity: "epic" }, // 27
  { slot: "cannon", effectId: "damage-meter-m", rarity: "legendary" }, // 28
  { slot: "cannon", effectId: "damage-meter-m", rarity: "mythic" }, // 29
  { slot: "cannon", effectId: "multishot-chance", rarity: "rare" }, // 30
  { slot: "cannon", effectId: "multishot-chance", rarity: "epic" }, // 31
  { slot: "cannon", effectId: "multishot-chance", rarity: "legendary" }, // 32
  { slot: "cannon", effectId: "multishot-chance", rarity: "legendary" }, // 33
  { slot: "cannon", effectId: "multishot-chance", rarity: "mythic" }, // 34
  { slot: "cannon", effectId: "multishot-targets", rarity: "epic" }, // 35
  { slot: "cannon", effectId: "multishot-targets", rarity: "legendary" }, // 36
  { slot: "cannon", effectId: "multishot-targets", rarity: "legendary" }, // 37
  { slot: "cannon", effectId: "multishot-targets", rarity: "mythic" }, // 38
  { slot: "cannon", effectId: "rapid-fire-chance", rarity: "rare" }, // 39
  { slot: "cannon", effectId: "rapid-fire-chance", rarity: "epic" }, // 40
  { slot: "cannon", effectId: "rapid-fire-chance", rarity: "legendary" }, // 41
  { slot: "cannon", effectId: "rapid-fire-chance", rarity: "legendary" }, // 42
  { slot: "cannon", effectId: "rapid-fire-chance", rarity: "mythic" }, // 43
  { slot: "cannon", effectId: "rapid-fire-duration", rarity: "rare" }, // 44
  { slot: "cannon", effectId: "rapid-fire-duration", rarity: "epic" }, // 45
  { slot: "cannon", effectId: "rapid-fire-duration", rarity: "legendary" }, // 46
  { slot: "cannon", effectId: "rapid-fire-duration", rarity: "legendary" }, // 47
  { slot: "cannon", effectId: "rapid-fire-duration", rarity: "mythic" }, // 48
  { slot: "cannon", effectId: "bounce-shot-chance", rarity: "rare" }, // 49
  { slot: "cannon", effectId: "bounce-shot-chance", rarity: "epic" }, // 50
  { slot: "cannon", effectId: "bounce-shot-chance", rarity: "legendary" }, // 51
  { slot: "cannon", effectId: "bounce-shot-chance", rarity: "legendary" }, // 52
  { slot: "cannon", effectId: "bounce-shot-chance", rarity: "mythic" }, // 53
  { slot: "cannon", effectId: "bounce-shot-targets", rarity: "epic" }, // 54
  { slot: "cannon", effectId: "bounce-shot-targets", rarity: "legendary" }, // 55
  { slot: "cannon", effectId: "bounce-shot-targets", rarity: "legendary" }, // 56
  { slot: "cannon", effectId: "bounce-shot-targets", rarity: "mythic" }, // 57
  { slot: "cannon", effectId: "bounce-shot-range", rarity: "rare" }, // 58
  { slot: "cannon", effectId: "bounce-shot-range", rarity: "epic" }, // 59
  { slot: "cannon", effectId: "bounce-shot-range", rarity: "legendary" }, // 60
  { slot: "cannon", effectId: "bounce-shot-range", rarity: "legendary" }, // 61
  { slot: "cannon", effectId: "bounce-shot-range", rarity: "mythic" }, // 62
  { slot: "cannon", effectId: "super-crit-chance", rarity: "epic" }, // 63
  { slot: "cannon", effectId: "super-crit-chance", rarity: "legendary" }, // 64
  { slot: "cannon", effectId: "super-crit-chance", rarity: "legendary" }, // 65
  { slot: "cannon", effectId: "super-crit-chance", rarity: "mythic" }, // 66
  { slot: "cannon", effectId: "super-crit-multi", rarity: "epic" }, // 67
  { slot: "cannon", effectId: "super-crit-multi", rarity: "legendary" }, // 68
  { slot: "cannon", effectId: "super-crit-multi", rarity: "legendary" }, // 69
  { slot: "cannon", effectId: "super-crit-multi", rarity: "mythic" }, // 70
  { slot: "cannon", effectId: "rend-armor-chance", rarity: "legendary" }, // 71
  { slot: "cannon", effectId: "rend-armor-chance", rarity: "legendary" }, // 72
  { slot: "cannon", effectId: "rend-armor-chance", rarity: "mythic" }, // 73
  { slot: "cannon", effectId: "rend-armor-multi", rarity: "legendary" }, // 74
  { slot: "cannon", effectId: "rend-armor-multi", rarity: "legendary" }, // 75
  { slot: "cannon", effectId: "rend-armor-multi", rarity: "mythic" }, // 76
  { slot: "cannon", effectId: "max-rend-armor-multi", rarity: "legendary" }, // 77
  { slot: "cannon", effectId: "max-rend-armor-multi", rarity: "legendary" }, // 78
  { slot: "cannon", effectId: "max-rend-armor-multi", rarity: "mythic" }, // 79
  { slot: "armor", effectId: "health-regen", rarity: "common" }, // 80
  { slot: "armor", effectId: "health-regen", rarity: "rare" }, // 81
  { slot: "armor", effectId: "health-regen", rarity: "epic" }, // 82
  { slot: "armor", effectId: "health-regen", rarity: "epic" }, // 83
  { slot: "armor", effectId: "health-regen", rarity: "legendary" }, // 84
  { slot: "armor", effectId: "health-regen", rarity: "mythic" }, // 85
  { slot: "armor", effectId: "defense", rarity: "common" }, // 86
  { slot: "armor", effectId: "defense", rarity: "rare" }, // 87
  { slot: "armor", effectId: "defense", rarity: "epic" }, // 88
  { slot: "armor", effectId: "defense", rarity: "epic" }, // 89
  { slot: "armor", effectId: "defense", rarity: "legendary" }, // 90
  { slot: "armor", effectId: "defense", rarity: "mythic" }, // 91
  { slot: "armor", effectId: "defense-absolute", rarity: "common" }, // 92
  { slot: "armor", effectId: "defense-absolute", rarity: "rare" }, // 93
  { slot: "armor", effectId: "defense-absolute", rarity: "epic" }, // 94
  { slot: "armor", effectId: "defense-absolute", rarity: "epic" }, // 95
  { slot: "armor", effectId: "defense-absolute", rarity: "legendary" }, // 96
  { slot: "armor", effectId: "defense-absolute", rarity: "mythic" }, // 97
  { slot: "armor", effectId: "thorns-damage", rarity: "epic" }, // 98
  { slot: "armor", effectId: "thorns-damage", rarity: "legendary" }, // 99
  { slot: "armor", effectId: "thorns-damage", rarity: "legendary" }, // 100
  { slot: "armor", effectId: "thorns-damage", rarity: "mythic" }, // 101
  { slot: "armor", effectId: "lifesteal", rarity: "epic" }, // 102
  { slot: "armor", effectId: "lifesteal", rarity: "legendary" }, // 103
  { slot: "armor", effectId: "lifesteal", rarity: "legendary" }, // 104
  { slot: "armor", effectId: "lifesteal", rarity: "mythic" }, // 105
  { slot: "armor", effectId: "knockback-chance", rarity: "epic" }, // 106
  { slot: "armor", effectId: "knockback-chance", rarity: "legendary" }, // 107
  { slot: "armor", effectId: "knockback-chance", rarity: "legendary" }, // 108
  { slot: "armor", effectId: "knockback-chance", rarity: "mythic" }, // 109
  { slot: "armor", effectId: "knockback-force", rarity: "epic" }, // 110
  { slot: "armor", effectId: "knockback-force", rarity: "legendary" }, // 111
  { slot: "armor", effectId: "knockback-force", rarity: "legendary" }, // 112
  { slot: "armor", effectId: "knockback-force", rarity: "mythic" }, // 113
  { slot: "armor", effectId: "orb-speed", rarity: "epic" }, // 114
  { slot: "armor", effectId: "orb-speed", rarity: "legendary" }, // 115
  { slot: "armor", effectId: "orb-speed", rarity: "legendary" }, // 116
  { slot: "armor", effectId: "orb-speed", rarity: "mythic" }, // 117
  { slot: "armor", effectId: "orbs", rarity: "mythic" }, // 118
  { slot: "armor", effectId: "orbs", rarity: "ancestral" }, // 119
  { slot: "armor", effectId: "shockwave-size", rarity: "epic" }, // 120
  { slot: "armor", effectId: "shockwave-size", rarity: "legendary" }, // 121
  { slot: "armor", effectId: "shockwave-size", rarity: "legendary" }, // 122
  { slot: "armor", effectId: "shockwave-size", rarity: "mythic" }, // 123
  { slot: "armor", effectId: "shockwave-frequency-s", rarity: "epic" }, // 124
  { slot: "armor", effectId: "shockwave-frequency-s", rarity: "legendary" }, // 125
  { slot: "armor", effectId: "shockwave-frequency-s", rarity: "legendary" }, // 126
  { slot: "armor", effectId: "shockwave-frequency-s", rarity: "mythic" }, // 127
  { slot: "armor", effectId: "land-mine-damage", rarity: "rare" }, // 128
  { slot: "armor", effectId: "land-mine-damage", rarity: "epic" }, // 129
  { slot: "armor", effectId: "land-mine-damage", rarity: "legendary" }, // 130
  { slot: "armor", effectId: "land-mine-damage", rarity: "legendary" }, // 131
  { slot: "armor", effectId: "land-mine-damage", rarity: "mythic" }, // 132
  { slot: "armor", effectId: "land-mine-chance", rarity: "rare" }, // 133
  { slot: "armor", effectId: "land-mine-chance", rarity: "epic" }, // 134
  { slot: "armor", effectId: "land-mine-chance", rarity: "legendary" }, // 135
  { slot: "armor", effectId: "land-mine-chance", rarity: "legendary" }, // 136
  { slot: "armor", effectId: "land-mine-chance", rarity: "mythic" }, // 137
  { slot: "armor", effectId: "land-mine-radius", rarity: "rare" }, // 138
  { slot: "armor", effectId: "land-mine-radius", rarity: "epic" }, // 139
  { slot: "armor", effectId: "land-mine-radius", rarity: "legendary" }, // 140
  { slot: "armor", effectId: "land-mine-radius", rarity: "legendary" }, // 141
  { slot: "armor", effectId: "land-mine-radius", rarity: "mythic" }, // 142
  { slot: "armor", effectId: "death-defy", rarity: "legendary" }, // 143
  { slot: "armor", effectId: "death-defy", rarity: "legendary" }, // 144
  { slot: "armor", effectId: "death-defy", rarity: "mythic" }, // 145
  { slot: "armor", effectId: "wall-health", rarity: "epic" }, // 146
  { slot: "armor", effectId: "wall-health", rarity: "legendary" }, // 147
  { slot: "armor", effectId: "wall-health", rarity: "legendary" }, // 148
  { slot: "armor", effectId: "wall-health", rarity: "mythic" }, // 149
  { slot: "armor", effectId: "wall-rebuild-s", rarity: "epic" }, // 150
  { slot: "armor", effectId: "wall-rebuild-s", rarity: "legendary" }, // 151
  { slot: "armor", effectId: "wall-rebuild-s", rarity: "legendary" }, // 152
  { slot: "armor", effectId: "wall-rebuild-s", rarity: "mythic" }, // 153
  { slot: "generator", effectId: "cash-bonus", rarity: "common" }, // 154
  { slot: "generator", effectId: "cash-bonus", rarity: "rare" }, // 155
  { slot: "generator", effectId: "cash-bonus", rarity: "epic" }, // 156
  { slot: "generator", effectId: "cash-bonus", rarity: "epic" }, // 157
  { slot: "generator", effectId: "cash-bonus", rarity: "legendary" }, // 158
  { slot: "generator", effectId: "cash-bonus", rarity: "mythic" }, // 159
  { slot: "generator", effectId: "cash-wave", rarity: "common" }, // 160
  { slot: "generator", effectId: "cash-wave", rarity: "rare" }, // 161
  { slot: "generator", effectId: "cash-wave", rarity: "epic" }, // 162
  { slot: "generator", effectId: "cash-wave", rarity: "epic" }, // 163
  { slot: "generator", effectId: "cash-wave", rarity: "legendary" }, // 164
  { slot: "generator", effectId: "cash-wave", rarity: "mythic" }, // 165
  { slot: "generator", effectId: "coins-kill-bonus", rarity: "common" }, // 166
  { slot: "generator", effectId: "coins-kill-bonus", rarity: "rare" }, // 167
  { slot: "generator", effectId: "coins-kill-bonus", rarity: "epic" }, // 168
  { slot: "generator", effectId: "coins-kill-bonus", rarity: "epic" }, // 169
  { slot: "generator", effectId: "coins-kill-bonus", rarity: "legendary" }, // 170
  { slot: "generator", effectId: "coins-kill-bonus", rarity: "mythic" }, // 171
  { slot: "generator", effectId: "coins-wave", rarity: "common" }, // 172
  { slot: "generator", effectId: "coins-wave", rarity: "rare" }, // 173
  { slot: "generator", effectId: "coins-wave", rarity: "epic" }, // 174
  { slot: "generator", effectId: "coins-wave", rarity: "epic" }, // 175
  { slot: "generator", effectId: "coins-wave", rarity: "legendary" }, // 176
  { slot: "generator", effectId: "coins-wave", rarity: "mythic" }, // 177
  { slot: "generator", effectId: "free-attack-upgrade", rarity: "common" }, // 178
  { slot: "generator", effectId: "free-attack-upgrade", rarity: "rare" }, // 179
  { slot: "generator", effectId: "free-attack-upgrade", rarity: "epic" }, // 180
  { slot: "generator", effectId: "free-attack-upgrade", rarity: "epic" }, // 181
  { slot: "generator", effectId: "free-attack-upgrade", rarity: "legendary" }, // 182
  { slot: "generator", effectId: "free-attack-upgrade", rarity: "mythic" }, // 183
  { slot: "generator", effectId: "free-defense-upgrade", rarity: "common" }, // 184
  { slot: "generator", effectId: "free-defense-upgrade", rarity: "rare" }, // 185
  { slot: "generator", effectId: "free-defense-upgrade", rarity: "epic" }, // 186
  { slot: "generator", effectId: "free-defense-upgrade", rarity: "epic" }, // 187
  { slot: "generator", effectId: "free-defense-upgrade", rarity: "legendary" }, // 188
  { slot: "generator", effectId: "free-defense-upgrade", rarity: "mythic" }, // 189
  { slot: "generator", effectId: "free-utility-upgrade", rarity: "common" }, // 190
  { slot: "generator", effectId: "free-utility-upgrade", rarity: "rare" }, // 191
  { slot: "generator", effectId: "free-utility-upgrade", rarity: "epic" }, // 192
  { slot: "generator", effectId: "free-utility-upgrade", rarity: "epic" }, // 193
  { slot: "generator", effectId: "free-utility-upgrade", rarity: "legendary" }, // 194
  { slot: "generator", effectId: "free-utility-upgrade", rarity: "mythic" }, // 195
  { slot: "generator", effectId: "interest-wave", rarity: "epic" }, // 196
  { slot: "generator", effectId: "interest-wave", rarity: "legendary" }, // 197
  { slot: "generator", effectId: "interest-wave", rarity: "legendary" }, // 198
  { slot: "generator", effectId: "interest-wave", rarity: "mythic" }, // 199
  { slot: "generator", effectId: "recovery-amount", rarity: "epic" }, // 200
  { slot: "generator", effectId: "recovery-amount", rarity: "legendary" }, // 201
  { slot: "generator", effectId: "recovery-amount", rarity: "legendary" }, // 202
  { slot: "generator", effectId: "recovery-amount", rarity: "mythic" }, // 203
  { slot: "generator", effectId: "max-recovery", rarity: "epic" }, // 204
  { slot: "generator", effectId: "max-recovery", rarity: "legendary" }, // 205
  { slot: "generator", effectId: "max-recovery", rarity: "legendary" }, // 206
  { slot: "generator", effectId: "max-recovery", rarity: "mythic" }, // 207
  { slot: "generator", effectId: "package-chance", rarity: "epic" }, // 208
  { slot: "generator", effectId: "package-chance", rarity: "legendary" }, // 209
  { slot: "generator", effectId: "package-chance", rarity: "legendary" }, // 210
  { slot: "generator", effectId: "package-chance", rarity: "mythic" }, // 211
  { slot: "generator", effectId: "enemy-attack-level-skip", rarity: "epic" }, // 212
  { slot: "generator", effectId: "enemy-attack-level-skip", rarity: "legendary" }, // 213
  { slot: "generator", effectId: "enemy-attack-level-skip", rarity: "legendary" }, // 214
  { slot: "generator", effectId: "enemy-attack-level-skip", rarity: "mythic" }, // 215
  { slot: "generator", effectId: "enemy-health-level-skip", rarity: "epic" }, // 216
  { slot: "generator", effectId: "enemy-health-level-skip", rarity: "legendary" }, // 217
  { slot: "generator", effectId: "enemy-health-level-skip", rarity: "legendary" }, // 218
  { slot: "generator", effectId: "enemy-health-level-skip", rarity: "mythic" }, // 219
  { slot: "core", effectId: "chain-lightning-damage-x", rarity: "legendary" }, // 220
  { slot: "core", effectId: "chain-lightning-damage-x", rarity: "mythic" }, // 221
  { slot: "core", effectId: "chain-lightning-damage-x", rarity: "ancestral" }, // 222
  { slot: "core", effectId: "chain-lightning-damage-x", rarity: "epic" }, // 223
  { slot: "core", effectId: "chain-lightning-damage-x", rarity: "legendary" }, // 224
  { slot: "core", effectId: "chain-lightning-damage-x", rarity: "mythic" }, // 225
  { slot: "core", effectId: "chain-lightning-quantity", rarity: "epic" }, // 226
  { slot: "core", effectId: "chain-lightning-quantity", rarity: "legendary" }, // 227
  { slot: "core", effectId: "chain-lightning-quantity", rarity: "legendary" }, // 228
  { slot: "core", effectId: "chain-lightning-quantity", rarity: "mythic" }, // 229
  { slot: "core", effectId: "chain-lightning-chance", rarity: "legendary" }, // 230
  { slot: "core", effectId: "chain-lightning-chance", rarity: "mythic" }, // 231
  { slot: "core", effectId: "chain-lightning-chance", rarity: "ancestral" }, // 232
  { slot: "core", effectId: "chain-lightning-chance", rarity: "epic" }, // 233
  { slot: "core", effectId: "chain-lightning-chance", rarity: "legendary" }, // 234
  { slot: "core", effectId: "chain-lightning-chance", rarity: "mythic" }, // 235
  { slot: "core", effectId: "smart-missiles-damage", rarity: "legendary" }, // 236
  { slot: "core", effectId: "smart-missiles-damage", rarity: "mythic" }, // 237
  { slot: "core", effectId: "smart-missiles-damage", rarity: "ancestral" }, // 238
  { slot: "core", effectId: "smart-missiles-damage", rarity: "epic" }, // 239
  { slot: "core", effectId: "smart-missiles-damage", rarity: "legendary" }, // 240
  { slot: "core", effectId: "smart-missiles-damage", rarity: "mythic" }, // 241
  { slot: "core", effectId: "smart-missiles-quantity", rarity: "epic" }, // 242
  { slot: "core", effectId: "smart-missiles-quantity", rarity: "legendary" }, // 243
  { slot: "core", effectId: "smart-missiles-quantity", rarity: "legendary" }, // 244
  { slot: "core", effectId: "smart-missiles-quantity", rarity: "mythic" }, // 245
  { slot: "core", effectId: "smart-missiles-cooldown-s", rarity: "legendary" }, // 246
  { slot: "core", effectId: "smart-missiles-cooldown-s", rarity: "legendary" }, // 247
  { slot: "core", effectId: "smart-missiles-cooldown-s", rarity: "mythic" }, // 248
  { slot: "core", effectId: "death-wave-cooldown-s", rarity: "legendary" }, // 249
  { slot: "core", effectId: "death-wave-cooldown-s", rarity: "legendary" }, // 250
  { slot: "core", effectId: "death-wave-cooldown-s", rarity: "mythic" }, // 251
  { slot: "core", effectId: "death-wave-quantity", rarity: "legendary" }, // 252
  { slot: "core", effectId: "death-wave-quantity", rarity: "legendary" }, // 253
  { slot: "core", effectId: "death-wave-quantity", rarity: "mythic" }, // 254
  { slot: "core", effectId: "death-wave-damage-x", rarity: "legendary" }, // 255
  { slot: "core", effectId: "death-wave-damage-x", rarity: "mythic" }, // 256
  { slot: "core", effectId: "death-wave-damage-x", rarity: "ancestral" }, // 257
  { slot: "core", effectId: "death-wave-damage-x", rarity: "epic" }, // 258
  { slot: "core", effectId: "death-wave-damage-x", rarity: "legendary" }, // 259
  { slot: "core", effectId: "death-wave-damage-x", rarity: "mythic" }, // 260
  { slot: "core", effectId: "chrono-field-duration-s", rarity: "legendary" }, // 261
  { slot: "core", effectId: "chrono-field-duration-s", rarity: "legendary" }, // 262
  { slot: "core", effectId: "chrono-field-duration-s", rarity: "mythic" }, // 263
  { slot: "core", effectId: "chrono-field-speed-reduction", rarity: "epic" }, // 264
  { slot: "core", effectId: "chrono-field-speed-reduction", rarity: "legendary" }, // 265
  { slot: "core", effectId: "chrono-field-speed-reduction", rarity: "legendary" }, // 266
  { slot: "core", effectId: "chrono-field-speed-reduction", rarity: "mythic" }, // 267
  { slot: "core", effectId: "chrono-field-cooldown-s", rarity: "legendary" }, // 268
  { slot: "core", effectId: "chrono-field-cooldown-s", rarity: "legendary" }, // 269
  { slot: "core", effectId: "chrono-field-cooldown-s", rarity: "mythic" }, // 270
  { slot: "core", effectId: "inner-land-mines-damage-x", rarity: "legendary" }, // 271
  { slot: "core", effectId: "inner-land-mines-damage-x", rarity: "mythic" }, // 272
  { slot: "core", effectId: "inner-land-mines-damage-x", rarity: "ancestral" }, // 273
  { slot: "core", effectId: "inner-land-mines-damage-x", rarity: "epic" }, // 274
  { slot: "core", effectId: "inner-land-mines-damage-x", rarity: "legendary" }, // 275
  { slot: "core", effectId: "inner-land-mines-damage-x", rarity: "mythic" }, // 276
  { slot: "core", effectId: "inner-land-mines-quantity", rarity: "legendary" }, // 277
  { slot: "core", effectId: "inner-land-mines-quantity", rarity: "legendary" }, // 278
  { slot: "core", effectId: "inner-land-mines-quantity", rarity: "mythic" }, // 279
  { slot: "core", effectId: "golden-tower-bonus", rarity: "epic" }, // 280
  { slot: "core", effectId: "golden-tower-bonus", rarity: "legendary" }, // 281
  { slot: "core", effectId: "golden-tower-bonus", rarity: "legendary" }, // 282
  { slot: "core", effectId: "golden-tower-bonus", rarity: "mythic" }, // 283
  { slot: "core", effectId: "inner-land-mines-cooldown-s", rarity: "epic" }, // 284
  { slot: "core", effectId: "inner-land-mines-cooldown-s", rarity: "legendary" }, // 285
  { slot: "core", effectId: "inner-land-mines-cooldown-s", rarity: "legendary" }, // 286
  { slot: "core", effectId: "inner-land-mines-cooldown-s", rarity: "mythic" }, // 287
  { slot: "core", effectId: "golden-tower-duration-s", rarity: "legendary" }, // 288
  { slot: "core", effectId: "golden-tower-duration-s", rarity: "legendary" }, // 289
  { slot: "core", effectId: "golden-tower-duration-s", rarity: "mythic" }, // 290
  { slot: "core", effectId: "golden-tower-cooldown-s", rarity: "legendary" }, // 291
  { slot: "core", effectId: "golden-tower-cooldown-s", rarity: "legendary" }, // 292
  { slot: "core", effectId: "golden-tower-cooldown-s", rarity: "mythic" }, // 293
  { slot: "core", effectId: "poison-swamp-damage-x", rarity: "legendary" }, // 294
  { slot: "core", effectId: "poison-swamp-damage-x", rarity: "mythic" }, // 295
  { slot: "core", effectId: "poison-swamp-damage-x", rarity: "ancestral" }, // 296
  { slot: "core", effectId: "poison-swamp-damage-x", rarity: "epic" }, // 297
  { slot: "core", effectId: "poison-swamp-damage-x", rarity: "legendary" }, // 298
  { slot: "core", effectId: "poison-swamp-damage-x", rarity: "mythic" }, // 299
  { slot: "core", effectId: "poison-swamp-duration-s", rarity: "legendary" }, // 300
  { slot: "core", effectId: "poison-swamp-duration-s", rarity: "legendary" }, // 301
  { slot: "core", effectId: "poison-swamp-duration-s", rarity: "mythic" }, // 302
  { slot: "core", effectId: "poison-swamp-cooldown-s", rarity: "rare" }, // 303
  { slot: "core", effectId: "poison-swamp-cooldown-s", rarity: "epic" }, // 304
  { slot: "core", effectId: "poison-swamp-cooldown-s", rarity: "legendary" }, // 305
  { slot: "core", effectId: "poison-swamp-cooldown-s", rarity: "legendary" }, // 306
  { slot: "core", effectId: "poison-swamp-cooldown-s", rarity: "mythic" }, // 307
  { slot: "core", effectId: "black-hole-cooldown-s", rarity: "legendary" }, // 308
  { slot: "core", effectId: "black-hole-cooldown-s", rarity: "legendary" }, // 309
  { slot: "core", effectId: "black-hole-cooldown-s", rarity: "mythic" }, // 310
  { slot: "core", effectId: "black-hole-duration-s", rarity: "legendary" }, // 311
  { slot: "core", effectId: "black-hole-duration-s", rarity: "legendary" }, // 312
  { slot: "core", effectId: "black-hole-duration-s", rarity: "mythic" }, // 313
  { slot: "core", effectId: "black-hole-size-m", rarity: "legendary" }, // 314
  { slot: "core", effectId: "black-hole-size-m", rarity: "mythic" }, // 315
  { slot: "core", effectId: "black-hole-size-m", rarity: "ancestral" }, // 316
  { slot: "core", effectId: "black-hole-size-m", rarity: "epic" }, // 317
  { slot: "core", effectId: "black-hole-size-m", rarity: "legendary" }, // 318
  { slot: "core", effectId: "black-hole-size-m", rarity: "mythic" }, // 319
  { slot: "core", effectId: "spotlight-bonus", rarity: "legendary" }, // 320
  { slot: "core", effectId: "spotlight-bonus", rarity: "mythic" }, // 321
  { slot: "core", effectId: "spotlight-bonus", rarity: "ancestral" }, // 322
  { slot: "core", effectId: "spotlight-bonus", rarity: "epic" }, // 323
  { slot: "core", effectId: "spotlight-bonus", rarity: "legendary" }, // 324
  { slot: "core", effectId: "spotlight-bonus", rarity: "mythic" }, // 325
  { slot: "core", effectId: "spotlight-angle", rarity: "epic" }, // 326
  { slot: "core", effectId: "spotlight-angle", rarity: "legendary" }, // 327
  { slot: "core", effectId: "spotlight-angle", rarity: "legendary" }, // 328
  { slot: "core", effectId: "spotlight-angle", rarity: "mythic" }, // 329
] as const

export function gameModuleEffectByIndex(index: number): GameModuleEffectDecode | null {
  if (!Number.isFinite(index) || index < 0) return null
  return GAME_MODULE_EFFECT_BY_INDEX[Math.trunc(index)] ?? null
}

/** Map equipped module `effects` array (0 = empty slot) to workshop selection map. */
export function gameSubmoduleSelectionFromEffectIndices(
  slot: WorkshopAssistModuleSlot,
  effectIndices: readonly number[],
): WorkshopSubmoduleSelectionMap {
  const out: WorkshopSubmoduleSelectionMap = {}
  for (const raw of effectIndices) {
    if (raw === 0) continue
    const decoded = gameModuleEffectByIndex(raw)
    if (decoded == null || decoded.slot !== slot) continue
    out[decoded.effectId] = decoded.rarity
  }
  return out
}
